package com.future.dao4ora.po;

import java.util.Date;

public class EndorsementEndorse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENDORSEMENT_ENDORSE.PROPOSALSID
     *
     * @mbggenerated
     */
    private String proposalsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENDORSEMENT_ENDORSE.BATCHID
     *
     * @mbggenerated
     */
    private String batchid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENDORSEMENT_ENDORSE.POLICYNO
     *
     * @mbggenerated
     */
    private String policyno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENDORSEMENT_ENDORSE.BRANCHID
     *
     * @mbggenerated
     */
    private String branchid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENDORSEMENT_ENDORSE.AMOUNT
     *
     * @mbggenerated
     */
    private Short amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENDORSEMENT_ENDORSE.FINISHTINME
     *
     * @mbggenerated
     */
    private Date finishtinme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENDORSEMENT_ENDORSE.OUTPOLICYNO
     *
     * @mbggenerated
     */
    private String outpolicyno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENDORSEMENT_ENDORSE.EXTENDFLOW
     *
     * @mbggenerated
     */
    private String extendflow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENDORSEMENT_ENDORSE.TYPE
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENDORSEMENT_ENDORSE.CREATESTAMP
     *
     * @mbggenerated
     */
    private Date createstamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENDORSEMENT_ENDORSE.LASTUPDATESTAMP
     *
     * @mbggenerated
     */
    private Date lastupdatestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENDORSEMENT_ENDORSE.NUM
     *
     * @mbggenerated
     */
    private Short num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENDORSEMENT_ENDORSE.GATEWAYTIME
     *
     * @mbggenerated
     */
    private Date gatewaytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENDORSEMENT_ENDORSE.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENDORSEMENT_ENDORSE.GATEWAYFLOW
     *
     * @mbggenerated
     */
    private String gatewayflow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENDORSEMENT_ENDORSE.RETURNCODE
     *
     * @mbggenerated
     */
    private String returncode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENDORSEMENT_ENDORSE.REASON
     *
     * @mbggenerated
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENDORSEMENT_ENDORSE.STATE
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENDORSEMENT_ENDORSE
     *
     * @mbggenerated
     */
    public EndorsementEndorse(String proposalsid, String batchid, String policyno, String branchid, Short amount, Date finishtinme, String outpolicyno, String extendflow, String type, Date createstamp, Date lastupdatestamp, Short num, Date gatewaytime, String status, String gatewayflow, String returncode, String reason, String state) {
        this.proposalsid = proposalsid;
        this.batchid = batchid;
        this.policyno = policyno;
        this.branchid = branchid;
        this.amount = amount;
        this.finishtinme = finishtinme;
        this.outpolicyno = outpolicyno;
        this.extendflow = extendflow;
        this.type = type;
        this.createstamp = createstamp;
        this.lastupdatestamp = lastupdatestamp;
        this.num = num;
        this.gatewaytime = gatewaytime;
        this.status = status;
        this.gatewayflow = gatewayflow;
        this.returncode = returncode;
        this.reason = reason;
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENDORSEMENT_ENDORSE
     *
     * @mbggenerated
     */
    public EndorsementEndorse() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENDORSEMENT_ENDORSE.PROPOSALSID
     *
     * @return the value of ENDORSEMENT_ENDORSE.PROPOSALSID
     *
     * @mbggenerated
     */
    public String getProposalsid() {
        return proposalsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENDORSEMENT_ENDORSE.PROPOSALSID
     *
     * @param proposalsid the value for ENDORSEMENT_ENDORSE.PROPOSALSID
     *
     * @mbggenerated
     */
    public void setProposalsid(String proposalsid) {
        this.proposalsid = proposalsid == null ? null : proposalsid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENDORSEMENT_ENDORSE.BATCHID
     *
     * @return the value of ENDORSEMENT_ENDORSE.BATCHID
     *
     * @mbggenerated
     */
    public String getBatchid() {
        return batchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENDORSEMENT_ENDORSE.BATCHID
     *
     * @param batchid the value for ENDORSEMENT_ENDORSE.BATCHID
     *
     * @mbggenerated
     */
    public void setBatchid(String batchid) {
        this.batchid = batchid == null ? null : batchid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENDORSEMENT_ENDORSE.POLICYNO
     *
     * @return the value of ENDORSEMENT_ENDORSE.POLICYNO
     *
     * @mbggenerated
     */
    public String getPolicyno() {
        return policyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENDORSEMENT_ENDORSE.POLICYNO
     *
     * @param policyno the value for ENDORSEMENT_ENDORSE.POLICYNO
     *
     * @mbggenerated
     */
    public void setPolicyno(String policyno) {
        this.policyno = policyno == null ? null : policyno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENDORSEMENT_ENDORSE.BRANCHID
     *
     * @return the value of ENDORSEMENT_ENDORSE.BRANCHID
     *
     * @mbggenerated
     */
    public String getBranchid() {
        return branchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENDORSEMENT_ENDORSE.BRANCHID
     *
     * @param branchid the value for ENDORSEMENT_ENDORSE.BRANCHID
     *
     * @mbggenerated
     */
    public void setBranchid(String branchid) {
        this.branchid = branchid == null ? null : branchid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENDORSEMENT_ENDORSE.AMOUNT
     *
     * @return the value of ENDORSEMENT_ENDORSE.AMOUNT
     *
     * @mbggenerated
     */
    public Short getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENDORSEMENT_ENDORSE.AMOUNT
     *
     * @param amount the value for ENDORSEMENT_ENDORSE.AMOUNT
     *
     * @mbggenerated
     */
    public void setAmount(Short amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENDORSEMENT_ENDORSE.FINISHTINME
     *
     * @return the value of ENDORSEMENT_ENDORSE.FINISHTINME
     *
     * @mbggenerated
     */
    public Date getFinishtinme() {
        return finishtinme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENDORSEMENT_ENDORSE.FINISHTINME
     *
     * @param finishtinme the value for ENDORSEMENT_ENDORSE.FINISHTINME
     *
     * @mbggenerated
     */
    public void setFinishtinme(Date finishtinme) {
        this.finishtinme = finishtinme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENDORSEMENT_ENDORSE.OUTPOLICYNO
     *
     * @return the value of ENDORSEMENT_ENDORSE.OUTPOLICYNO
     *
     * @mbggenerated
     */
    public String getOutpolicyno() {
        return outpolicyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENDORSEMENT_ENDORSE.OUTPOLICYNO
     *
     * @param outpolicyno the value for ENDORSEMENT_ENDORSE.OUTPOLICYNO
     *
     * @mbggenerated
     */
    public void setOutpolicyno(String outpolicyno) {
        this.outpolicyno = outpolicyno == null ? null : outpolicyno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENDORSEMENT_ENDORSE.EXTENDFLOW
     *
     * @return the value of ENDORSEMENT_ENDORSE.EXTENDFLOW
     *
     * @mbggenerated
     */
    public String getExtendflow() {
        return extendflow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENDORSEMENT_ENDORSE.EXTENDFLOW
     *
     * @param extendflow the value for ENDORSEMENT_ENDORSE.EXTENDFLOW
     *
     * @mbggenerated
     */
    public void setExtendflow(String extendflow) {
        this.extendflow = extendflow == null ? null : extendflow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENDORSEMENT_ENDORSE.TYPE
     *
     * @return the value of ENDORSEMENT_ENDORSE.TYPE
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENDORSEMENT_ENDORSE.TYPE
     *
     * @param type the value for ENDORSEMENT_ENDORSE.TYPE
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENDORSEMENT_ENDORSE.CREATESTAMP
     *
     * @return the value of ENDORSEMENT_ENDORSE.CREATESTAMP
     *
     * @mbggenerated
     */
    public Date getCreatestamp() {
        return createstamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENDORSEMENT_ENDORSE.CREATESTAMP
     *
     * @param createstamp the value for ENDORSEMENT_ENDORSE.CREATESTAMP
     *
     * @mbggenerated
     */
    public void setCreatestamp(Date createstamp) {
        this.createstamp = createstamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENDORSEMENT_ENDORSE.LASTUPDATESTAMP
     *
     * @return the value of ENDORSEMENT_ENDORSE.LASTUPDATESTAMP
     *
     * @mbggenerated
     */
    public Date getLastupdatestamp() {
        return lastupdatestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENDORSEMENT_ENDORSE.LASTUPDATESTAMP
     *
     * @param lastupdatestamp the value for ENDORSEMENT_ENDORSE.LASTUPDATESTAMP
     *
     * @mbggenerated
     */
    public void setLastupdatestamp(Date lastupdatestamp) {
        this.lastupdatestamp = lastupdatestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENDORSEMENT_ENDORSE.NUM
     *
     * @return the value of ENDORSEMENT_ENDORSE.NUM
     *
     * @mbggenerated
     */
    public Short getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENDORSEMENT_ENDORSE.NUM
     *
     * @param num the value for ENDORSEMENT_ENDORSE.NUM
     *
     * @mbggenerated
     */
    public void setNum(Short num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENDORSEMENT_ENDORSE.GATEWAYTIME
     *
     * @return the value of ENDORSEMENT_ENDORSE.GATEWAYTIME
     *
     * @mbggenerated
     */
    public Date getGatewaytime() {
        return gatewaytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENDORSEMENT_ENDORSE.GATEWAYTIME
     *
     * @param gatewaytime the value for ENDORSEMENT_ENDORSE.GATEWAYTIME
     *
     * @mbggenerated
     */
    public void setGatewaytime(Date gatewaytime) {
        this.gatewaytime = gatewaytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENDORSEMENT_ENDORSE.STATUS
     *
     * @return the value of ENDORSEMENT_ENDORSE.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENDORSEMENT_ENDORSE.STATUS
     *
     * @param status the value for ENDORSEMENT_ENDORSE.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENDORSEMENT_ENDORSE.GATEWAYFLOW
     *
     * @return the value of ENDORSEMENT_ENDORSE.GATEWAYFLOW
     *
     * @mbggenerated
     */
    public String getGatewayflow() {
        return gatewayflow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENDORSEMENT_ENDORSE.GATEWAYFLOW
     *
     * @param gatewayflow the value for ENDORSEMENT_ENDORSE.GATEWAYFLOW
     *
     * @mbggenerated
     */
    public void setGatewayflow(String gatewayflow) {
        this.gatewayflow = gatewayflow == null ? null : gatewayflow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENDORSEMENT_ENDORSE.RETURNCODE
     *
     * @return the value of ENDORSEMENT_ENDORSE.RETURNCODE
     *
     * @mbggenerated
     */
    public String getReturncode() {
        return returncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENDORSEMENT_ENDORSE.RETURNCODE
     *
     * @param returncode the value for ENDORSEMENT_ENDORSE.RETURNCODE
     *
     * @mbggenerated
     */
    public void setReturncode(String returncode) {
        this.returncode = returncode == null ? null : returncode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENDORSEMENT_ENDORSE.REASON
     *
     * @return the value of ENDORSEMENT_ENDORSE.REASON
     *
     * @mbggenerated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENDORSEMENT_ENDORSE.REASON
     *
     * @param reason the value for ENDORSEMENT_ENDORSE.REASON
     *
     * @mbggenerated
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENDORSEMENT_ENDORSE.STATE
     *
     * @return the value of ENDORSEMENT_ENDORSE.STATE
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENDORSEMENT_ENDORSE.STATE
     *
     * @param state the value for ENDORSEMENT_ENDORSE.STATE
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }
}