package com.future.dao4ora.po;

import java.util.Date;

public class EndorsementEndorseitemsWithBLOBs extends EndorsementEndorseitems {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENDORSEMENT_ENDORSEITEMS.OLDVALUE
     *
     * @mbggenerated
     */
    private String oldvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENDORSEMENT_ENDORSEITEMS.NEWVALUE
     *
     * @mbggenerated
     */
    private String newvalue;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENDORSEMENT_ENDORSEITEMS
     *
     * @mbggenerated
     */
    public EndorsementEndorseitemsWithBLOBs(String proposalsid, String batchid, String itemid, String itemtype, Date createstamp, Date lastupdatestamp, String oldvalue, String newvalue) {
        super(proposalsid, batchid, itemid, itemtype, createstamp, lastupdatestamp);
        this.oldvalue = oldvalue;
        this.newvalue = newvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENDORSEMENT_ENDORSEITEMS
     *
     * @mbggenerated
     */
    public EndorsementEndorseitemsWithBLOBs() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENDORSEMENT_ENDORSEITEMS.OLDVALUE
     *
     * @return the value of ENDORSEMENT_ENDORSEITEMS.OLDVALUE
     *
     * @mbggenerated
     */
    public String getOldvalue() {
        return oldvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENDORSEMENT_ENDORSEITEMS.OLDVALUE
     *
     * @param oldvalue the value for ENDORSEMENT_ENDORSEITEMS.OLDVALUE
     *
     * @mbggenerated
     */
    public void setOldvalue(String oldvalue) {
        this.oldvalue = oldvalue == null ? null : oldvalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENDORSEMENT_ENDORSEITEMS.NEWVALUE
     *
     * @return the value of ENDORSEMENT_ENDORSEITEMS.NEWVALUE
     *
     * @mbggenerated
     */
    public String getNewvalue() {
        return newvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENDORSEMENT_ENDORSEITEMS.NEWVALUE
     *
     * @param newvalue the value for ENDORSEMENT_ENDORSEITEMS.NEWVALUE
     *
     * @mbggenerated
     */
    public void setNewvalue(String newvalue) {
        this.newvalue = newvalue == null ? null : newvalue.trim();
    }
}