package com.future.dao4ora.po;

import com.future.annotation.MappingConfig;

import java.math.BigDecimal;
import java.util.Date;
@MappingConfig(fileName = "reportmap.properties",mappingKey = "airinfo.sheethead")
public class GeAlipayAirinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.SERIALNO
     *
     * @mbggenerated
     */
    private String serialno;


    public String getProductname() {
        return productname;
    }

    public void setProductname(String productname) {
        this.productname = productname;
    }

    private String productname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.TRANSTIME
     *
     * @mbggenerated
     */
    private Date transtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.REQMSGID
     *
     * @mbggenerated
     */
    private String reqmsgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.POLICYNO
     *
     * @mbggenerated
     */
    private String policyno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.PRODNO
     *
     * @mbggenerated
     */
    private String prodno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.SUMMARYPOLICYNO
     *
     * @mbggenerated
     */
    private String summarypolicyno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.POLICYTYPE
     *
     * @mbggenerated
     */
    private String policytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.PREMIUM
     *
     * @mbggenerated
     */
    private BigDecimal premium;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.ACTUALPREMIUM
     *
     * @mbggenerated
     */
    private BigDecimal actualpremium;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.SUMINSURED
     *
     * @mbggenerated
     */
    private BigDecimal suminsured;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.INSUREDTIME
     *
     * @mbggenerated
     */
    private Date insuredtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.EFFECTSTARTTIME
     *
     * @mbggenerated
     */
    private Date effectstarttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.EFFECTENDTIME
     *
     * @mbggenerated
     */
    private Date effectendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.APPLYNUM
     *
     * @mbggenerated
     */
    private BigDecimal applynum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.AIRNUMBER
     *
     * @mbggenerated
     */
    private String airnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.ISREQUIREINVOICE
     *
     * @mbggenerated
     */
    private String isrequireinvoice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.AIRORDEREND
     *
     * @mbggenerated
     */
    private String airorderend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.AIRTAKEOFF
     *
     * @mbggenerated
     */
    private Date airtakeoff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.AIRORDERID
     *
     * @mbggenerated
     */
    private String airorderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.SHAREDCOMMISSION
     *
     * @mbggenerated
     */
    private String sharedcommission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.TICKETNO
     *
     * @mbggenerated
     */
    private String ticketno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.FLIGHTNO
     *
     * @mbggenerated
     */
    private String flightno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.AIRCOMNAME
     *
     * @mbggenerated
     */
    private String aircomname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.INSUREDCOPIES
     *
     * @mbggenerated
     */
    private BigDecimal insuredcopies;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.AIRORDERSTART
     *
     * @mbggenerated
     */
    private String airorderstart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.BIZORDERID
     *
     * @mbggenerated
     */
    private String bizorderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.AIRLANDING
     *
     * @mbggenerated
     */
    private Date airlanding;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.MERCHANTACCOUNTTYPE
     *
     * @mbggenerated
     */
    private String merchantaccounttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.MERCHANTACCOUNTID
     *
     * @mbggenerated
     */
    private String merchantaccountid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.OTHERACCOUNTTYPE
     *
     * @mbggenerated
     */
    private String otheraccounttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.OTHERACCOUNTID
     *
     * @mbggenerated
     */
    private String otheraccountid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.PAYTIME
     *
     * @mbggenerated
     */
    private Date paytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.FEE
     *
     * @mbggenerated
     */
    private BigDecimal fee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.PAYFLOWID
     *
     * @mbggenerated
     */
    private String payflowid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.HOLDERPERSONNO
     *
     * @mbggenerated
     */
    private String holderpersonno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.HOLDERACCOUNTTYPE
     *
     * @mbggenerated
     */
    private String holderaccounttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.HOLDERACCOUNTNO
     *
     * @mbggenerated
     */
    private String holderaccountno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.HOLDERACCOUNTNAME
     *
     * @mbggenerated
     */
    private String holderaccountname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.HOLDERCERTTYPE
     *
     * @mbggenerated
     */
    private String holdercerttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.HOLDERCERTNO
     *
     * @mbggenerated
     */
    private String holdercertno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.HOLDERCERTNAME
     *
     * @mbggenerated
     */
    private String holdercertname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.HOLDERBIRTHDAY
     *
     * @mbggenerated
     */
    private Date holderbirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.HOLDERPHONE
     *
     * @mbggenerated
     */
    private String holderphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.INSUREDSAMEWITHHOLDER
     *
     * @mbggenerated
     */
    private String insuredsamewithholder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.INSUREDPERSONNO
     *
     * @mbggenerated
     */
    private String insuredpersonno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.INSUREDACCOUNTTYPE
     *
     * @mbggenerated
     */
    private String insuredaccounttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.INSUREDACCOUNTNO
     *
     * @mbggenerated
     */
    private String insuredaccountno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.INSUREDACCOUNTNAME
     *
     * @mbggenerated
     */
    private String insuredaccountname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.INSUREDCERTTYPE
     *
     * @mbggenerated
     */
    private String insuredcerttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.INSUREDCERTNO
     *
     * @mbggenerated
     */
    private String insuredcertno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.INSUREDCERTNAME
     *
     * @mbggenerated
     */
    private String insuredcertname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.INSUREDBIRTHDAY
     *
     * @mbggenerated
     */
    private Date insuredbirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.INSUREDPHONE
     *
     * @mbggenerated
     */
    private String insuredphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.STATUS
     *
     * @mbggenerated
     */
    @MappingConfig(fileName = "reportmap.properties",mappingKey = "airinfo.status")
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.MAKEDATE
     *
     * @mbggenerated
     */
    private Date makedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.MODIFYDATE
     *
     * @mbggenerated
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.PROPOSALNO
     *
     * @mbggenerated
     */
    private String proposalno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.PROVINCE
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.CITY
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.AREA
     *
     * @mbggenerated
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.DETAILADDRESS
     *
     * @mbggenerated
     */
    private String detailaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.MOBILE
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.ZIP
     *
     * @mbggenerated
     */
    private String zip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.NUM
     *
     * @mbggenerated
     */
    private Short num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.REASON
     *
     * @mbggenerated
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ALIPAY_AIRINFO.SAVEERRORCOUNT
     *
     * @mbggenerated
     */
    private Short saveerrorcount;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GE_ALIPAY_AIRINFO
     *
     * @mbggenerated
     */
    public GeAlipayAirinfo(String serialno,String productname, Date transtime, String reqmsgid, String policyno, String prodno, String summarypolicyno, String policytype, BigDecimal premium, BigDecimal actualpremium, BigDecimal suminsured, Date insuredtime, Date effectstarttime, Date effectendtime, BigDecimal applynum, String airnumber, String isrequireinvoice, String airorderend, Date airtakeoff, String airorderid, String sharedcommission, String ticketno, String flightno, String aircomname, BigDecimal insuredcopies, String airorderstart, String bizorderid, Date airlanding, String merchantaccounttype, String merchantaccountid, String otheraccounttype, String otheraccountid, Date paytime, BigDecimal fee, String payflowid, String holderpersonno, String holderaccounttype, String holderaccountno, String holderaccountname, String holdercerttype, String holdercertno, String holdercertname, Date holderbirthday, String holderphone, String insuredsamewithholder, String insuredpersonno, String insuredaccounttype, String insuredaccountno, String insuredaccountname, String insuredcerttype, String insuredcertno, String insuredcertname, Date insuredbirthday, String insuredphone, String status, Date makedate, Date modifydate, String proposalno, String province, String city, String area, String detailaddress, String mobile, String zip, Short num, String reason, Short saveerrorcount) {
        this.serialno = serialno;
        this.productname = productname;
        this.transtime = transtime;
        this.reqmsgid = reqmsgid;
        this.policyno = policyno;
        this.prodno = prodno;
        this.summarypolicyno = summarypolicyno;
        this.policytype = policytype;
        this.premium = premium;
        this.actualpremium = actualpremium;
        this.suminsured = suminsured;
        this.insuredtime = insuredtime;
        this.effectstarttime = effectstarttime;
        this.effectendtime = effectendtime;
        this.applynum = applynum;
        this.airnumber = airnumber;
        this.isrequireinvoice = isrequireinvoice;
        this.airorderend = airorderend;
        this.airtakeoff = airtakeoff;
        this.airorderid = airorderid;
        this.sharedcommission = sharedcommission;
        this.ticketno = ticketno;
        this.flightno = flightno;
        this.aircomname = aircomname;
        this.insuredcopies = insuredcopies;
        this.airorderstart = airorderstart;
        this.bizorderid = bizorderid;
        this.airlanding = airlanding;
        this.merchantaccounttype = merchantaccounttype;
        this.merchantaccountid = merchantaccountid;
        this.otheraccounttype = otheraccounttype;
        this.otheraccountid = otheraccountid;
        this.paytime = paytime;
        this.fee = fee;
        this.payflowid = payflowid;
        this.holderpersonno = holderpersonno;
        this.holderaccounttype = holderaccounttype;
        this.holderaccountno = holderaccountno;
        this.holderaccountname = holderaccountname;
        this.holdercerttype = holdercerttype;
        this.holdercertno = holdercertno;
        this.holdercertname = holdercertname;
        this.holderbirthday = holderbirthday;
        this.holderphone = holderphone;
        this.insuredsamewithholder = insuredsamewithholder;
        this.insuredpersonno = insuredpersonno;
        this.insuredaccounttype = insuredaccounttype;
        this.insuredaccountno = insuredaccountno;
        this.insuredaccountname = insuredaccountname;
        this.insuredcerttype = insuredcerttype;
        this.insuredcertno = insuredcertno;
        this.insuredcertname = insuredcertname;
        this.insuredbirthday = insuredbirthday;
        this.insuredphone = insuredphone;
        this.status = status;
        this.makedate = makedate;
        this.modifydate = modifydate;
        this.proposalno = proposalno;
        this.province = province;
        this.city = city;
        this.area = area;
        this.detailaddress = detailaddress;
        this.mobile = mobile;
        this.zip = zip;
        this.num = num;
        this.reason = reason;
        this.saveerrorcount = saveerrorcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GE_ALIPAY_AIRINFO
     *
     * @mbggenerated
     */
    public GeAlipayAirinfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.SERIALNO
     *
     * @return the value of GE_ALIPAY_AIRINFO.SERIALNO
     *
     * @mbggenerated
     */
    public String getSerialno() {
        return serialno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.SERIALNO
     *
     * @param serialno the value for GE_ALIPAY_AIRINFO.SERIALNO
     *
     * @mbggenerated
     */
    public void setSerialno(String serialno) {
        this.serialno = serialno == null ? null : serialno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.TRANSTIME
     *
     * @return the value of GE_ALIPAY_AIRINFO.TRANSTIME
     *
     * @mbggenerated
     */
    public Date getTranstime() {
        return transtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.TRANSTIME
     *
     * @param transtime the value for GE_ALIPAY_AIRINFO.TRANSTIME
     *
     * @mbggenerated
     */
    public void setTranstime(Date transtime) {
        this.transtime = transtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.REQMSGID
     *
     * @return the value of GE_ALIPAY_AIRINFO.REQMSGID
     *
     * @mbggenerated
     */
    public String getReqmsgid() {
        return reqmsgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.REQMSGID
     *
     * @param reqmsgid the value for GE_ALIPAY_AIRINFO.REQMSGID
     *
     * @mbggenerated
     */
    public void setReqmsgid(String reqmsgid) {
        this.reqmsgid = reqmsgid == null ? null : reqmsgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.POLICYNO
     *
     * @return the value of GE_ALIPAY_AIRINFO.POLICYNO
     *
     * @mbggenerated
     */
    public String getPolicyno() {
        return policyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.POLICYNO
     *
     * @param policyno the value for GE_ALIPAY_AIRINFO.POLICYNO
     *
     * @mbggenerated
     */
    public void setPolicyno(String policyno) {
        this.policyno = policyno == null ? null : policyno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.PRODNO
     *
     * @return the value of GE_ALIPAY_AIRINFO.PRODNO
     *
     * @mbggenerated
     */
    public String getProdno() {
        return prodno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.PRODNO
     *
     * @param prodno the value for GE_ALIPAY_AIRINFO.PRODNO
     *
     * @mbggenerated
     */
    public void setProdno(String prodno) {
        this.prodno = prodno == null ? null : prodno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.SUMMARYPOLICYNO
     *
     * @return the value of GE_ALIPAY_AIRINFO.SUMMARYPOLICYNO
     *
     * @mbggenerated
     */
    public String getSummarypolicyno() {
        return summarypolicyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.SUMMARYPOLICYNO
     *
     * @param summarypolicyno the value for GE_ALIPAY_AIRINFO.SUMMARYPOLICYNO
     *
     * @mbggenerated
     */
    public void setSummarypolicyno(String summarypolicyno) {
        this.summarypolicyno = summarypolicyno == null ? null : summarypolicyno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.POLICYTYPE
     *
     * @return the value of GE_ALIPAY_AIRINFO.POLICYTYPE
     *
     * @mbggenerated
     */
    public String getPolicytype() {
        return policytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.POLICYTYPE
     *
     * @param policytype the value for GE_ALIPAY_AIRINFO.POLICYTYPE
     *
     * @mbggenerated
     */
    public void setPolicytype(String policytype) {
        this.policytype = policytype == null ? null : policytype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.PREMIUM
     *
     * @return the value of GE_ALIPAY_AIRINFO.PREMIUM
     *
     * @mbggenerated
     */
    public BigDecimal getPremium() {
        return premium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.PREMIUM
     *
     * @param premium the value for GE_ALIPAY_AIRINFO.PREMIUM
     *
     * @mbggenerated
     */
    public void setPremium(BigDecimal premium) {
        this.premium = premium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.ACTUALPREMIUM
     *
     * @return the value of GE_ALIPAY_AIRINFO.ACTUALPREMIUM
     *
     * @mbggenerated
     */
    public BigDecimal getActualpremium() {
        return actualpremium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.ACTUALPREMIUM
     *
     * @param actualpremium the value for GE_ALIPAY_AIRINFO.ACTUALPREMIUM
     *
     * @mbggenerated
     */
    public void setActualpremium(BigDecimal actualpremium) {
        this.actualpremium = actualpremium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.SUMINSURED
     *
     * @return the value of GE_ALIPAY_AIRINFO.SUMINSURED
     *
     * @mbggenerated
     */
    public BigDecimal getSuminsured() {
        return suminsured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.SUMINSURED
     *
     * @param suminsured the value for GE_ALIPAY_AIRINFO.SUMINSURED
     *
     * @mbggenerated
     */
    public void setSuminsured(BigDecimal suminsured) {
        this.suminsured = suminsured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.INSUREDTIME
     *
     * @return the value of GE_ALIPAY_AIRINFO.INSUREDTIME
     *
     * @mbggenerated
     */
    public Date getInsuredtime() {
        return insuredtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.INSUREDTIME
     *
     * @param insuredtime the value for GE_ALIPAY_AIRINFO.INSUREDTIME
     *
     * @mbggenerated
     */
    public void setInsuredtime(Date insuredtime) {
        this.insuredtime = insuredtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.EFFECTSTARTTIME
     *
     * @return the value of GE_ALIPAY_AIRINFO.EFFECTSTARTTIME
     *
     * @mbggenerated
     */
    public Date getEffectstarttime() {
        return effectstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.EFFECTSTARTTIME
     *
     * @param effectstarttime the value for GE_ALIPAY_AIRINFO.EFFECTSTARTTIME
     *
     * @mbggenerated
     */
    public void setEffectstarttime(Date effectstarttime) {
        this.effectstarttime = effectstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.EFFECTENDTIME
     *
     * @return the value of GE_ALIPAY_AIRINFO.EFFECTENDTIME
     *
     * @mbggenerated
     */
    public Date getEffectendtime() {
        return effectendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.EFFECTENDTIME
     *
     * @param effectendtime the value for GE_ALIPAY_AIRINFO.EFFECTENDTIME
     *
     * @mbggenerated
     */
    public void setEffectendtime(Date effectendtime) {
        this.effectendtime = effectendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.APPLYNUM
     *
     * @return the value of GE_ALIPAY_AIRINFO.APPLYNUM
     *
     * @mbggenerated
     */
    public BigDecimal getApplynum() {
        return applynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.APPLYNUM
     *
     * @param applynum the value for GE_ALIPAY_AIRINFO.APPLYNUM
     *
     * @mbggenerated
     */
    public void setApplynum(BigDecimal applynum) {
        this.applynum = applynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.AIRNUMBER
     *
     * @return the value of GE_ALIPAY_AIRINFO.AIRNUMBER
     *
     * @mbggenerated
     */
    public String getAirnumber() {
        return airnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.AIRNUMBER
     *
     * @param airnumber the value for GE_ALIPAY_AIRINFO.AIRNUMBER
     *
     * @mbggenerated
     */
    public void setAirnumber(String airnumber) {
        this.airnumber = airnumber == null ? null : airnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.ISREQUIREINVOICE
     *
     * @return the value of GE_ALIPAY_AIRINFO.ISREQUIREINVOICE
     *
     * @mbggenerated
     */
    public String getIsrequireinvoice() {
        return isrequireinvoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.ISREQUIREINVOICE
     *
     * @param isrequireinvoice the value for GE_ALIPAY_AIRINFO.ISREQUIREINVOICE
     *
     * @mbggenerated
     */
    public void setIsrequireinvoice(String isrequireinvoice) {
        this.isrequireinvoice = isrequireinvoice == null ? null : isrequireinvoice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.AIRORDEREND
     *
     * @return the value of GE_ALIPAY_AIRINFO.AIRORDEREND
     *
     * @mbggenerated
     */
    public String getAirorderend() {
        return airorderend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.AIRORDEREND
     *
     * @param airorderend the value for GE_ALIPAY_AIRINFO.AIRORDEREND
     *
     * @mbggenerated
     */
    public void setAirorderend(String airorderend) {
        this.airorderend = airorderend == null ? null : airorderend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.AIRTAKEOFF
     *
     * @return the value of GE_ALIPAY_AIRINFO.AIRTAKEOFF
     *
     * @mbggenerated
     */
    public Date getAirtakeoff() {
        return airtakeoff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.AIRTAKEOFF
     *
     * @param airtakeoff the value for GE_ALIPAY_AIRINFO.AIRTAKEOFF
     *
     * @mbggenerated
     */
    public void setAirtakeoff(Date airtakeoff) {
        this.airtakeoff = airtakeoff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.AIRORDERID
     *
     * @return the value of GE_ALIPAY_AIRINFO.AIRORDERID
     *
     * @mbggenerated
     */
    public String getAirorderid() {
        return airorderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.AIRORDERID
     *
     * @param airorderid the value for GE_ALIPAY_AIRINFO.AIRORDERID
     *
     * @mbggenerated
     */
    public void setAirorderid(String airorderid) {
        this.airorderid = airorderid == null ? null : airorderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.SHAREDCOMMISSION
     *
     * @return the value of GE_ALIPAY_AIRINFO.SHAREDCOMMISSION
     *
     * @mbggenerated
     */
    public String getSharedcommission() {
        return sharedcommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.SHAREDCOMMISSION
     *
     * @param sharedcommission the value for GE_ALIPAY_AIRINFO.SHAREDCOMMISSION
     *
     * @mbggenerated
     */
    public void setSharedcommission(String sharedcommission) {
        this.sharedcommission = sharedcommission == null ? null : sharedcommission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.TICKETNO
     *
     * @return the value of GE_ALIPAY_AIRINFO.TICKETNO
     *
     * @mbggenerated
     */
    public String getTicketno() {
        return ticketno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.TICKETNO
     *
     * @param ticketno the value for GE_ALIPAY_AIRINFO.TICKETNO
     *
     * @mbggenerated
     */
    public void setTicketno(String ticketno) {
        this.ticketno = ticketno == null ? null : ticketno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.FLIGHTNO
     *
     * @return the value of GE_ALIPAY_AIRINFO.FLIGHTNO
     *
     * @mbggenerated
     */
    public String getFlightno() {
        return flightno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.FLIGHTNO
     *
     * @param flightno the value for GE_ALIPAY_AIRINFO.FLIGHTNO
     *
     * @mbggenerated
     */
    public void setFlightno(String flightno) {
        this.flightno = flightno == null ? null : flightno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.AIRCOMNAME
     *
     * @return the value of GE_ALIPAY_AIRINFO.AIRCOMNAME
     *
     * @mbggenerated
     */
    public String getAircomname() {
        return aircomname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.AIRCOMNAME
     *
     * @param aircomname the value for GE_ALIPAY_AIRINFO.AIRCOMNAME
     *
     * @mbggenerated
     */
    public void setAircomname(String aircomname) {
        this.aircomname = aircomname == null ? null : aircomname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.INSUREDCOPIES
     *
     * @return the value of GE_ALIPAY_AIRINFO.INSUREDCOPIES
     *
     * @mbggenerated
     */
    public BigDecimal getInsuredcopies() {
        return insuredcopies;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.INSUREDCOPIES
     *
     * @param insuredcopies the value for GE_ALIPAY_AIRINFO.INSUREDCOPIES
     *
     * @mbggenerated
     */
    public void setInsuredcopies(BigDecimal insuredcopies) {
        this.insuredcopies = insuredcopies;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.AIRORDERSTART
     *
     * @return the value of GE_ALIPAY_AIRINFO.AIRORDERSTART
     *
     * @mbggenerated
     */
    public String getAirorderstart() {
        return airorderstart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.AIRORDERSTART
     *
     * @param airorderstart the value for GE_ALIPAY_AIRINFO.AIRORDERSTART
     *
     * @mbggenerated
     */
    public void setAirorderstart(String airorderstart) {
        this.airorderstart = airorderstart == null ? null : airorderstart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.BIZORDERID
     *
     * @return the value of GE_ALIPAY_AIRINFO.BIZORDERID
     *
     * @mbggenerated
     */
    public String getBizorderid() {
        return bizorderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.BIZORDERID
     *
     * @param bizorderid the value for GE_ALIPAY_AIRINFO.BIZORDERID
     *
     * @mbggenerated
     */
    public void setBizorderid(String bizorderid) {
        this.bizorderid = bizorderid == null ? null : bizorderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.AIRLANDING
     *
     * @return the value of GE_ALIPAY_AIRINFO.AIRLANDING
     *
     * @mbggenerated
     */
    public Date getAirlanding() {
        return airlanding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.AIRLANDING
     *
     * @param airlanding the value for GE_ALIPAY_AIRINFO.AIRLANDING
     *
     * @mbggenerated
     */
    public void setAirlanding(Date airlanding) {
        this.airlanding = airlanding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.MERCHANTACCOUNTTYPE
     *
     * @return the value of GE_ALIPAY_AIRINFO.MERCHANTACCOUNTTYPE
     *
     * @mbggenerated
     */
    public String getMerchantaccounttype() {
        return merchantaccounttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.MERCHANTACCOUNTTYPE
     *
     * @param merchantaccounttype the value for GE_ALIPAY_AIRINFO.MERCHANTACCOUNTTYPE
     *
     * @mbggenerated
     */
    public void setMerchantaccounttype(String merchantaccounttype) {
        this.merchantaccounttype = merchantaccounttype == null ? null : merchantaccounttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.MERCHANTACCOUNTID
     *
     * @return the value of GE_ALIPAY_AIRINFO.MERCHANTACCOUNTID
     *
     * @mbggenerated
     */
    public String getMerchantaccountid() {
        return merchantaccountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.MERCHANTACCOUNTID
     *
     * @param merchantaccountid the value for GE_ALIPAY_AIRINFO.MERCHANTACCOUNTID
     *
     * @mbggenerated
     */
    public void setMerchantaccountid(String merchantaccountid) {
        this.merchantaccountid = merchantaccountid == null ? null : merchantaccountid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.OTHERACCOUNTTYPE
     *
     * @return the value of GE_ALIPAY_AIRINFO.OTHERACCOUNTTYPE
     *
     * @mbggenerated
     */
    public String getOtheraccounttype() {
        return otheraccounttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.OTHERACCOUNTTYPE
     *
     * @param otheraccounttype the value for GE_ALIPAY_AIRINFO.OTHERACCOUNTTYPE
     *
     * @mbggenerated
     */
    public void setOtheraccounttype(String otheraccounttype) {
        this.otheraccounttype = otheraccounttype == null ? null : otheraccounttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.OTHERACCOUNTID
     *
     * @return the value of GE_ALIPAY_AIRINFO.OTHERACCOUNTID
     *
     * @mbggenerated
     */
    public String getOtheraccountid() {
        return otheraccountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.OTHERACCOUNTID
     *
     * @param otheraccountid the value for GE_ALIPAY_AIRINFO.OTHERACCOUNTID
     *
     * @mbggenerated
     */
    public void setOtheraccountid(String otheraccountid) {
        this.otheraccountid = otheraccountid == null ? null : otheraccountid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.PAYTIME
     *
     * @return the value of GE_ALIPAY_AIRINFO.PAYTIME
     *
     * @mbggenerated
     */
    public Date getPaytime() {
        return paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.PAYTIME
     *
     * @param paytime the value for GE_ALIPAY_AIRINFO.PAYTIME
     *
     * @mbggenerated
     */
    public void setPaytime(Date paytime) {
        this.paytime = paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.FEE
     *
     * @return the value of GE_ALIPAY_AIRINFO.FEE
     *
     * @mbggenerated
     */
    public BigDecimal getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.FEE
     *
     * @param fee the value for GE_ALIPAY_AIRINFO.FEE
     *
     * @mbggenerated
     */
    public void setFee(BigDecimal fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.PAYFLOWID
     *
     * @return the value of GE_ALIPAY_AIRINFO.PAYFLOWID
     *
     * @mbggenerated
     */
    public String getPayflowid() {
        return payflowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.PAYFLOWID
     *
     * @param payflowid the value for GE_ALIPAY_AIRINFO.PAYFLOWID
     *
     * @mbggenerated
     */
    public void setPayflowid(String payflowid) {
        this.payflowid = payflowid == null ? null : payflowid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.HOLDERPERSONNO
     *
     * @return the value of GE_ALIPAY_AIRINFO.HOLDERPERSONNO
     *
     * @mbggenerated
     */
    public String getHolderpersonno() {
        return holderpersonno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.HOLDERPERSONNO
     *
     * @param holderpersonno the value for GE_ALIPAY_AIRINFO.HOLDERPERSONNO
     *
     * @mbggenerated
     */
    public void setHolderpersonno(String holderpersonno) {
        this.holderpersonno = holderpersonno == null ? null : holderpersonno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.HOLDERACCOUNTTYPE
     *
     * @return the value of GE_ALIPAY_AIRINFO.HOLDERACCOUNTTYPE
     *
     * @mbggenerated
     */
    public String getHolderaccounttype() {
        return holderaccounttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.HOLDERACCOUNTTYPE
     *
     * @param holderaccounttype the value for GE_ALIPAY_AIRINFO.HOLDERACCOUNTTYPE
     *
     * @mbggenerated
     */
    public void setHolderaccounttype(String holderaccounttype) {
        this.holderaccounttype = holderaccounttype == null ? null : holderaccounttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.HOLDERACCOUNTNO
     *
     * @return the value of GE_ALIPAY_AIRINFO.HOLDERACCOUNTNO
     *
     * @mbggenerated
     */
    public String getHolderaccountno() {
        return holderaccountno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.HOLDERACCOUNTNO
     *
     * @param holderaccountno the value for GE_ALIPAY_AIRINFO.HOLDERACCOUNTNO
     *
     * @mbggenerated
     */
    public void setHolderaccountno(String holderaccountno) {
        this.holderaccountno = holderaccountno == null ? null : holderaccountno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.HOLDERACCOUNTNAME
     *
     * @return the value of GE_ALIPAY_AIRINFO.HOLDERACCOUNTNAME
     *
     * @mbggenerated
     */
    public String getHolderaccountname() {
        return holderaccountname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.HOLDERACCOUNTNAME
     *
     * @param holderaccountname the value for GE_ALIPAY_AIRINFO.HOLDERACCOUNTNAME
     *
     * @mbggenerated
     */
    public void setHolderaccountname(String holderaccountname) {
        this.holderaccountname = holderaccountname == null ? null : holderaccountname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.HOLDERCERTTYPE
     *
     * @return the value of GE_ALIPAY_AIRINFO.HOLDERCERTTYPE
     *
     * @mbggenerated
     */
    public String getHoldercerttype() {
        return holdercerttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.HOLDERCERTTYPE
     *
     * @param holdercerttype the value for GE_ALIPAY_AIRINFO.HOLDERCERTTYPE
     *
     * @mbggenerated
     */
    public void setHoldercerttype(String holdercerttype) {
        this.holdercerttype = holdercerttype == null ? null : holdercerttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.HOLDERCERTNO
     *
     * @return the value of GE_ALIPAY_AIRINFO.HOLDERCERTNO
     *
     * @mbggenerated
     */
    public String getHoldercertno() {
        return holdercertno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.HOLDERCERTNO
     *
     * @param holdercertno the value for GE_ALIPAY_AIRINFO.HOLDERCERTNO
     *
     * @mbggenerated
     */
    public void setHoldercertno(String holdercertno) {
        this.holdercertno = holdercertno == null ? null : holdercertno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.HOLDERCERTNAME
     *
     * @return the value of GE_ALIPAY_AIRINFO.HOLDERCERTNAME
     *
     * @mbggenerated
     */
    public String getHoldercertname() {
        return holdercertname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.HOLDERCERTNAME
     *
     * @param holdercertname the value for GE_ALIPAY_AIRINFO.HOLDERCERTNAME
     *
     * @mbggenerated
     */
    public void setHoldercertname(String holdercertname) {
        this.holdercertname = holdercertname == null ? null : holdercertname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.HOLDERBIRTHDAY
     *
     * @return the value of GE_ALIPAY_AIRINFO.HOLDERBIRTHDAY
     *
     * @mbggenerated
     */
    public Date getHolderbirthday() {
        return holderbirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.HOLDERBIRTHDAY
     *
     * @param holderbirthday the value for GE_ALIPAY_AIRINFO.HOLDERBIRTHDAY
     *
     * @mbggenerated
     */
    public void setHolderbirthday(Date holderbirthday) {
        this.holderbirthday = holderbirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.HOLDERPHONE
     *
     * @return the value of GE_ALIPAY_AIRINFO.HOLDERPHONE
     *
     * @mbggenerated
     */
    public String getHolderphone() {
        return holderphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.HOLDERPHONE
     *
     * @param holderphone the value for GE_ALIPAY_AIRINFO.HOLDERPHONE
     *
     * @mbggenerated
     */
    public void setHolderphone(String holderphone) {
        this.holderphone = holderphone == null ? null : holderphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.INSUREDSAMEWITHHOLDER
     *
     * @return the value of GE_ALIPAY_AIRINFO.INSUREDSAMEWITHHOLDER
     *
     * @mbggenerated
     */
    public String getInsuredsamewithholder() {
        return insuredsamewithholder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.INSUREDSAMEWITHHOLDER
     *
     * @param insuredsamewithholder the value for GE_ALIPAY_AIRINFO.INSUREDSAMEWITHHOLDER
     *
     * @mbggenerated
     */
    public void setInsuredsamewithholder(String insuredsamewithholder) {
        this.insuredsamewithholder = insuredsamewithholder == null ? null : insuredsamewithholder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.INSUREDPERSONNO
     *
     * @return the value of GE_ALIPAY_AIRINFO.INSUREDPERSONNO
     *
     * @mbggenerated
     */
    public String getInsuredpersonno() {
        return insuredpersonno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.INSUREDPERSONNO
     *
     * @param insuredpersonno the value for GE_ALIPAY_AIRINFO.INSUREDPERSONNO
     *
     * @mbggenerated
     */
    public void setInsuredpersonno(String insuredpersonno) {
        this.insuredpersonno = insuredpersonno == null ? null : insuredpersonno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.INSUREDACCOUNTTYPE
     *
     * @return the value of GE_ALIPAY_AIRINFO.INSUREDACCOUNTTYPE
     *
     * @mbggenerated
     */
    public String getInsuredaccounttype() {
        return insuredaccounttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.INSUREDACCOUNTTYPE
     *
     * @param insuredaccounttype the value for GE_ALIPAY_AIRINFO.INSUREDACCOUNTTYPE
     *
     * @mbggenerated
     */
    public void setInsuredaccounttype(String insuredaccounttype) {
        this.insuredaccounttype = insuredaccounttype == null ? null : insuredaccounttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.INSUREDACCOUNTNO
     *
     * @return the value of GE_ALIPAY_AIRINFO.INSUREDACCOUNTNO
     *
     * @mbggenerated
     */
    public String getInsuredaccountno() {
        return insuredaccountno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.INSUREDACCOUNTNO
     *
     * @param insuredaccountno the value for GE_ALIPAY_AIRINFO.INSUREDACCOUNTNO
     *
     * @mbggenerated
     */
    public void setInsuredaccountno(String insuredaccountno) {
        this.insuredaccountno = insuredaccountno == null ? null : insuredaccountno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.INSUREDACCOUNTNAME
     *
     * @return the value of GE_ALIPAY_AIRINFO.INSUREDACCOUNTNAME
     *
     * @mbggenerated
     */
    public String getInsuredaccountname() {
        return insuredaccountname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.INSUREDACCOUNTNAME
     *
     * @param insuredaccountname the value for GE_ALIPAY_AIRINFO.INSUREDACCOUNTNAME
     *
     * @mbggenerated
     */
    public void setInsuredaccountname(String insuredaccountname) {
        this.insuredaccountname = insuredaccountname == null ? null : insuredaccountname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.INSUREDCERTTYPE
     *
     * @return the value of GE_ALIPAY_AIRINFO.INSUREDCERTTYPE
     *
     * @mbggenerated
     */
    public String getInsuredcerttype() {
        return insuredcerttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.INSUREDCERTTYPE
     *
     * @param insuredcerttype the value for GE_ALIPAY_AIRINFO.INSUREDCERTTYPE
     *
     * @mbggenerated
     */
    public void setInsuredcerttype(String insuredcerttype) {
        this.insuredcerttype = insuredcerttype == null ? null : insuredcerttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.INSUREDCERTNO
     *
     * @return the value of GE_ALIPAY_AIRINFO.INSUREDCERTNO
     *
     * @mbggenerated
     */
    public String getInsuredcertno() {
        return insuredcertno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.INSUREDCERTNO
     *
     * @param insuredcertno the value for GE_ALIPAY_AIRINFO.INSUREDCERTNO
     *
     * @mbggenerated
     */
    public void setInsuredcertno(String insuredcertno) {
        this.insuredcertno = insuredcertno == null ? null : insuredcertno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.INSUREDCERTNAME
     *
     * @return the value of GE_ALIPAY_AIRINFO.INSUREDCERTNAME
     *
     * @mbggenerated
     */
    public String getInsuredcertname() {
        return insuredcertname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.INSUREDCERTNAME
     *
     * @param insuredcertname the value for GE_ALIPAY_AIRINFO.INSUREDCERTNAME
     *
     * @mbggenerated
     */
    public void setInsuredcertname(String insuredcertname) {
        this.insuredcertname = insuredcertname == null ? null : insuredcertname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.INSUREDBIRTHDAY
     *
     * @return the value of GE_ALIPAY_AIRINFO.INSUREDBIRTHDAY
     *
     * @mbggenerated
     */
    public Date getInsuredbirthday() {
        return insuredbirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.INSUREDBIRTHDAY
     *
     * @param insuredbirthday the value for GE_ALIPAY_AIRINFO.INSUREDBIRTHDAY
     *
     * @mbggenerated
     */
    public void setInsuredbirthday(Date insuredbirthday) {
        this.insuredbirthday = insuredbirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.INSUREDPHONE
     *
     * @return the value of GE_ALIPAY_AIRINFO.INSUREDPHONE
     *
     * @mbggenerated
     */
    public String getInsuredphone() {
        return insuredphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.INSUREDPHONE
     *
     * @param insuredphone the value for GE_ALIPAY_AIRINFO.INSUREDPHONE
     *
     * @mbggenerated
     */
    public void setInsuredphone(String insuredphone) {
        this.insuredphone = insuredphone == null ? null : insuredphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.STATUS
     *
     * @return the value of GE_ALIPAY_AIRINFO.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.STATUS
     *
     * @param status the value for GE_ALIPAY_AIRINFO.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.MAKEDATE
     *
     * @return the value of GE_ALIPAY_AIRINFO.MAKEDATE
     *
     * @mbggenerated
     */
    public Date getMakedate() {
        return makedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.MAKEDATE
     *
     * @param makedate the value for GE_ALIPAY_AIRINFO.MAKEDATE
     *
     * @mbggenerated
     */
    public void setMakedate(Date makedate) {
        this.makedate = makedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.MODIFYDATE
     *
     * @return the value of GE_ALIPAY_AIRINFO.MODIFYDATE
     *
     * @mbggenerated
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.MODIFYDATE
     *
     * @param modifydate the value for GE_ALIPAY_AIRINFO.MODIFYDATE
     *
     * @mbggenerated
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.PROPOSALNO
     *
     * @return the value of GE_ALIPAY_AIRINFO.PROPOSALNO
     *
     * @mbggenerated
     */
    public String getProposalno() {
        return proposalno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.PROPOSALNO
     *
     * @param proposalno the value for GE_ALIPAY_AIRINFO.PROPOSALNO
     *
     * @mbggenerated
     */
    public void setProposalno(String proposalno) {
        this.proposalno = proposalno == null ? null : proposalno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.PROVINCE
     *
     * @return the value of GE_ALIPAY_AIRINFO.PROVINCE
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.PROVINCE
     *
     * @param province the value for GE_ALIPAY_AIRINFO.PROVINCE
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.CITY
     *
     * @return the value of GE_ALIPAY_AIRINFO.CITY
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.CITY
     *
     * @param city the value for GE_ALIPAY_AIRINFO.CITY
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.AREA
     *
     * @return the value of GE_ALIPAY_AIRINFO.AREA
     *
     * @mbggenerated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.AREA
     *
     * @param area the value for GE_ALIPAY_AIRINFO.AREA
     *
     * @mbggenerated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.DETAILADDRESS
     *
     * @return the value of GE_ALIPAY_AIRINFO.DETAILADDRESS
     *
     * @mbggenerated
     */
    public String getDetailaddress() {
        return detailaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.DETAILADDRESS
     *
     * @param detailaddress the value for GE_ALIPAY_AIRINFO.DETAILADDRESS
     *
     * @mbggenerated
     */
    public void setDetailaddress(String detailaddress) {
        this.detailaddress = detailaddress == null ? null : detailaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.MOBILE
     *
     * @return the value of GE_ALIPAY_AIRINFO.MOBILE
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.MOBILE
     *
     * @param mobile the value for GE_ALIPAY_AIRINFO.MOBILE
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.ZIP
     *
     * @return the value of GE_ALIPAY_AIRINFO.ZIP
     *
     * @mbggenerated
     */
    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.ZIP
     *
     * @param zip the value for GE_ALIPAY_AIRINFO.ZIP
     *
     * @mbggenerated
     */
    public void setZip(String zip) {
        this.zip = zip == null ? null : zip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.NUM
     *
     * @return the value of GE_ALIPAY_AIRINFO.NUM
     *
     * @mbggenerated
     */
    public Short getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.NUM
     *
     * @param num the value for GE_ALIPAY_AIRINFO.NUM
     *
     * @mbggenerated
     */
    public void setNum(Short num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.REASON
     *
     * @return the value of GE_ALIPAY_AIRINFO.REASON
     *
     * @mbggenerated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.REASON
     *
     * @param reason the value for GE_ALIPAY_AIRINFO.REASON
     *
     * @mbggenerated
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ALIPAY_AIRINFO.SAVEERRORCOUNT
     *
     * @return the value of GE_ALIPAY_AIRINFO.SAVEERRORCOUNT
     *
     * @mbggenerated
     */
    public Short getSaveerrorcount() {
        return saveerrorcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ALIPAY_AIRINFO.SAVEERRORCOUNT
     *
     * @param saveerrorcount the value for GE_ALIPAY_AIRINFO.SAVEERRORCOUNT
     *
     * @mbggenerated
     */
    public void setSaveerrorcount(Short saveerrorcount) {
        this.saveerrorcount = saveerrorcount;
    }
}