package com.future.dao4ora.po;

import java.math.BigDecimal;
import java.util.Date;

public class GeOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.ORDERNO
     *
     * @mbggenerated
     */
    private String orderno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.CIRCPAYMENTNO
     *
     * @mbggenerated
     */
    private String circpaymentno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.USERID
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.CURRENCY
     *
     * @mbggenerated
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.ORDERAMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal orderamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.PAYTIME
     *
     * @mbggenerated
     */
    private Date paytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.PAYSTATUS
     *
     * @mbggenerated
     */
    private String paystatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.PAYWAY
     *
     * @mbggenerated
     */
    private String payway;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.INVOICEFLAG
     *
     * @mbggenerated
     */
    private String invoiceflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.INVOICETITLE
     *
     * @mbggenerated
     */
    private String invoicetitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.SUBMITTIME
     *
     * @mbggenerated
     */
    private Date submittime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.GATEWAYRNO
     *
     * @mbggenerated
     */
    private String gatewayrno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.BANKORDERNO
     *
     * @mbggenerated
     */
    private String bankorderno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.SURCHARGE
     *
     * @mbggenerated
     */
    private BigDecimal surcharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.FLOWNO
     *
     * @mbggenerated
     */
    private String flowno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.REFUNDMENTFLAG
     *
     * @mbggenerated
     */
    private String refundmentflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.CREATEDATE
     *
     * @mbggenerated
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.RECIPIENTNAME
     *
     * @mbggenerated
     */
    private String recipientname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.RECIPIENTMOBILE
     *
     * @mbggenerated
     */
    private String recipientmobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.ZIPCODE
     *
     * @mbggenerated
     */
    private String zipcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.RECIPIENTADDRESS
     *
     * @mbggenerated
     */
    private String recipientaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.SENDDATE
     *
     * @mbggenerated
     */
    private Date senddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.FLAG
     *
     * @mbggenerated
     */
    private String flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.DISTRIBUTIONSTATUS
     *
     * @mbggenerated
     */
    private String distributionstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.USERTYPE
     *
     * @mbggenerated
     */
    private String usertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.DATASOURSE
     *
     * @mbggenerated
     */
    private String datasourse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.ENCODEMSG
     *
     * @mbggenerated
     */
    private String encodemsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.SIGNMSG
     *
     * @mbggenerated
     */
    private String signmsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.SYSTEMSSN
     *
     * @mbggenerated
     */
    private String systemssn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.AGENTIDENTITYCODE
     *
     * @mbggenerated
     */
    private String agentidentitycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.PAYMENTPLATFORM
     *
     * @mbggenerated
     */
    private String paymentplatform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.PAYMENTSOURCE
     *
     * @mbggenerated
     */
    private String paymentsource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.TBORDERID
     *
     * @mbggenerated
     */
    private String tborderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.PAYORDERID
     *
     * @mbggenerated
     */
    private String payorderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.CHECKPAYNO
     *
     * @mbggenerated
     */
    private String checkpayno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.ACCOUNTDATE
     *
     * @mbggenerated
     */
    private Date accountdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.ALIPAYBUYERACCOUNT
     *
     * @mbggenerated
     */
    private String alipaybuyeraccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.ALIPAYBUYERID
     *
     * @mbggenerated
     */
    private String alipaybuyerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.ESBRESPONSETIME
     *
     * @mbggenerated
     */
    private Date esbresponsetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.COMMUNICATIONMODE
     *
     * @mbggenerated
     */
    private String communicationmode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.APPTIME
     *
     * @mbggenerated
     */
    private Date apptime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.EXTRAFEE
     *
     * @mbggenerated
     */
    private BigDecimal extrafee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.SUMPREM
     *
     * @mbggenerated
     */
    private BigDecimal sumprem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.SALETYPE
     *
     * @mbggenerated
     */
    private String saletype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.PROPOSALVALIDATECODE
     *
     * @mbggenerated
     */
    private String proposalvalidatecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.CHARGENO
     *
     * @mbggenerated
     */
    private String chargeno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_ORDER.RELATIONORDERNO
     *
     * @mbggenerated
     */
    private String relationorderno;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GE_ORDER
     *
     * @mbggenerated
     */
    public GeOrder(String orderno, String circpaymentno, String userid, String currency, BigDecimal orderamount, Date paytime, String paystatus, String payway, String invoiceflag, String invoicetitle, Date submittime, String status, String gatewayrno, String bankorderno, BigDecimal surcharge, String flowno, String refundmentflag, Date createdate, String recipientname, String recipientmobile, String zipcode, String recipientaddress, Date senddate, String flag, String distributionstatus, String usertype, String datasourse, String encodemsg, String signmsg, String systemssn, String agentidentitycode, String paymentplatform, String paymentsource, String tborderid, String payorderid, String checkpayno, Date accountdate, String alipaybuyeraccount, String alipaybuyerid, Date esbresponsetime, String communicationmode, Date apptime, BigDecimal extrafee, BigDecimal sumprem, String saletype, String proposalvalidatecode, String chargeno, String relationorderno) {
        this.orderno = orderno;
        this.circpaymentno = circpaymentno;
        this.userid = userid;
        this.currency = currency;
        this.orderamount = orderamount;
        this.paytime = paytime;
        this.paystatus = paystatus;
        this.payway = payway;
        this.invoiceflag = invoiceflag;
        this.invoicetitle = invoicetitle;
        this.submittime = submittime;
        this.status = status;
        this.gatewayrno = gatewayrno;
        this.bankorderno = bankorderno;
        this.surcharge = surcharge;
        this.flowno = flowno;
        this.refundmentflag = refundmentflag;
        this.createdate = createdate;
        this.recipientname = recipientname;
        this.recipientmobile = recipientmobile;
        this.zipcode = zipcode;
        this.recipientaddress = recipientaddress;
        this.senddate = senddate;
        this.flag = flag;
        this.distributionstatus = distributionstatus;
        this.usertype = usertype;
        this.datasourse = datasourse;
        this.encodemsg = encodemsg;
        this.signmsg = signmsg;
        this.systemssn = systemssn;
        this.agentidentitycode = agentidentitycode;
        this.paymentplatform = paymentplatform;
        this.paymentsource = paymentsource;
        this.tborderid = tborderid;
        this.payorderid = payorderid;
        this.checkpayno = checkpayno;
        this.accountdate = accountdate;
        this.alipaybuyeraccount = alipaybuyeraccount;
        this.alipaybuyerid = alipaybuyerid;
        this.esbresponsetime = esbresponsetime;
        this.communicationmode = communicationmode;
        this.apptime = apptime;
        this.extrafee = extrafee;
        this.sumprem = sumprem;
        this.saletype = saletype;
        this.proposalvalidatecode = proposalvalidatecode;
        this.chargeno = chargeno;
        this.relationorderno = relationorderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GE_ORDER
     *
     * @mbggenerated
     */
    public GeOrder() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.ORDERNO
     *
     * @return the value of GE_ORDER.ORDERNO
     *
     * @mbggenerated
     */
    public String getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.ORDERNO
     *
     * @param orderno the value for GE_ORDER.ORDERNO
     *
     * @mbggenerated
     */
    public void setOrderno(String orderno) {
        this.orderno = orderno == null ? null : orderno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.CIRCPAYMENTNO
     *
     * @return the value of GE_ORDER.CIRCPAYMENTNO
     *
     * @mbggenerated
     */
    public String getCircpaymentno() {
        return circpaymentno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.CIRCPAYMENTNO
     *
     * @param circpaymentno the value for GE_ORDER.CIRCPAYMENTNO
     *
     * @mbggenerated
     */
    public void setCircpaymentno(String circpaymentno) {
        this.circpaymentno = circpaymentno == null ? null : circpaymentno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.USERID
     *
     * @return the value of GE_ORDER.USERID
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.USERID
     *
     * @param userid the value for GE_ORDER.USERID
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.CURRENCY
     *
     * @return the value of GE_ORDER.CURRENCY
     *
     * @mbggenerated
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.CURRENCY
     *
     * @param currency the value for GE_ORDER.CURRENCY
     *
     * @mbggenerated
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.ORDERAMOUNT
     *
     * @return the value of GE_ORDER.ORDERAMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getOrderamount() {
        return orderamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.ORDERAMOUNT
     *
     * @param orderamount the value for GE_ORDER.ORDERAMOUNT
     *
     * @mbggenerated
     */
    public void setOrderamount(BigDecimal orderamount) {
        this.orderamount = orderamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.PAYTIME
     *
     * @return the value of GE_ORDER.PAYTIME
     *
     * @mbggenerated
     */
    public Date getPaytime() {
        return paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.PAYTIME
     *
     * @param paytime the value for GE_ORDER.PAYTIME
     *
     * @mbggenerated
     */
    public void setPaytime(Date paytime) {
        this.paytime = paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.PAYSTATUS
     *
     * @return the value of GE_ORDER.PAYSTATUS
     *
     * @mbggenerated
     */
    public String getPaystatus() {
        return paystatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.PAYSTATUS
     *
     * @param paystatus the value for GE_ORDER.PAYSTATUS
     *
     * @mbggenerated
     */
    public void setPaystatus(String paystatus) {
        this.paystatus = paystatus == null ? null : paystatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.PAYWAY
     *
     * @return the value of GE_ORDER.PAYWAY
     *
     * @mbggenerated
     */
    public String getPayway() {
        return payway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.PAYWAY
     *
     * @param payway the value for GE_ORDER.PAYWAY
     *
     * @mbggenerated
     */
    public void setPayway(String payway) {
        this.payway = payway == null ? null : payway.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.INVOICEFLAG
     *
     * @return the value of GE_ORDER.INVOICEFLAG
     *
     * @mbggenerated
     */
    public String getInvoiceflag() {
        return invoiceflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.INVOICEFLAG
     *
     * @param invoiceflag the value for GE_ORDER.INVOICEFLAG
     *
     * @mbggenerated
     */
    public void setInvoiceflag(String invoiceflag) {
        this.invoiceflag = invoiceflag == null ? null : invoiceflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.INVOICETITLE
     *
     * @return the value of GE_ORDER.INVOICETITLE
     *
     * @mbggenerated
     */
    public String getInvoicetitle() {
        return invoicetitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.INVOICETITLE
     *
     * @param invoicetitle the value for GE_ORDER.INVOICETITLE
     *
     * @mbggenerated
     */
    public void setInvoicetitle(String invoicetitle) {
        this.invoicetitle = invoicetitle == null ? null : invoicetitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.SUBMITTIME
     *
     * @return the value of GE_ORDER.SUBMITTIME
     *
     * @mbggenerated
     */
    public Date getSubmittime() {
        return submittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.SUBMITTIME
     *
     * @param submittime the value for GE_ORDER.SUBMITTIME
     *
     * @mbggenerated
     */
    public void setSubmittime(Date submittime) {
        this.submittime = submittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.STATUS
     *
     * @return the value of GE_ORDER.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.STATUS
     *
     * @param status the value for GE_ORDER.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.GATEWAYRNO
     *
     * @return the value of GE_ORDER.GATEWAYRNO
     *
     * @mbggenerated
     */
    public String getGatewayrno() {
        return gatewayrno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.GATEWAYRNO
     *
     * @param gatewayrno the value for GE_ORDER.GATEWAYRNO
     *
     * @mbggenerated
     */
    public void setGatewayrno(String gatewayrno) {
        this.gatewayrno = gatewayrno == null ? null : gatewayrno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.BANKORDERNO
     *
     * @return the value of GE_ORDER.BANKORDERNO
     *
     * @mbggenerated
     */
    public String getBankorderno() {
        return bankorderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.BANKORDERNO
     *
     * @param bankorderno the value for GE_ORDER.BANKORDERNO
     *
     * @mbggenerated
     */
    public void setBankorderno(String bankorderno) {
        this.bankorderno = bankorderno == null ? null : bankorderno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.SURCHARGE
     *
     * @return the value of GE_ORDER.SURCHARGE
     *
     * @mbggenerated
     */
    public BigDecimal getSurcharge() {
        return surcharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.SURCHARGE
     *
     * @param surcharge the value for GE_ORDER.SURCHARGE
     *
     * @mbggenerated
     */
    public void setSurcharge(BigDecimal surcharge) {
        this.surcharge = surcharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.FLOWNO
     *
     * @return the value of GE_ORDER.FLOWNO
     *
     * @mbggenerated
     */
    public String getFlowno() {
        return flowno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.FLOWNO
     *
     * @param flowno the value for GE_ORDER.FLOWNO
     *
     * @mbggenerated
     */
    public void setFlowno(String flowno) {
        this.flowno = flowno == null ? null : flowno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.REFUNDMENTFLAG
     *
     * @return the value of GE_ORDER.REFUNDMENTFLAG
     *
     * @mbggenerated
     */
    public String getRefundmentflag() {
        return refundmentflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.REFUNDMENTFLAG
     *
     * @param refundmentflag the value for GE_ORDER.REFUNDMENTFLAG
     *
     * @mbggenerated
     */
    public void setRefundmentflag(String refundmentflag) {
        this.refundmentflag = refundmentflag == null ? null : refundmentflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.CREATEDATE
     *
     * @return the value of GE_ORDER.CREATEDATE
     *
     * @mbggenerated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.CREATEDATE
     *
     * @param createdate the value for GE_ORDER.CREATEDATE
     *
     * @mbggenerated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.RECIPIENTNAME
     *
     * @return the value of GE_ORDER.RECIPIENTNAME
     *
     * @mbggenerated
     */
    public String getRecipientname() {
        return recipientname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.RECIPIENTNAME
     *
     * @param recipientname the value for GE_ORDER.RECIPIENTNAME
     *
     * @mbggenerated
     */
    public void setRecipientname(String recipientname) {
        this.recipientname = recipientname == null ? null : recipientname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.RECIPIENTMOBILE
     *
     * @return the value of GE_ORDER.RECIPIENTMOBILE
     *
     * @mbggenerated
     */
    public String getRecipientmobile() {
        return recipientmobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.RECIPIENTMOBILE
     *
     * @param recipientmobile the value for GE_ORDER.RECIPIENTMOBILE
     *
     * @mbggenerated
     */
    public void setRecipientmobile(String recipientmobile) {
        this.recipientmobile = recipientmobile == null ? null : recipientmobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.ZIPCODE
     *
     * @return the value of GE_ORDER.ZIPCODE
     *
     * @mbggenerated
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.ZIPCODE
     *
     * @param zipcode the value for GE_ORDER.ZIPCODE
     *
     * @mbggenerated
     */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode == null ? null : zipcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.RECIPIENTADDRESS
     *
     * @return the value of GE_ORDER.RECIPIENTADDRESS
     *
     * @mbggenerated
     */
    public String getRecipientaddress() {
        return recipientaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.RECIPIENTADDRESS
     *
     * @param recipientaddress the value for GE_ORDER.RECIPIENTADDRESS
     *
     * @mbggenerated
     */
    public void setRecipientaddress(String recipientaddress) {
        this.recipientaddress = recipientaddress == null ? null : recipientaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.SENDDATE
     *
     * @return the value of GE_ORDER.SENDDATE
     *
     * @mbggenerated
     */
    public Date getSenddate() {
        return senddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.SENDDATE
     *
     * @param senddate the value for GE_ORDER.SENDDATE
     *
     * @mbggenerated
     */
    public void setSenddate(Date senddate) {
        this.senddate = senddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.FLAG
     *
     * @return the value of GE_ORDER.FLAG
     *
     * @mbggenerated
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.FLAG
     *
     * @param flag the value for GE_ORDER.FLAG
     *
     * @mbggenerated
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.DISTRIBUTIONSTATUS
     *
     * @return the value of GE_ORDER.DISTRIBUTIONSTATUS
     *
     * @mbggenerated
     */
    public String getDistributionstatus() {
        return distributionstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.DISTRIBUTIONSTATUS
     *
     * @param distributionstatus the value for GE_ORDER.DISTRIBUTIONSTATUS
     *
     * @mbggenerated
     */
    public void setDistributionstatus(String distributionstatus) {
        this.distributionstatus = distributionstatus == null ? null : distributionstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.USERTYPE
     *
     * @return the value of GE_ORDER.USERTYPE
     *
     * @mbggenerated
     */
    public String getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.USERTYPE
     *
     * @param usertype the value for GE_ORDER.USERTYPE
     *
     * @mbggenerated
     */
    public void setUsertype(String usertype) {
        this.usertype = usertype == null ? null : usertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.DATASOURSE
     *
     * @return the value of GE_ORDER.DATASOURSE
     *
     * @mbggenerated
     */
    public String getDatasourse() {
        return datasourse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.DATASOURSE
     *
     * @param datasourse the value for GE_ORDER.DATASOURSE
     *
     * @mbggenerated
     */
    public void setDatasourse(String datasourse) {
        this.datasourse = datasourse == null ? null : datasourse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.ENCODEMSG
     *
     * @return the value of GE_ORDER.ENCODEMSG
     *
     * @mbggenerated
     */
    public String getEncodemsg() {
        return encodemsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.ENCODEMSG
     *
     * @param encodemsg the value for GE_ORDER.ENCODEMSG
     *
     * @mbggenerated
     */
    public void setEncodemsg(String encodemsg) {
        this.encodemsg = encodemsg == null ? null : encodemsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.SIGNMSG
     *
     * @return the value of GE_ORDER.SIGNMSG
     *
     * @mbggenerated
     */
    public String getSignmsg() {
        return signmsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.SIGNMSG
     *
     * @param signmsg the value for GE_ORDER.SIGNMSG
     *
     * @mbggenerated
     */
    public void setSignmsg(String signmsg) {
        this.signmsg = signmsg == null ? null : signmsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.SYSTEMSSN
     *
     * @return the value of GE_ORDER.SYSTEMSSN
     *
     * @mbggenerated
     */
    public String getSystemssn() {
        return systemssn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.SYSTEMSSN
     *
     * @param systemssn the value for GE_ORDER.SYSTEMSSN
     *
     * @mbggenerated
     */
    public void setSystemssn(String systemssn) {
        this.systemssn = systemssn == null ? null : systemssn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.AGENTIDENTITYCODE
     *
     * @return the value of GE_ORDER.AGENTIDENTITYCODE
     *
     * @mbggenerated
     */
    public String getAgentidentitycode() {
        return agentidentitycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.AGENTIDENTITYCODE
     *
     * @param agentidentitycode the value for GE_ORDER.AGENTIDENTITYCODE
     *
     * @mbggenerated
     */
    public void setAgentidentitycode(String agentidentitycode) {
        this.agentidentitycode = agentidentitycode == null ? null : agentidentitycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.PAYMENTPLATFORM
     *
     * @return the value of GE_ORDER.PAYMENTPLATFORM
     *
     * @mbggenerated
     */
    public String getPaymentplatform() {
        return paymentplatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.PAYMENTPLATFORM
     *
     * @param paymentplatform the value for GE_ORDER.PAYMENTPLATFORM
     *
     * @mbggenerated
     */
    public void setPaymentplatform(String paymentplatform) {
        this.paymentplatform = paymentplatform == null ? null : paymentplatform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.PAYMENTSOURCE
     *
     * @return the value of GE_ORDER.PAYMENTSOURCE
     *
     * @mbggenerated
     */
    public String getPaymentsource() {
        return paymentsource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.PAYMENTSOURCE
     *
     * @param paymentsource the value for GE_ORDER.PAYMENTSOURCE
     *
     * @mbggenerated
     */
    public void setPaymentsource(String paymentsource) {
        this.paymentsource = paymentsource == null ? null : paymentsource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.TBORDERID
     *
     * @return the value of GE_ORDER.TBORDERID
     *
     * @mbggenerated
     */
    public String getTborderid() {
        return tborderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.TBORDERID
     *
     * @param tborderid the value for GE_ORDER.TBORDERID
     *
     * @mbggenerated
     */
    public void setTborderid(String tborderid) {
        this.tborderid = tborderid == null ? null : tborderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.PAYORDERID
     *
     * @return the value of GE_ORDER.PAYORDERID
     *
     * @mbggenerated
     */
    public String getPayorderid() {
        return payorderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.PAYORDERID
     *
     * @param payorderid the value for GE_ORDER.PAYORDERID
     *
     * @mbggenerated
     */
    public void setPayorderid(String payorderid) {
        this.payorderid = payorderid == null ? null : payorderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.CHECKPAYNO
     *
     * @return the value of GE_ORDER.CHECKPAYNO
     *
     * @mbggenerated
     */
    public String getCheckpayno() {
        return checkpayno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.CHECKPAYNO
     *
     * @param checkpayno the value for GE_ORDER.CHECKPAYNO
     *
     * @mbggenerated
     */
    public void setCheckpayno(String checkpayno) {
        this.checkpayno = checkpayno == null ? null : checkpayno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.ACCOUNTDATE
     *
     * @return the value of GE_ORDER.ACCOUNTDATE
     *
     * @mbggenerated
     */
    public Date getAccountdate() {
        return accountdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.ACCOUNTDATE
     *
     * @param accountdate the value for GE_ORDER.ACCOUNTDATE
     *
     * @mbggenerated
     */
    public void setAccountdate(Date accountdate) {
        this.accountdate = accountdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.ALIPAYBUYERACCOUNT
     *
     * @return the value of GE_ORDER.ALIPAYBUYERACCOUNT
     *
     * @mbggenerated
     */
    public String getAlipaybuyeraccount() {
        return alipaybuyeraccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.ALIPAYBUYERACCOUNT
     *
     * @param alipaybuyeraccount the value for GE_ORDER.ALIPAYBUYERACCOUNT
     *
     * @mbggenerated
     */
    public void setAlipaybuyeraccount(String alipaybuyeraccount) {
        this.alipaybuyeraccount = alipaybuyeraccount == null ? null : alipaybuyeraccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.ALIPAYBUYERID
     *
     * @return the value of GE_ORDER.ALIPAYBUYERID
     *
     * @mbggenerated
     */
    public String getAlipaybuyerid() {
        return alipaybuyerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.ALIPAYBUYERID
     *
     * @param alipaybuyerid the value for GE_ORDER.ALIPAYBUYERID
     *
     * @mbggenerated
     */
    public void setAlipaybuyerid(String alipaybuyerid) {
        this.alipaybuyerid = alipaybuyerid == null ? null : alipaybuyerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.ESBRESPONSETIME
     *
     * @return the value of GE_ORDER.ESBRESPONSETIME
     *
     * @mbggenerated
     */
    public Date getEsbresponsetime() {
        return esbresponsetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.ESBRESPONSETIME
     *
     * @param esbresponsetime the value for GE_ORDER.ESBRESPONSETIME
     *
     * @mbggenerated
     */
    public void setEsbresponsetime(Date esbresponsetime) {
        this.esbresponsetime = esbresponsetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.COMMUNICATIONMODE
     *
     * @return the value of GE_ORDER.COMMUNICATIONMODE
     *
     * @mbggenerated
     */
    public String getCommunicationmode() {
        return communicationmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.COMMUNICATIONMODE
     *
     * @param communicationmode the value for GE_ORDER.COMMUNICATIONMODE
     *
     * @mbggenerated
     */
    public void setCommunicationmode(String communicationmode) {
        this.communicationmode = communicationmode == null ? null : communicationmode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.APPTIME
     *
     * @return the value of GE_ORDER.APPTIME
     *
     * @mbggenerated
     */
    public Date getApptime() {
        return apptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.APPTIME
     *
     * @param apptime the value for GE_ORDER.APPTIME
     *
     * @mbggenerated
     */
    public void setApptime(Date apptime) {
        this.apptime = apptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.EXTRAFEE
     *
     * @return the value of GE_ORDER.EXTRAFEE
     *
     * @mbggenerated
     */
    public BigDecimal getExtrafee() {
        return extrafee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.EXTRAFEE
     *
     * @param extrafee the value for GE_ORDER.EXTRAFEE
     *
     * @mbggenerated
     */
    public void setExtrafee(BigDecimal extrafee) {
        this.extrafee = extrafee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.SUMPREM
     *
     * @return the value of GE_ORDER.SUMPREM
     *
     * @mbggenerated
     */
    public BigDecimal getSumprem() {
        return sumprem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.SUMPREM
     *
     * @param sumprem the value for GE_ORDER.SUMPREM
     *
     * @mbggenerated
     */
    public void setSumprem(BigDecimal sumprem) {
        this.sumprem = sumprem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.SALETYPE
     *
     * @return the value of GE_ORDER.SALETYPE
     *
     * @mbggenerated
     */
    public String getSaletype() {
        return saletype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.SALETYPE
     *
     * @param saletype the value for GE_ORDER.SALETYPE
     *
     * @mbggenerated
     */
    public void setSaletype(String saletype) {
        this.saletype = saletype == null ? null : saletype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.PROPOSALVALIDATECODE
     *
     * @return the value of GE_ORDER.PROPOSALVALIDATECODE
     *
     * @mbggenerated
     */
    public String getProposalvalidatecode() {
        return proposalvalidatecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.PROPOSALVALIDATECODE
     *
     * @param proposalvalidatecode the value for GE_ORDER.PROPOSALVALIDATECODE
     *
     * @mbggenerated
     */
    public void setProposalvalidatecode(String proposalvalidatecode) {
        this.proposalvalidatecode = proposalvalidatecode == null ? null : proposalvalidatecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.CHARGENO
     *
     * @return the value of GE_ORDER.CHARGENO
     *
     * @mbggenerated
     */
    public String getChargeno() {
        return chargeno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.CHARGENO
     *
     * @param chargeno the value for GE_ORDER.CHARGENO
     *
     * @mbggenerated
     */
    public void setChargeno(String chargeno) {
        this.chargeno = chargeno == null ? null : chargeno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_ORDER.RELATIONORDERNO
     *
     * @return the value of GE_ORDER.RELATIONORDERNO
     *
     * @mbggenerated
     */
    public String getRelationorderno() {
        return relationorderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_ORDER.RELATIONORDERNO
     *
     * @param relationorderno the value for GE_ORDER.RELATIONORDERNO
     *
     * @mbggenerated
     */
    public void setRelationorderno(String relationorderno) {
        this.relationorderno = relationorderno == null ? null : relationorderno.trim();
    }
}