package com.future.dao4ora.po;

import java.math.BigDecimal;
import java.util.Date;

public class GeProposalMain {
    private GeAirorder geAirorder;
    private GeOrder geOrder;
    private GeQuoteParty geQuoteParty;
    private GeQuotePartyKey geQuotePartyKey;

    public GeQuotePartyKey getGeQuotePartyKey() {
        return geQuotePartyKey;
    }

    public void setGeQuotePartyKey(GeQuotePartyKey geQuotePartyKey) {
        this.geQuotePartyKey = geQuotePartyKey;
    }

    public GeAirorder getGeAirorder() {
        return geAirorder;
    }

    public void setGeAirorder(GeAirorder geAirorder) {
        this.geAirorder = geAirorder;
    }

    public GeOrder getGeOrder() {
        return geOrder;
    }

    public void setGeOrder(GeOrder geOrder) {
        this.geOrder = geOrder;
    }

    public GeQuoteParty getGeQuoteParty() {
        return geQuoteParty;
    }

    public void setGeQuoteParty(GeQuoteParty geQuoteParty) {
        this.geQuoteParty = geQuoteParty;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.PROPOSALSID
     *
     * @mbggenerated
     */
    private String proposalsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.PROPOSALNO
     *
     * @mbggenerated
     */
    private String proposalno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.QUOTENO
     *
     * @mbggenerated
     */
    private String quoteno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.POLICYNO
     *
     * @mbggenerated
     */
    private String policyno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.PRODUCTNO
     *
     * @mbggenerated
     */
    private String productno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.RISKCODE
     *
     * @mbggenerated
     */
    private String riskcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.CLASSCODE
     *
     * @mbggenerated
     */
    private String classcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.BUSINESSNATURE
     *
     * @mbggenerated
     */
    private String businessnature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.AREACODE
     *
     * @mbggenerated
     */
    private String areacode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.SALECOM
     *
     * @mbggenerated
     */
    private String salecom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.OPERATEDATE
     *
     * @mbggenerated
     */
    private Date operatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.APPLINAME
     *
     * @mbggenerated
     */
    private String appliname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.APPLIADDRESS
     *
     * @mbggenerated
     */
    private String appliaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.INSUREDNAME
     *
     * @mbggenerated
     */
    private String insuredname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.INSUREDADDRESS
     *
     * @mbggenerated
     */
    private String insuredaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.USERID
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.USERTYPE
     *
     * @mbggenerated
     */
    private String usertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.CHANNELCODE
     *
     * @mbggenerated
     */
    private String channelcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.RENEWALFLAG
     *
     * @mbggenerated
     */
    private String renewalflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.OLDLPOLICYNO
     *
     * @mbggenerated
     */
    private String oldlpolicyno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.STARTDATE
     *
     * @mbggenerated
     */
    private Date startdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.ENDDATE
     *
     * @mbggenerated
     */
    private Date enddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.UNITCOUNT
     *
     * @mbggenerated
     */
    private String unitcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.PERIODUNIT
     *
     * @mbggenerated
     */
    private String periodunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.PERIOD
     *
     * @mbggenerated
     */
    private String period;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.CURRENCY
     *
     * @mbggenerated
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.MAXINSURANCEAMOUNT
     *
     * @mbggenerated
     */
    private String maxinsuranceamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.SUMAMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal sumamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.SUMBASEPREMIUM
     *
     * @mbggenerated
     */
    private BigDecimal sumbasepremium;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.DISCOUNT
     *
     * @mbggenerated
     */
    private BigDecimal discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.SUMDISCOUNT
     *
     * @mbggenerated
     */
    private BigDecimal sumdiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.SUMPREMIUM
     *
     * @mbggenerated
     */
    private BigDecimal sumpremium;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.SUMSUBPREMIUM
     *
     * @mbggenerated
     */
    private BigDecimal sumsubpremium;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.ISPAPER
     *
     * @mbggenerated
     */
    private String ispaper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.ELEADDRESS
     *
     * @mbggenerated
     */
    private String eleaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.BUSINESSAREA
     *
     * @mbggenerated
     */
    private String businessarea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.PLATFORMINVALIDDATE
     *
     * @mbggenerated
     */
    private Date platforminvaliddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.INPUTDATE
     *
     * @mbggenerated
     */
    private Date inputdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.INPUTHOUR
     *
     * @mbggenerated
     */
    private String inputhour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.ISLEGALFLAG
     *
     * @mbggenerated
     */
    private String islegalflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.ISCLEAR
     *
     * @mbggenerated
     */
    private String isclear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.UPDATETIME
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.UPDATEDATE
     *
     * @mbggenerated
     */
    private Date updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.AGENTCODE
     *
     * @mbggenerated
     */
    private String agentcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.AGREEMENTNO
     *
     * @mbggenerated
     */
    private String agreementno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.AGENTNAME
     *
     * @mbggenerated
     */
    private String agentname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.DEPARTMENTNO
     *
     * @mbggenerated
     */
    private String departmentno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.DEPARTMENTNAME
     *
     * @mbggenerated
     */
    private String departmentname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.REASON
     *
     * @mbggenerated
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.FLAG
     *
     * @mbggenerated
     */
    private String flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.EID
     *
     * @mbggenerated
     */
    private String eid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.AREACODEPRO
     *
     * @mbggenerated
     */
    private String areacodepro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.PRECHECKDATE
     *
     * @mbggenerated
     */
    private String precheckdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.MOREBUYNO
     *
     * @mbggenerated
     */
    private String morebuyno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.DISCOUNTID
     *
     * @mbggenerated
     */
    private String discountid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.PAYMENTSTATUS
     *
     * @mbggenerated
     */
    private String paymentstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.BUSINESSSOURCE
     *
     * @mbggenerated
     */
    private String businesssource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.GROUPCHANNEL
     *
     * @mbggenerated
     */
    private String groupchannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.HXSUMPREMIUM
     *
     * @mbggenerated
     */
    private BigDecimal hxsumpremium;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.HXSTATUS
     *
     * @mbggenerated
     */
    private String hxstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.HXPOLICYSTATUS
     *
     * @mbggenerated
     */
    private String hxpolicystatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.SESSIONID
     *
     * @mbggenerated
     */
    private String sessionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.TBITEMID
     *
     * @mbggenerated
     */
    private String tbitemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.TBSUBORDERID
     *
     * @mbggenerated
     */
    private String tbsuborderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.ITEMID
     *
     * @mbggenerated
     */
    private String itemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.TBORDERID
     *
     * @mbggenerated
     */
    private String tborderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.COMMUNICATIONMODE
     *
     * @mbggenerated
     */
    private String communicationmode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.APPTIME
     *
     * @mbggenerated
     */
    private String apptime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.ZHREFERENCECODE
     *
     * @mbggenerated
     */
    private String zhreferencecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.SALETYPE
     *
     * @mbggenerated
     */
    private String saletype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.SOCIATYPAYMENTNO
     *
     * @mbggenerated
     */
    private String sociatypaymentno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.REFERRALCODE
     *
     * @mbggenerated
     */
    private String referralcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.ORDERNO
     *
     * @mbggenerated
     */
    private String orderno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.OPENID
     *
     * @mbggenerated
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.SALESMANID
     *
     * @mbggenerated
     */
    private String salesmanid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.SALESMANCHANNEL
     *
     * @mbggenerated
     */
    private String salesmanchannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.SALESMANTYPE
     *
     * @mbggenerated
     */
    private String salesmantype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.MOBILEIMEI
     *
     * @mbggenerated
     */
    private String mobileimei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.MAINTENANCE
     *
     * @mbggenerated
     */
    private Short maintenance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.MOBILEBRAND
     *
     * @mbggenerated
     */
    private String mobilebrand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.MOBILEMODEL
     *
     * @mbggenerated
     */
    private String mobilemodel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.ISCLAIMS
     *
     * @mbggenerated
     */
    private String isclaims;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.CLAIMSTIME
     *
     * @mbggenerated
     */
    private Date claimstime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.RECEIVEAGE
     *
     * @mbggenerated
     */
    private String receiveage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.PAYTIME
     *
     * @mbggenerated
     */
    private String paytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.LOANPREMIUM
     *
     * @mbggenerated
     */
    private BigDecimal loanpremium;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.LOANSTARTTIME
     *
     * @mbggenerated
     */
    private Date loanstarttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.LOANENDTIME
     *
     * @mbggenerated
     */
    private Date loanendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.SURRENDERSTATUS
     *
     * @mbggenerated
     */
    private String surrenderstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.SURRENDERTIME
     *
     * @mbggenerated
     */
    private Date surrendertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.SURRENDERUPDATEDATE
     *
     * @mbggenerated
     */
    private Date surrenderupdatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.SURRENDERUPDATETIME
     *
     * @mbggenerated
     */
    private Date surrenderupdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.SURRENDERMSG
     *
     * @mbggenerated
     */
    private String surrendermsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_PROPOSAL_MAIN.REQUESTEDTIME
     *
     * @mbggenerated
     */
    private Date requestedtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GE_PROPOSAL_MAIN
     *
     * @mbggenerated
     */
    public GeProposalMain(String proposalsid, String proposalno, String quoteno, String policyno, String productno, String riskcode, String classcode, String businessnature, String areacode, String salecom, Date operatedate, String appliname, String appliaddress, String insuredname, String insuredaddress, String userid, String usertype, String channelcode, String renewalflag, String oldlpolicyno, Date startdate, Date enddate, String unitcount, String periodunit, String period, String currency, String maxinsuranceamount, BigDecimal sumamount, BigDecimal sumbasepremium, BigDecimal discount, BigDecimal sumdiscount, BigDecimal sumpremium, BigDecimal sumsubpremium, String ispaper, String eleaddress, String businessarea, Date platforminvaliddate, Date inputdate, String inputhour, String islegalflag, String isclear, String status, Date updatetime, Date updatedate, String agentcode, String agreementno, String agentname, String departmentno, String departmentname, String reason, String flag, String eid, String areacodepro, String precheckdate, String morebuyno, String discountid, String paymentstatus, String businesssource, String groupchannel, BigDecimal hxsumpremium, String hxstatus, String hxpolicystatus, String sessionid, String tbitemid, String tbsuborderid, String itemid, String tborderid, String communicationmode, String apptime, String zhreferencecode, String saletype, String sociatypaymentno, String referralcode, String orderno, String openid, String salesmanid, String salesmanchannel, String salesmantype, String mobileimei, Short maintenance, String mobilebrand, String mobilemodel, String isclaims, Date claimstime, String receiveage, String paytime, BigDecimal loanpremium, Date loanstarttime, Date loanendtime, String surrenderstatus, Date surrendertime, Date surrenderupdatedate, Date surrenderupdatetime, String surrendermsg, Date requestedtime) {
        this.proposalsid = proposalsid;
        this.proposalno = proposalno;
        this.quoteno = quoteno;
        this.policyno = policyno;
        this.productno = productno;
        this.riskcode = riskcode;
        this.classcode = classcode;
        this.businessnature = businessnature;
        this.areacode = areacode;
        this.salecom = salecom;
        this.operatedate = operatedate;
        this.appliname = appliname;
        this.appliaddress = appliaddress;
        this.insuredname = insuredname;
        this.insuredaddress = insuredaddress;
        this.userid = userid;
        this.usertype = usertype;
        this.channelcode = channelcode;
        this.renewalflag = renewalflag;
        this.oldlpolicyno = oldlpolicyno;
        this.startdate = startdate;
        this.enddate = enddate;
        this.unitcount = unitcount;
        this.periodunit = periodunit;
        this.period = period;
        this.currency = currency;
        this.maxinsuranceamount = maxinsuranceamount;
        this.sumamount = sumamount;
        this.sumbasepremium = sumbasepremium;
        this.discount = discount;
        this.sumdiscount = sumdiscount;
        this.sumpremium = sumpremium;
        this.sumsubpremium = sumsubpremium;
        this.ispaper = ispaper;
        this.eleaddress = eleaddress;
        this.businessarea = businessarea;
        this.platforminvaliddate = platforminvaliddate;
        this.inputdate = inputdate;
        this.inputhour = inputhour;
        this.islegalflag = islegalflag;
        this.isclear = isclear;
        this.status = status;
        this.updatetime = updatetime;
        this.updatedate = updatedate;
        this.agentcode = agentcode;
        this.agreementno = agreementno;
        this.agentname = agentname;
        this.departmentno = departmentno;
        this.departmentname = departmentname;
        this.reason = reason;
        this.flag = flag;
        this.eid = eid;
        this.areacodepro = areacodepro;
        this.precheckdate = precheckdate;
        this.morebuyno = morebuyno;
        this.discountid = discountid;
        this.paymentstatus = paymentstatus;
        this.businesssource = businesssource;
        this.groupchannel = groupchannel;
        this.hxsumpremium = hxsumpremium;
        this.hxstatus = hxstatus;
        this.hxpolicystatus = hxpolicystatus;
        this.sessionid = sessionid;
        this.tbitemid = tbitemid;
        this.tbsuborderid = tbsuborderid;
        this.itemid = itemid;
        this.tborderid = tborderid;
        this.communicationmode = communicationmode;
        this.apptime = apptime;
        this.zhreferencecode = zhreferencecode;
        this.saletype = saletype;
        this.sociatypaymentno = sociatypaymentno;
        this.referralcode = referralcode;
        this.orderno = orderno;
        this.openid = openid;
        this.salesmanid = salesmanid;
        this.salesmanchannel = salesmanchannel;
        this.salesmantype = salesmantype;
        this.mobileimei = mobileimei;
        this.maintenance = maintenance;
        this.mobilebrand = mobilebrand;
        this.mobilemodel = mobilemodel;
        this.isclaims = isclaims;
        this.claimstime = claimstime;
        this.receiveage = receiveage;
        this.paytime = paytime;
        this.loanpremium = loanpremium;
        this.loanstarttime = loanstarttime;
        this.loanendtime = loanendtime;
        this.surrenderstatus = surrenderstatus;
        this.surrendertime = surrendertime;
        this.surrenderupdatedate = surrenderupdatedate;
        this.surrenderupdatetime = surrenderupdatetime;
        this.surrendermsg = surrendermsg;
        this.requestedtime = requestedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GE_PROPOSAL_MAIN
     *
     * @mbggenerated
     */
    public GeProposalMain() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.PROPOSALSID
     *
     * @return the value of GE_PROPOSAL_MAIN.PROPOSALSID
     *
     * @mbggenerated
     */
    public String getProposalsid() {
        return proposalsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.PROPOSALSID
     *
     * @param proposalsid the value for GE_PROPOSAL_MAIN.PROPOSALSID
     *
     * @mbggenerated
     */
    public void setProposalsid(String proposalsid) {
        this.proposalsid = proposalsid == null ? null : proposalsid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.PROPOSALNO
     *
     * @return the value of GE_PROPOSAL_MAIN.PROPOSALNO
     *
     * @mbggenerated
     */
    public String getProposalno() {
        return proposalno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.PROPOSALNO
     *
     * @param proposalno the value for GE_PROPOSAL_MAIN.PROPOSALNO
     *
     * @mbggenerated
     */
    public void setProposalno(String proposalno) {
        this.proposalno = proposalno == null ? null : proposalno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.QUOTENO
     *
     * @return the value of GE_PROPOSAL_MAIN.QUOTENO
     *
     * @mbggenerated
     */
    public String getQuoteno() {
        return quoteno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.QUOTENO
     *
     * @param quoteno the value for GE_PROPOSAL_MAIN.QUOTENO
     *
     * @mbggenerated
     */
    public void setQuoteno(String quoteno) {
        this.quoteno = quoteno == null ? null : quoteno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.POLICYNO
     *
     * @return the value of GE_PROPOSAL_MAIN.POLICYNO
     *
     * @mbggenerated
     */
    public String getPolicyno() {
        return policyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.POLICYNO
     *
     * @param policyno the value for GE_PROPOSAL_MAIN.POLICYNO
     *
     * @mbggenerated
     */
    public void setPolicyno(String policyno) {
        this.policyno = policyno == null ? null : policyno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.PRODUCTNO
     *
     * @return the value of GE_PROPOSAL_MAIN.PRODUCTNO
     *
     * @mbggenerated
     */
    public String getProductno() {
        return productno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.PRODUCTNO
     *
     * @param productno the value for GE_PROPOSAL_MAIN.PRODUCTNO
     *
     * @mbggenerated
     */
    public void setProductno(String productno) {
        this.productno = productno == null ? null : productno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.RISKCODE
     *
     * @return the value of GE_PROPOSAL_MAIN.RISKCODE
     *
     * @mbggenerated
     */
    public String getRiskcode() {
        return riskcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.RISKCODE
     *
     * @param riskcode the value for GE_PROPOSAL_MAIN.RISKCODE
     *
     * @mbggenerated
     */
    public void setRiskcode(String riskcode) {
        this.riskcode = riskcode == null ? null : riskcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.CLASSCODE
     *
     * @return the value of GE_PROPOSAL_MAIN.CLASSCODE
     *
     * @mbggenerated
     */
    public String getClasscode() {
        return classcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.CLASSCODE
     *
     * @param classcode the value for GE_PROPOSAL_MAIN.CLASSCODE
     *
     * @mbggenerated
     */
    public void setClasscode(String classcode) {
        this.classcode = classcode == null ? null : classcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.BUSINESSNATURE
     *
     * @return the value of GE_PROPOSAL_MAIN.BUSINESSNATURE
     *
     * @mbggenerated
     */
    public String getBusinessnature() {
        return businessnature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.BUSINESSNATURE
     *
     * @param businessnature the value for GE_PROPOSAL_MAIN.BUSINESSNATURE
     *
     * @mbggenerated
     */
    public void setBusinessnature(String businessnature) {
        this.businessnature = businessnature == null ? null : businessnature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.AREACODE
     *
     * @return the value of GE_PROPOSAL_MAIN.AREACODE
     *
     * @mbggenerated
     */
    public String getAreacode() {
        return areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.AREACODE
     *
     * @param areacode the value for GE_PROPOSAL_MAIN.AREACODE
     *
     * @mbggenerated
     */
    public void setAreacode(String areacode) {
        this.areacode = areacode == null ? null : areacode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.SALECOM
     *
     * @return the value of GE_PROPOSAL_MAIN.SALECOM
     *
     * @mbggenerated
     */
    public String getSalecom() {
        return salecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.SALECOM
     *
     * @param salecom the value for GE_PROPOSAL_MAIN.SALECOM
     *
     * @mbggenerated
     */
    public void setSalecom(String salecom) {
        this.salecom = salecom == null ? null : salecom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.OPERATEDATE
     *
     * @return the value of GE_PROPOSAL_MAIN.OPERATEDATE
     *
     * @mbggenerated
     */
    public Date getOperatedate() {
        return operatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.OPERATEDATE
     *
     * @param operatedate the value for GE_PROPOSAL_MAIN.OPERATEDATE
     *
     * @mbggenerated
     */
    public void setOperatedate(Date operatedate) {
        this.operatedate = operatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.APPLINAME
     *
     * @return the value of GE_PROPOSAL_MAIN.APPLINAME
     *
     * @mbggenerated
     */
    public String getAppliname() {
        return appliname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.APPLINAME
     *
     * @param appliname the value for GE_PROPOSAL_MAIN.APPLINAME
     *
     * @mbggenerated
     */
    public void setAppliname(String appliname) {
        this.appliname = appliname == null ? null : appliname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.APPLIADDRESS
     *
     * @return the value of GE_PROPOSAL_MAIN.APPLIADDRESS
     *
     * @mbggenerated
     */
    public String getAppliaddress() {
        return appliaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.APPLIADDRESS
     *
     * @param appliaddress the value for GE_PROPOSAL_MAIN.APPLIADDRESS
     *
     * @mbggenerated
     */
    public void setAppliaddress(String appliaddress) {
        this.appliaddress = appliaddress == null ? null : appliaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.INSUREDNAME
     *
     * @return the value of GE_PROPOSAL_MAIN.INSUREDNAME
     *
     * @mbggenerated
     */
    public String getInsuredname() {
        return insuredname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.INSUREDNAME
     *
     * @param insuredname the value for GE_PROPOSAL_MAIN.INSUREDNAME
     *
     * @mbggenerated
     */
    public void setInsuredname(String insuredname) {
        this.insuredname = insuredname == null ? null : insuredname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.INSUREDADDRESS
     *
     * @return the value of GE_PROPOSAL_MAIN.INSUREDADDRESS
     *
     * @mbggenerated
     */
    public String getInsuredaddress() {
        return insuredaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.INSUREDADDRESS
     *
     * @param insuredaddress the value for GE_PROPOSAL_MAIN.INSUREDADDRESS
     *
     * @mbggenerated
     */
    public void setInsuredaddress(String insuredaddress) {
        this.insuredaddress = insuredaddress == null ? null : insuredaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.USERID
     *
     * @return the value of GE_PROPOSAL_MAIN.USERID
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.USERID
     *
     * @param userid the value for GE_PROPOSAL_MAIN.USERID
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.USERTYPE
     *
     * @return the value of GE_PROPOSAL_MAIN.USERTYPE
     *
     * @mbggenerated
     */
    public String getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.USERTYPE
     *
     * @param usertype the value for GE_PROPOSAL_MAIN.USERTYPE
     *
     * @mbggenerated
     */
    public void setUsertype(String usertype) {
        this.usertype = usertype == null ? null : usertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.CHANNELCODE
     *
     * @return the value of GE_PROPOSAL_MAIN.CHANNELCODE
     *
     * @mbggenerated
     */
    public String getChannelcode() {
        return channelcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.CHANNELCODE
     *
     * @param channelcode the value for GE_PROPOSAL_MAIN.CHANNELCODE
     *
     * @mbggenerated
     */
    public void setChannelcode(String channelcode) {
        this.channelcode = channelcode == null ? null : channelcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.RENEWALFLAG
     *
     * @return the value of GE_PROPOSAL_MAIN.RENEWALFLAG
     *
     * @mbggenerated
     */
    public String getRenewalflag() {
        return renewalflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.RENEWALFLAG
     *
     * @param renewalflag the value for GE_PROPOSAL_MAIN.RENEWALFLAG
     *
     * @mbggenerated
     */
    public void setRenewalflag(String renewalflag) {
        this.renewalflag = renewalflag == null ? null : renewalflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.OLDLPOLICYNO
     *
     * @return the value of GE_PROPOSAL_MAIN.OLDLPOLICYNO
     *
     * @mbggenerated
     */
    public String getOldlpolicyno() {
        return oldlpolicyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.OLDLPOLICYNO
     *
     * @param oldlpolicyno the value for GE_PROPOSAL_MAIN.OLDLPOLICYNO
     *
     * @mbggenerated
     */
    public void setOldlpolicyno(String oldlpolicyno) {
        this.oldlpolicyno = oldlpolicyno == null ? null : oldlpolicyno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.STARTDATE
     *
     * @return the value of GE_PROPOSAL_MAIN.STARTDATE
     *
     * @mbggenerated
     */
    public Date getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.STARTDATE
     *
     * @param startdate the value for GE_PROPOSAL_MAIN.STARTDATE
     *
     * @mbggenerated
     */
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.ENDDATE
     *
     * @return the value of GE_PROPOSAL_MAIN.ENDDATE
     *
     * @mbggenerated
     */
    public Date getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.ENDDATE
     *
     * @param enddate the value for GE_PROPOSAL_MAIN.ENDDATE
     *
     * @mbggenerated
     */
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.UNITCOUNT
     *
     * @return the value of GE_PROPOSAL_MAIN.UNITCOUNT
     *
     * @mbggenerated
     */
    public String getUnitcount() {
        return unitcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.UNITCOUNT
     *
     * @param unitcount the value for GE_PROPOSAL_MAIN.UNITCOUNT
     *
     * @mbggenerated
     */
    public void setUnitcount(String unitcount) {
        this.unitcount = unitcount == null ? null : unitcount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.PERIODUNIT
     *
     * @return the value of GE_PROPOSAL_MAIN.PERIODUNIT
     *
     * @mbggenerated
     */
    public String getPeriodunit() {
        return periodunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.PERIODUNIT
     *
     * @param periodunit the value for GE_PROPOSAL_MAIN.PERIODUNIT
     *
     * @mbggenerated
     */
    public void setPeriodunit(String periodunit) {
        this.periodunit = periodunit == null ? null : periodunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.PERIOD
     *
     * @return the value of GE_PROPOSAL_MAIN.PERIOD
     *
     * @mbggenerated
     */
    public String getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.PERIOD
     *
     * @param period the value for GE_PROPOSAL_MAIN.PERIOD
     *
     * @mbggenerated
     */
    public void setPeriod(String period) {
        this.period = period == null ? null : period.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.CURRENCY
     *
     * @return the value of GE_PROPOSAL_MAIN.CURRENCY
     *
     * @mbggenerated
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.CURRENCY
     *
     * @param currency the value for GE_PROPOSAL_MAIN.CURRENCY
     *
     * @mbggenerated
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.MAXINSURANCEAMOUNT
     *
     * @return the value of GE_PROPOSAL_MAIN.MAXINSURANCEAMOUNT
     *
     * @mbggenerated
     */
    public String getMaxinsuranceamount() {
        return maxinsuranceamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.MAXINSURANCEAMOUNT
     *
     * @param maxinsuranceamount the value for GE_PROPOSAL_MAIN.MAXINSURANCEAMOUNT
     *
     * @mbggenerated
     */
    public void setMaxinsuranceamount(String maxinsuranceamount) {
        this.maxinsuranceamount = maxinsuranceamount == null ? null : maxinsuranceamount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.SUMAMOUNT
     *
     * @return the value of GE_PROPOSAL_MAIN.SUMAMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getSumamount() {
        return sumamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.SUMAMOUNT
     *
     * @param sumamount the value for GE_PROPOSAL_MAIN.SUMAMOUNT
     *
     * @mbggenerated
     */
    public void setSumamount(BigDecimal sumamount) {
        this.sumamount = sumamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.SUMBASEPREMIUM
     *
     * @return the value of GE_PROPOSAL_MAIN.SUMBASEPREMIUM
     *
     * @mbggenerated
     */
    public BigDecimal getSumbasepremium() {
        return sumbasepremium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.SUMBASEPREMIUM
     *
     * @param sumbasepremium the value for GE_PROPOSAL_MAIN.SUMBASEPREMIUM
     *
     * @mbggenerated
     */
    public void setSumbasepremium(BigDecimal sumbasepremium) {
        this.sumbasepremium = sumbasepremium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.DISCOUNT
     *
     * @return the value of GE_PROPOSAL_MAIN.DISCOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.DISCOUNT
     *
     * @param discount the value for GE_PROPOSAL_MAIN.DISCOUNT
     *
     * @mbggenerated
     */
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.SUMDISCOUNT
     *
     * @return the value of GE_PROPOSAL_MAIN.SUMDISCOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getSumdiscount() {
        return sumdiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.SUMDISCOUNT
     *
     * @param sumdiscount the value for GE_PROPOSAL_MAIN.SUMDISCOUNT
     *
     * @mbggenerated
     */
    public void setSumdiscount(BigDecimal sumdiscount) {
        this.sumdiscount = sumdiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.SUMPREMIUM
     *
     * @return the value of GE_PROPOSAL_MAIN.SUMPREMIUM
     *
     * @mbggenerated
     */
    public BigDecimal getSumpremium() {
        return sumpremium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.SUMPREMIUM
     *
     * @param sumpremium the value for GE_PROPOSAL_MAIN.SUMPREMIUM
     *
     * @mbggenerated
     */
    public void setSumpremium(BigDecimal sumpremium) {
        this.sumpremium = sumpremium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.SUMSUBPREMIUM
     *
     * @return the value of GE_PROPOSAL_MAIN.SUMSUBPREMIUM
     *
     * @mbggenerated
     */
    public BigDecimal getSumsubpremium() {
        return sumsubpremium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.SUMSUBPREMIUM
     *
     * @param sumsubpremium the value for GE_PROPOSAL_MAIN.SUMSUBPREMIUM
     *
     * @mbggenerated
     */
    public void setSumsubpremium(BigDecimal sumsubpremium) {
        this.sumsubpremium = sumsubpremium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.ISPAPER
     *
     * @return the value of GE_PROPOSAL_MAIN.ISPAPER
     *
     * @mbggenerated
     */
    public String getIspaper() {
        return ispaper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.ISPAPER
     *
     * @param ispaper the value for GE_PROPOSAL_MAIN.ISPAPER
     *
     * @mbggenerated
     */
    public void setIspaper(String ispaper) {
        this.ispaper = ispaper == null ? null : ispaper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.ELEADDRESS
     *
     * @return the value of GE_PROPOSAL_MAIN.ELEADDRESS
     *
     * @mbggenerated
     */
    public String getEleaddress() {
        return eleaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.ELEADDRESS
     *
     * @param eleaddress the value for GE_PROPOSAL_MAIN.ELEADDRESS
     *
     * @mbggenerated
     */
    public void setEleaddress(String eleaddress) {
        this.eleaddress = eleaddress == null ? null : eleaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.BUSINESSAREA
     *
     * @return the value of GE_PROPOSAL_MAIN.BUSINESSAREA
     *
     * @mbggenerated
     */
    public String getBusinessarea() {
        return businessarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.BUSINESSAREA
     *
     * @param businessarea the value for GE_PROPOSAL_MAIN.BUSINESSAREA
     *
     * @mbggenerated
     */
    public void setBusinessarea(String businessarea) {
        this.businessarea = businessarea == null ? null : businessarea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.PLATFORMINVALIDDATE
     *
     * @return the value of GE_PROPOSAL_MAIN.PLATFORMINVALIDDATE
     *
     * @mbggenerated
     */
    public Date getPlatforminvaliddate() {
        return platforminvaliddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.PLATFORMINVALIDDATE
     *
     * @param platforminvaliddate the value for GE_PROPOSAL_MAIN.PLATFORMINVALIDDATE
     *
     * @mbggenerated
     */
    public void setPlatforminvaliddate(Date platforminvaliddate) {
        this.platforminvaliddate = platforminvaliddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.INPUTDATE
     *
     * @return the value of GE_PROPOSAL_MAIN.INPUTDATE
     *
     * @mbggenerated
     */
    public Date getInputdate() {
        return inputdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.INPUTDATE
     *
     * @param inputdate the value for GE_PROPOSAL_MAIN.INPUTDATE
     *
     * @mbggenerated
     */
    public void setInputdate(Date inputdate) {
        this.inputdate = inputdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.INPUTHOUR
     *
     * @return the value of GE_PROPOSAL_MAIN.INPUTHOUR
     *
     * @mbggenerated
     */
    public String getInputhour() {
        return inputhour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.INPUTHOUR
     *
     * @param inputhour the value for GE_PROPOSAL_MAIN.INPUTHOUR
     *
     * @mbggenerated
     */
    public void setInputhour(String inputhour) {
        this.inputhour = inputhour == null ? null : inputhour.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.ISLEGALFLAG
     *
     * @return the value of GE_PROPOSAL_MAIN.ISLEGALFLAG
     *
     * @mbggenerated
     */
    public String getIslegalflag() {
        return islegalflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.ISLEGALFLAG
     *
     * @param islegalflag the value for GE_PROPOSAL_MAIN.ISLEGALFLAG
     *
     * @mbggenerated
     */
    public void setIslegalflag(String islegalflag) {
        this.islegalflag = islegalflag == null ? null : islegalflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.ISCLEAR
     *
     * @return the value of GE_PROPOSAL_MAIN.ISCLEAR
     *
     * @mbggenerated
     */
    public String getIsclear() {
        return isclear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.ISCLEAR
     *
     * @param isclear the value for GE_PROPOSAL_MAIN.ISCLEAR
     *
     * @mbggenerated
     */
    public void setIsclear(String isclear) {
        this.isclear = isclear == null ? null : isclear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.STATUS
     *
     * @return the value of GE_PROPOSAL_MAIN.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.STATUS
     *
     * @param status the value for GE_PROPOSAL_MAIN.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.UPDATETIME
     *
     * @return the value of GE_PROPOSAL_MAIN.UPDATETIME
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.UPDATETIME
     *
     * @param updatetime the value for GE_PROPOSAL_MAIN.UPDATETIME
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.UPDATEDATE
     *
     * @return the value of GE_PROPOSAL_MAIN.UPDATEDATE
     *
     * @mbggenerated
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.UPDATEDATE
     *
     * @param updatedate the value for GE_PROPOSAL_MAIN.UPDATEDATE
     *
     * @mbggenerated
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.AGENTCODE
     *
     * @return the value of GE_PROPOSAL_MAIN.AGENTCODE
     *
     * @mbggenerated
     */
    public String getAgentcode() {
        return agentcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.AGENTCODE
     *
     * @param agentcode the value for GE_PROPOSAL_MAIN.AGENTCODE
     *
     * @mbggenerated
     */
    public void setAgentcode(String agentcode) {
        this.agentcode = agentcode == null ? null : agentcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.AGREEMENTNO
     *
     * @return the value of GE_PROPOSAL_MAIN.AGREEMENTNO
     *
     * @mbggenerated
     */
    public String getAgreementno() {
        return agreementno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.AGREEMENTNO
     *
     * @param agreementno the value for GE_PROPOSAL_MAIN.AGREEMENTNO
     *
     * @mbggenerated
     */
    public void setAgreementno(String agreementno) {
        this.agreementno = agreementno == null ? null : agreementno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.AGENTNAME
     *
     * @return the value of GE_PROPOSAL_MAIN.AGENTNAME
     *
     * @mbggenerated
     */
    public String getAgentname() {
        return agentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.AGENTNAME
     *
     * @param agentname the value for GE_PROPOSAL_MAIN.AGENTNAME
     *
     * @mbggenerated
     */
    public void setAgentname(String agentname) {
        this.agentname = agentname == null ? null : agentname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.DEPARTMENTNO
     *
     * @return the value of GE_PROPOSAL_MAIN.DEPARTMENTNO
     *
     * @mbggenerated
     */
    public String getDepartmentno() {
        return departmentno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.DEPARTMENTNO
     *
     * @param departmentno the value for GE_PROPOSAL_MAIN.DEPARTMENTNO
     *
     * @mbggenerated
     */
    public void setDepartmentno(String departmentno) {
        this.departmentno = departmentno == null ? null : departmentno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.DEPARTMENTNAME
     *
     * @return the value of GE_PROPOSAL_MAIN.DEPARTMENTNAME
     *
     * @mbggenerated
     */
    public String getDepartmentname() {
        return departmentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.DEPARTMENTNAME
     *
     * @param departmentname the value for GE_PROPOSAL_MAIN.DEPARTMENTNAME
     *
     * @mbggenerated
     */
    public void setDepartmentname(String departmentname) {
        this.departmentname = departmentname == null ? null : departmentname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.REASON
     *
     * @return the value of GE_PROPOSAL_MAIN.REASON
     *
     * @mbggenerated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.REASON
     *
     * @param reason the value for GE_PROPOSAL_MAIN.REASON
     *
     * @mbggenerated
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.FLAG
     *
     * @return the value of GE_PROPOSAL_MAIN.FLAG
     *
     * @mbggenerated
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.FLAG
     *
     * @param flag the value for GE_PROPOSAL_MAIN.FLAG
     *
     * @mbggenerated
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.EID
     *
     * @return the value of GE_PROPOSAL_MAIN.EID
     *
     * @mbggenerated
     */
    public String getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.EID
     *
     * @param eid the value for GE_PROPOSAL_MAIN.EID
     *
     * @mbggenerated
     */
    public void setEid(String eid) {
        this.eid = eid == null ? null : eid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.AREACODEPRO
     *
     * @return the value of GE_PROPOSAL_MAIN.AREACODEPRO
     *
     * @mbggenerated
     */
    public String getAreacodepro() {
        return areacodepro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.AREACODEPRO
     *
     * @param areacodepro the value for GE_PROPOSAL_MAIN.AREACODEPRO
     *
     * @mbggenerated
     */
    public void setAreacodepro(String areacodepro) {
        this.areacodepro = areacodepro == null ? null : areacodepro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.PRECHECKDATE
     *
     * @return the value of GE_PROPOSAL_MAIN.PRECHECKDATE
     *
     * @mbggenerated
     */
    public String getPrecheckdate() {
        return precheckdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.PRECHECKDATE
     *
     * @param precheckdate the value for GE_PROPOSAL_MAIN.PRECHECKDATE
     *
     * @mbggenerated
     */
    public void setPrecheckdate(String precheckdate) {
        this.precheckdate = precheckdate == null ? null : precheckdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.MOREBUYNO
     *
     * @return the value of GE_PROPOSAL_MAIN.MOREBUYNO
     *
     * @mbggenerated
     */
    public String getMorebuyno() {
        return morebuyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.MOREBUYNO
     *
     * @param morebuyno the value for GE_PROPOSAL_MAIN.MOREBUYNO
     *
     * @mbggenerated
     */
    public void setMorebuyno(String morebuyno) {
        this.morebuyno = morebuyno == null ? null : morebuyno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.DISCOUNTID
     *
     * @return the value of GE_PROPOSAL_MAIN.DISCOUNTID
     *
     * @mbggenerated
     */
    public String getDiscountid() {
        return discountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.DISCOUNTID
     *
     * @param discountid the value for GE_PROPOSAL_MAIN.DISCOUNTID
     *
     * @mbggenerated
     */
    public void setDiscountid(String discountid) {
        this.discountid = discountid == null ? null : discountid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.PAYMENTSTATUS
     *
     * @return the value of GE_PROPOSAL_MAIN.PAYMENTSTATUS
     *
     * @mbggenerated
     */
    public String getPaymentstatus() {
        return paymentstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.PAYMENTSTATUS
     *
     * @param paymentstatus the value for GE_PROPOSAL_MAIN.PAYMENTSTATUS
     *
     * @mbggenerated
     */
    public void setPaymentstatus(String paymentstatus) {
        this.paymentstatus = paymentstatus == null ? null : paymentstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.BUSINESSSOURCE
     *
     * @return the value of GE_PROPOSAL_MAIN.BUSINESSSOURCE
     *
     * @mbggenerated
     */
    public String getBusinesssource() {
        return businesssource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.BUSINESSSOURCE
     *
     * @param businesssource the value for GE_PROPOSAL_MAIN.BUSINESSSOURCE
     *
     * @mbggenerated
     */
    public void setBusinesssource(String businesssource) {
        this.businesssource = businesssource == null ? null : businesssource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.GROUPCHANNEL
     *
     * @return the value of GE_PROPOSAL_MAIN.GROUPCHANNEL
     *
     * @mbggenerated
     */
    public String getGroupchannel() {
        return groupchannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.GROUPCHANNEL
     *
     * @param groupchannel the value for GE_PROPOSAL_MAIN.GROUPCHANNEL
     *
     * @mbggenerated
     */
    public void setGroupchannel(String groupchannel) {
        this.groupchannel = groupchannel == null ? null : groupchannel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.HXSUMPREMIUM
     *
     * @return the value of GE_PROPOSAL_MAIN.HXSUMPREMIUM
     *
     * @mbggenerated
     */
    public BigDecimal getHxsumpremium() {
        return hxsumpremium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.HXSUMPREMIUM
     *
     * @param hxsumpremium the value for GE_PROPOSAL_MAIN.HXSUMPREMIUM
     *
     * @mbggenerated
     */
    public void setHxsumpremium(BigDecimal hxsumpremium) {
        this.hxsumpremium = hxsumpremium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.HXSTATUS
     *
     * @return the value of GE_PROPOSAL_MAIN.HXSTATUS
     *
     * @mbggenerated
     */
    public String getHxstatus() {
        return hxstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.HXSTATUS
     *
     * @param hxstatus the value for GE_PROPOSAL_MAIN.HXSTATUS
     *
     * @mbggenerated
     */
    public void setHxstatus(String hxstatus) {
        this.hxstatus = hxstatus == null ? null : hxstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.HXPOLICYSTATUS
     *
     * @return the value of GE_PROPOSAL_MAIN.HXPOLICYSTATUS
     *
     * @mbggenerated
     */
    public String getHxpolicystatus() {
        return hxpolicystatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.HXPOLICYSTATUS
     *
     * @param hxpolicystatus the value for GE_PROPOSAL_MAIN.HXPOLICYSTATUS
     *
     * @mbggenerated
     */
    public void setHxpolicystatus(String hxpolicystatus) {
        this.hxpolicystatus = hxpolicystatus == null ? null : hxpolicystatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.SESSIONID
     *
     * @return the value of GE_PROPOSAL_MAIN.SESSIONID
     *
     * @mbggenerated
     */
    public String getSessionid() {
        return sessionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.SESSIONID
     *
     * @param sessionid the value for GE_PROPOSAL_MAIN.SESSIONID
     *
     * @mbggenerated
     */
    public void setSessionid(String sessionid) {
        this.sessionid = sessionid == null ? null : sessionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.TBITEMID
     *
     * @return the value of GE_PROPOSAL_MAIN.TBITEMID
     *
     * @mbggenerated
     */
    public String getTbitemid() {
        return tbitemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.TBITEMID
     *
     * @param tbitemid the value for GE_PROPOSAL_MAIN.TBITEMID
     *
     * @mbggenerated
     */
    public void setTbitemid(String tbitemid) {
        this.tbitemid = tbitemid == null ? null : tbitemid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.TBSUBORDERID
     *
     * @return the value of GE_PROPOSAL_MAIN.TBSUBORDERID
     *
     * @mbggenerated
     */
    public String getTbsuborderid() {
        return tbsuborderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.TBSUBORDERID
     *
     * @param tbsuborderid the value for GE_PROPOSAL_MAIN.TBSUBORDERID
     *
     * @mbggenerated
     */
    public void setTbsuborderid(String tbsuborderid) {
        this.tbsuborderid = tbsuborderid == null ? null : tbsuborderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.ITEMID
     *
     * @return the value of GE_PROPOSAL_MAIN.ITEMID
     *
     * @mbggenerated
     */
    public String getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.ITEMID
     *
     * @param itemid the value for GE_PROPOSAL_MAIN.ITEMID
     *
     * @mbggenerated
     */
    public void setItemid(String itemid) {
        this.itemid = itemid == null ? null : itemid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.TBORDERID
     *
     * @return the value of GE_PROPOSAL_MAIN.TBORDERID
     *
     * @mbggenerated
     */
    public String getTborderid() {
        return tborderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.TBORDERID
     *
     * @param tborderid the value for GE_PROPOSAL_MAIN.TBORDERID
     *
     * @mbggenerated
     */
    public void setTborderid(String tborderid) {
        this.tborderid = tborderid == null ? null : tborderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.COMMUNICATIONMODE
     *
     * @return the value of GE_PROPOSAL_MAIN.COMMUNICATIONMODE
     *
     * @mbggenerated
     */
    public String getCommunicationmode() {
        return communicationmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.COMMUNICATIONMODE
     *
     * @param communicationmode the value for GE_PROPOSAL_MAIN.COMMUNICATIONMODE
     *
     * @mbggenerated
     */
    public void setCommunicationmode(String communicationmode) {
        this.communicationmode = communicationmode == null ? null : communicationmode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.APPTIME
     *
     * @return the value of GE_PROPOSAL_MAIN.APPTIME
     *
     * @mbggenerated
     */
    public String getApptime() {
        return apptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.APPTIME
     *
     * @param apptime the value for GE_PROPOSAL_MAIN.APPTIME
     *
     * @mbggenerated
     */
    public void setApptime(String apptime) {
        this.apptime = apptime == null ? null : apptime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.ZHREFERENCECODE
     *
     * @return the value of GE_PROPOSAL_MAIN.ZHREFERENCECODE
     *
     * @mbggenerated
     */
    public String getZhreferencecode() {
        return zhreferencecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.ZHREFERENCECODE
     *
     * @param zhreferencecode the value for GE_PROPOSAL_MAIN.ZHREFERENCECODE
     *
     * @mbggenerated
     */
    public void setZhreferencecode(String zhreferencecode) {
        this.zhreferencecode = zhreferencecode == null ? null : zhreferencecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.SALETYPE
     *
     * @return the value of GE_PROPOSAL_MAIN.SALETYPE
     *
     * @mbggenerated
     */
    public String getSaletype() {
        return saletype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.SALETYPE
     *
     * @param saletype the value for GE_PROPOSAL_MAIN.SALETYPE
     *
     * @mbggenerated
     */
    public void setSaletype(String saletype) {
        this.saletype = saletype == null ? null : saletype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.SOCIATYPAYMENTNO
     *
     * @return the value of GE_PROPOSAL_MAIN.SOCIATYPAYMENTNO
     *
     * @mbggenerated
     */
    public String getSociatypaymentno() {
        return sociatypaymentno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.SOCIATYPAYMENTNO
     *
     * @param sociatypaymentno the value for GE_PROPOSAL_MAIN.SOCIATYPAYMENTNO
     *
     * @mbggenerated
     */
    public void setSociatypaymentno(String sociatypaymentno) {
        this.sociatypaymentno = sociatypaymentno == null ? null : sociatypaymentno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.REFERRALCODE
     *
     * @return the value of GE_PROPOSAL_MAIN.REFERRALCODE
     *
     * @mbggenerated
     */
    public String getReferralcode() {
        return referralcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.REFERRALCODE
     *
     * @param referralcode the value for GE_PROPOSAL_MAIN.REFERRALCODE
     *
     * @mbggenerated
     */
    public void setReferralcode(String referralcode) {
        this.referralcode = referralcode == null ? null : referralcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.ORDERNO
     *
     * @return the value of GE_PROPOSAL_MAIN.ORDERNO
     *
     * @mbggenerated
     */
    public String getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.ORDERNO
     *
     * @param orderno the value for GE_PROPOSAL_MAIN.ORDERNO
     *
     * @mbggenerated
     */
    public void setOrderno(String orderno) {
        this.orderno = orderno == null ? null : orderno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.OPENID
     *
     * @return the value of GE_PROPOSAL_MAIN.OPENID
     *
     * @mbggenerated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.OPENID
     *
     * @param openid the value for GE_PROPOSAL_MAIN.OPENID
     *
     * @mbggenerated
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.SALESMANID
     *
     * @return the value of GE_PROPOSAL_MAIN.SALESMANID
     *
     * @mbggenerated
     */
    public String getSalesmanid() {
        return salesmanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.SALESMANID
     *
     * @param salesmanid the value for GE_PROPOSAL_MAIN.SALESMANID
     *
     * @mbggenerated
     */
    public void setSalesmanid(String salesmanid) {
        this.salesmanid = salesmanid == null ? null : salesmanid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.SALESMANCHANNEL
     *
     * @return the value of GE_PROPOSAL_MAIN.SALESMANCHANNEL
     *
     * @mbggenerated
     */
    public String getSalesmanchannel() {
        return salesmanchannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.SALESMANCHANNEL
     *
     * @param salesmanchannel the value for GE_PROPOSAL_MAIN.SALESMANCHANNEL
     *
     * @mbggenerated
     */
    public void setSalesmanchannel(String salesmanchannel) {
        this.salesmanchannel = salesmanchannel == null ? null : salesmanchannel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.SALESMANTYPE
     *
     * @return the value of GE_PROPOSAL_MAIN.SALESMANTYPE
     *
     * @mbggenerated
     */
    public String getSalesmantype() {
        return salesmantype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.SALESMANTYPE
     *
     * @param salesmantype the value for GE_PROPOSAL_MAIN.SALESMANTYPE
     *
     * @mbggenerated
     */
    public void setSalesmantype(String salesmantype) {
        this.salesmantype = salesmantype == null ? null : salesmantype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.MOBILEIMEI
     *
     * @return the value of GE_PROPOSAL_MAIN.MOBILEIMEI
     *
     * @mbggenerated
     */
    public String getMobileimei() {
        return mobileimei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.MOBILEIMEI
     *
     * @param mobileimei the value for GE_PROPOSAL_MAIN.MOBILEIMEI
     *
     * @mbggenerated
     */
    public void setMobileimei(String mobileimei) {
        this.mobileimei = mobileimei == null ? null : mobileimei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.MAINTENANCE
     *
     * @return the value of GE_PROPOSAL_MAIN.MAINTENANCE
     *
     * @mbggenerated
     */
    public Short getMaintenance() {
        return maintenance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.MAINTENANCE
     *
     * @param maintenance the value for GE_PROPOSAL_MAIN.MAINTENANCE
     *
     * @mbggenerated
     */
    public void setMaintenance(Short maintenance) {
        this.maintenance = maintenance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.MOBILEBRAND
     *
     * @return the value of GE_PROPOSAL_MAIN.MOBILEBRAND
     *
     * @mbggenerated
     */
    public String getMobilebrand() {
        return mobilebrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.MOBILEBRAND
     *
     * @param mobilebrand the value for GE_PROPOSAL_MAIN.MOBILEBRAND
     *
     * @mbggenerated
     */
    public void setMobilebrand(String mobilebrand) {
        this.mobilebrand = mobilebrand == null ? null : mobilebrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.MOBILEMODEL
     *
     * @return the value of GE_PROPOSAL_MAIN.MOBILEMODEL
     *
     * @mbggenerated
     */
    public String getMobilemodel() {
        return mobilemodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.MOBILEMODEL
     *
     * @param mobilemodel the value for GE_PROPOSAL_MAIN.MOBILEMODEL
     *
     * @mbggenerated
     */
    public void setMobilemodel(String mobilemodel) {
        this.mobilemodel = mobilemodel == null ? null : mobilemodel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.ISCLAIMS
     *
     * @return the value of GE_PROPOSAL_MAIN.ISCLAIMS
     *
     * @mbggenerated
     */
    public String getIsclaims() {
        return isclaims;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.ISCLAIMS
     *
     * @param isclaims the value for GE_PROPOSAL_MAIN.ISCLAIMS
     *
     * @mbggenerated
     */
    public void setIsclaims(String isclaims) {
        this.isclaims = isclaims == null ? null : isclaims.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.CLAIMSTIME
     *
     * @return the value of GE_PROPOSAL_MAIN.CLAIMSTIME
     *
     * @mbggenerated
     */
    public Date getClaimstime() {
        return claimstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.CLAIMSTIME
     *
     * @param claimstime the value for GE_PROPOSAL_MAIN.CLAIMSTIME
     *
     * @mbggenerated
     */
    public void setClaimstime(Date claimstime) {
        this.claimstime = claimstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.RECEIVEAGE
     *
     * @return the value of GE_PROPOSAL_MAIN.RECEIVEAGE
     *
     * @mbggenerated
     */
    public String getReceiveage() {
        return receiveage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.RECEIVEAGE
     *
     * @param receiveage the value for GE_PROPOSAL_MAIN.RECEIVEAGE
     *
     * @mbggenerated
     */
    public void setReceiveage(String receiveage) {
        this.receiveage = receiveage == null ? null : receiveage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.PAYTIME
     *
     * @return the value of GE_PROPOSAL_MAIN.PAYTIME
     *
     * @mbggenerated
     */
    public String getPaytime() {
        return paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.PAYTIME
     *
     * @param paytime the value for GE_PROPOSAL_MAIN.PAYTIME
     *
     * @mbggenerated
     */
    public void setPaytime(String paytime) {
        this.paytime = paytime == null ? null : paytime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.LOANPREMIUM
     *
     * @return the value of GE_PROPOSAL_MAIN.LOANPREMIUM
     *
     * @mbggenerated
     */
    public BigDecimal getLoanpremium() {
        return loanpremium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.LOANPREMIUM
     *
     * @param loanpremium the value for GE_PROPOSAL_MAIN.LOANPREMIUM
     *
     * @mbggenerated
     */
    public void setLoanpremium(BigDecimal loanpremium) {
        this.loanpremium = loanpremium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.LOANSTARTTIME
     *
     * @return the value of GE_PROPOSAL_MAIN.LOANSTARTTIME
     *
     * @mbggenerated
     */
    public Date getLoanstarttime() {
        return loanstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.LOANSTARTTIME
     *
     * @param loanstarttime the value for GE_PROPOSAL_MAIN.LOANSTARTTIME
     *
     * @mbggenerated
     */
    public void setLoanstarttime(Date loanstarttime) {
        this.loanstarttime = loanstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.LOANENDTIME
     *
     * @return the value of GE_PROPOSAL_MAIN.LOANENDTIME
     *
     * @mbggenerated
     */
    public Date getLoanendtime() {
        return loanendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.LOANENDTIME
     *
     * @param loanendtime the value for GE_PROPOSAL_MAIN.LOANENDTIME
     *
     * @mbggenerated
     */
    public void setLoanendtime(Date loanendtime) {
        this.loanendtime = loanendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.SURRENDERSTATUS
     *
     * @return the value of GE_PROPOSAL_MAIN.SURRENDERSTATUS
     *
     * @mbggenerated
     */
    public String getSurrenderstatus() {
        return surrenderstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.SURRENDERSTATUS
     *
     * @param surrenderstatus the value for GE_PROPOSAL_MAIN.SURRENDERSTATUS
     *
     * @mbggenerated
     */
    public void setSurrenderstatus(String surrenderstatus) {
        this.surrenderstatus = surrenderstatus == null ? null : surrenderstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.SURRENDERTIME
     *
     * @return the value of GE_PROPOSAL_MAIN.SURRENDERTIME
     *
     * @mbggenerated
     */
    public Date getSurrendertime() {
        return surrendertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.SURRENDERTIME
     *
     * @param surrendertime the value for GE_PROPOSAL_MAIN.SURRENDERTIME
     *
     * @mbggenerated
     */
    public void setSurrendertime(Date surrendertime) {
        this.surrendertime = surrendertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.SURRENDERUPDATEDATE
     *
     * @return the value of GE_PROPOSAL_MAIN.SURRENDERUPDATEDATE
     *
     * @mbggenerated
     */
    public Date getSurrenderupdatedate() {
        return surrenderupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.SURRENDERUPDATEDATE
     *
     * @param surrenderupdatedate the value for GE_PROPOSAL_MAIN.SURRENDERUPDATEDATE
     *
     * @mbggenerated
     */
    public void setSurrenderupdatedate(Date surrenderupdatedate) {
        this.surrenderupdatedate = surrenderupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.SURRENDERUPDATETIME
     *
     * @return the value of GE_PROPOSAL_MAIN.SURRENDERUPDATETIME
     *
     * @mbggenerated
     */
    public Date getSurrenderupdatetime() {
        return surrenderupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.SURRENDERUPDATETIME
     *
     * @param surrenderupdatetime the value for GE_PROPOSAL_MAIN.SURRENDERUPDATETIME
     *
     * @mbggenerated
     */
    public void setSurrenderupdatetime(Date surrenderupdatetime) {
        this.surrenderupdatetime = surrenderupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.SURRENDERMSG
     *
     * @return the value of GE_PROPOSAL_MAIN.SURRENDERMSG
     *
     * @mbggenerated
     */
    public String getSurrendermsg() {
        return surrendermsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.SURRENDERMSG
     *
     * @param surrendermsg the value for GE_PROPOSAL_MAIN.SURRENDERMSG
     *
     * @mbggenerated
     */
    public void setSurrendermsg(String surrendermsg) {
        this.surrendermsg = surrendermsg == null ? null : surrendermsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_PROPOSAL_MAIN.REQUESTEDTIME
     *
     * @return the value of GE_PROPOSAL_MAIN.REQUESTEDTIME
     *
     * @mbggenerated
     */
    public Date getRequestedtime() {
        return requestedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_PROPOSAL_MAIN.REQUESTEDTIME
     *
     * @param requestedtime the value for GE_PROPOSAL_MAIN.REQUESTEDTIME
     *
     * @mbggenerated
     */
    public void setRequestedtime(Date requestedtime) {
        this.requestedtime = requestedtime;
    }
}