package com.future.dao4ora.po;

public class GeQuotePartyKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_QUOTE_PARTY.QUOTENO
     *
     * @mbggenerated
     */
    private String quoteno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_QUOTE_PARTY.SERIALNO
     *
     * @mbggenerated
     */
    private String serialno;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GE_QUOTE_PARTY
     *
     * @mbggenerated
     */
    public GeQuotePartyKey(String quoteno, String serialno) {
        this.quoteno = quoteno;
        this.serialno = serialno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GE_QUOTE_PARTY
     *
     * @mbggenerated
     */
    public GeQuotePartyKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_QUOTE_PARTY.QUOTENO
     *
     * @return the value of GE_QUOTE_PARTY.QUOTENO
     *
     * @mbggenerated
     */
    public String getQuoteno() {
        return quoteno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_QUOTE_PARTY.QUOTENO
     *
     * @param quoteno the value for GE_QUOTE_PARTY.QUOTENO
     *
     * @mbggenerated
     */
    public void setQuoteno(String quoteno) {
        this.quoteno = quoteno == null ? null : quoteno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_QUOTE_PARTY.SERIALNO
     *
     * @return the value of GE_QUOTE_PARTY.SERIALNO
     *
     * @mbggenerated
     */
    public String getSerialno() {
        return serialno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_QUOTE_PARTY.SERIALNO
     *
     * @param serialno the value for GE_QUOTE_PARTY.SERIALNO
     *
     * @mbggenerated
     */
    public void setSerialno(String serialno) {
        this.serialno = serialno == null ? null : serialno.trim();
    }
}