package com.future.dao.po;

import java.math.BigDecimal;
import java.util.Date;

public class GeAirorder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_AIRORDER.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_AIRORDER.AIRORDERID
     *
     * @mbggenerated
     */
    private String airorderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_AIRORDER.AIRCOMNAME
     *
     * @mbggenerated
     */
    private String aircomname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_AIRORDER.FLIGHTNO
     *
     * @mbggenerated
     */
    private String flightno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_AIRORDER.AIRTAKEOFF
     *
     * @mbggenerated
     */
    private Date airtakeoff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_AIRORDER.AIRLANDING
     *
     * @mbggenerated
     */
    private Date airlanding;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_AIRORDER.AIRORDERSTART
     *
     * @mbggenerated
     */
    private String airorderstart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_AIRORDER.AIRORDEREND
     *
     * @mbggenerated
     */
    private String airorderend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_AIRORDER.TICKETNO
     *
     * @mbggenerated
     */
    private String ticketno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_AIRORDER.ISREQUIREINVOICE
     *
     * @mbggenerated
     */
    private String isrequireinvoice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_AIRORDER.PROVINCE
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_AIRORDER.CITY
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_AIRORDER.AREA
     *
     * @mbggenerated
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_AIRORDER.DETAILADDRESS
     *
     * @mbggenerated
     */
    private String detailaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_AIRORDER.MOBILE
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_AIRORDER.TEL
     *
     * @mbggenerated
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_AIRORDER.ZIP
     *
     * @mbggenerated
     */
    private String zip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_AIRORDER.PROPOSALNO
     *
     * @mbggenerated
     */
    private String proposalno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_AIRORDER.ENDORSENO
     *
     * @mbggenerated
     */
    private String endorseno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_AIRORDER.POLICYNO
     *
     * @mbggenerated
     */
    private String policyno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_AIRORDER.ENDORSEFROM
     *
     * @mbggenerated
     */
    private String endorsefrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_AIRORDER.FEE
     *
     * @mbggenerated
     */
    private BigDecimal fee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_AIRORDER.ENDORSEFINISHTIME
     *
     * @mbggenerated
     */
    private Date endorsefinishtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_AIRORDER.OUTPOLICYNO
     *
     * @mbggenerated
     */
    private String outpolicyno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_AIRORDER.OUTBIZNO
     *
     * @mbggenerated
     */
    private String outbizno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_AIRORDER.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_AIRORDER.INSUREDCOPIES
     *
     * @mbggenerated
     */
    private String insuredcopies;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_AIRORDER.BIZORDERID
     *
     * @mbggenerated
     */
    private String bizorderid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GE_AIRORDER
     *
     * @mbggenerated
     */
    public GeAirorder(String id, String airorderid, String aircomname, String flightno, Date airtakeoff, Date airlanding, String airorderstart, String airorderend, String ticketno, String isrequireinvoice, String province, String city, String area, String detailaddress, String mobile, String tel, String zip, String proposalno, String endorseno, String policyno, String endorsefrom, BigDecimal fee, Date endorsefinishtime, String outpolicyno, String outbizno, String status, String insuredcopies, String bizorderid) {
        this.id = id;
        this.airorderid = airorderid;
        this.aircomname = aircomname;
        this.flightno = flightno;
        this.airtakeoff = airtakeoff;
        this.airlanding = airlanding;
        this.airorderstart = airorderstart;
        this.airorderend = airorderend;
        this.ticketno = ticketno;
        this.isrequireinvoice = isrequireinvoice;
        this.province = province;
        this.city = city;
        this.area = area;
        this.detailaddress = detailaddress;
        this.mobile = mobile;
        this.tel = tel;
        this.zip = zip;
        this.proposalno = proposalno;
        this.endorseno = endorseno;
        this.policyno = policyno;
        this.endorsefrom = endorsefrom;
        this.fee = fee;
        this.endorsefinishtime = endorsefinishtime;
        this.outpolicyno = outpolicyno;
        this.outbizno = outbizno;
        this.status = status;
        this.insuredcopies = insuredcopies;
        this.bizorderid = bizorderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GE_AIRORDER
     *
     * @mbggenerated
     */
    public GeAirorder() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_AIRORDER.ID
     *
     * @return the value of GE_AIRORDER.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_AIRORDER.ID
     *
     * @param id the value for GE_AIRORDER.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_AIRORDER.AIRORDERID
     *
     * @return the value of GE_AIRORDER.AIRORDERID
     *
     * @mbggenerated
     */
    public String getAirorderid() {
        return airorderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_AIRORDER.AIRORDERID
     *
     * @param airorderid the value for GE_AIRORDER.AIRORDERID
     *
     * @mbggenerated
     */
    public void setAirorderid(String airorderid) {
        this.airorderid = airorderid == null ? null : airorderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_AIRORDER.AIRCOMNAME
     *
     * @return the value of GE_AIRORDER.AIRCOMNAME
     *
     * @mbggenerated
     */
    public String getAircomname() {
        return aircomname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_AIRORDER.AIRCOMNAME
     *
     * @param aircomname the value for GE_AIRORDER.AIRCOMNAME
     *
     * @mbggenerated
     */
    public void setAircomname(String aircomname) {
        this.aircomname = aircomname == null ? null : aircomname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_AIRORDER.FLIGHTNO
     *
     * @return the value of GE_AIRORDER.FLIGHTNO
     *
     * @mbggenerated
     */
    public String getFlightno() {
        return flightno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_AIRORDER.FLIGHTNO
     *
     * @param flightno the value for GE_AIRORDER.FLIGHTNO
     *
     * @mbggenerated
     */
    public void setFlightno(String flightno) {
        this.flightno = flightno == null ? null : flightno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_AIRORDER.AIRTAKEOFF
     *
     * @return the value of GE_AIRORDER.AIRTAKEOFF
     *
     * @mbggenerated
     */
    public Date getAirtakeoff() {
        return airtakeoff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_AIRORDER.AIRTAKEOFF
     *
     * @param airtakeoff the value for GE_AIRORDER.AIRTAKEOFF
     *
     * @mbggenerated
     */
    public void setAirtakeoff(Date airtakeoff) {
        this.airtakeoff = airtakeoff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_AIRORDER.AIRLANDING
     *
     * @return the value of GE_AIRORDER.AIRLANDING
     *
     * @mbggenerated
     */
    public Date getAirlanding() {
        return airlanding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_AIRORDER.AIRLANDING
     *
     * @param airlanding the value for GE_AIRORDER.AIRLANDING
     *
     * @mbggenerated
     */
    public void setAirlanding(Date airlanding) {
        this.airlanding = airlanding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_AIRORDER.AIRORDERSTART
     *
     * @return the value of GE_AIRORDER.AIRORDERSTART
     *
     * @mbggenerated
     */
    public String getAirorderstart() {
        return airorderstart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_AIRORDER.AIRORDERSTART
     *
     * @param airorderstart the value for GE_AIRORDER.AIRORDERSTART
     *
     * @mbggenerated
     */
    public void setAirorderstart(String airorderstart) {
        this.airorderstart = airorderstart == null ? null : airorderstart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_AIRORDER.AIRORDEREND
     *
     * @return the value of GE_AIRORDER.AIRORDEREND
     *
     * @mbggenerated
     */
    public String getAirorderend() {
        return airorderend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_AIRORDER.AIRORDEREND
     *
     * @param airorderend the value for GE_AIRORDER.AIRORDEREND
     *
     * @mbggenerated
     */
    public void setAirorderend(String airorderend) {
        this.airorderend = airorderend == null ? null : airorderend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_AIRORDER.TICKETNO
     *
     * @return the value of GE_AIRORDER.TICKETNO
     *
     * @mbggenerated
     */
    public String getTicketno() {
        return ticketno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_AIRORDER.TICKETNO
     *
     * @param ticketno the value for GE_AIRORDER.TICKETNO
     *
     * @mbggenerated
     */
    public void setTicketno(String ticketno) {
        this.ticketno = ticketno == null ? null : ticketno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_AIRORDER.ISREQUIREINVOICE
     *
     * @return the value of GE_AIRORDER.ISREQUIREINVOICE
     *
     * @mbggenerated
     */
    public String getIsrequireinvoice() {
        return isrequireinvoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_AIRORDER.ISREQUIREINVOICE
     *
     * @param isrequireinvoice the value for GE_AIRORDER.ISREQUIREINVOICE
     *
     * @mbggenerated
     */
    public void setIsrequireinvoice(String isrequireinvoice) {
        this.isrequireinvoice = isrequireinvoice == null ? null : isrequireinvoice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_AIRORDER.PROVINCE
     *
     * @return the value of GE_AIRORDER.PROVINCE
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_AIRORDER.PROVINCE
     *
     * @param province the value for GE_AIRORDER.PROVINCE
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_AIRORDER.CITY
     *
     * @return the value of GE_AIRORDER.CITY
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_AIRORDER.CITY
     *
     * @param city the value for GE_AIRORDER.CITY
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_AIRORDER.AREA
     *
     * @return the value of GE_AIRORDER.AREA
     *
     * @mbggenerated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_AIRORDER.AREA
     *
     * @param area the value for GE_AIRORDER.AREA
     *
     * @mbggenerated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_AIRORDER.DETAILADDRESS
     *
     * @return the value of GE_AIRORDER.DETAILADDRESS
     *
     * @mbggenerated
     */
    public String getDetailaddress() {
        return detailaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_AIRORDER.DETAILADDRESS
     *
     * @param detailaddress the value for GE_AIRORDER.DETAILADDRESS
     *
     * @mbggenerated
     */
    public void setDetailaddress(String detailaddress) {
        this.detailaddress = detailaddress == null ? null : detailaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_AIRORDER.MOBILE
     *
     * @return the value of GE_AIRORDER.MOBILE
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_AIRORDER.MOBILE
     *
     * @param mobile the value for GE_AIRORDER.MOBILE
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_AIRORDER.TEL
     *
     * @return the value of GE_AIRORDER.TEL
     *
     * @mbggenerated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_AIRORDER.TEL
     *
     * @param tel the value for GE_AIRORDER.TEL
     *
     * @mbggenerated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_AIRORDER.ZIP
     *
     * @return the value of GE_AIRORDER.ZIP
     *
     * @mbggenerated
     */
    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_AIRORDER.ZIP
     *
     * @param zip the value for GE_AIRORDER.ZIP
     *
     * @mbggenerated
     */
    public void setZip(String zip) {
        this.zip = zip == null ? null : zip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_AIRORDER.PROPOSALNO
     *
     * @return the value of GE_AIRORDER.PROPOSALNO
     *
     * @mbggenerated
     */
    public String getProposalno() {
        return proposalno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_AIRORDER.PROPOSALNO
     *
     * @param proposalno the value for GE_AIRORDER.PROPOSALNO
     *
     * @mbggenerated
     */
    public void setProposalno(String proposalno) {
        this.proposalno = proposalno == null ? null : proposalno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_AIRORDER.ENDORSENO
     *
     * @return the value of GE_AIRORDER.ENDORSENO
     *
     * @mbggenerated
     */
    public String getEndorseno() {
        return endorseno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_AIRORDER.ENDORSENO
     *
     * @param endorseno the value for GE_AIRORDER.ENDORSENO
     *
     * @mbggenerated
     */
    public void setEndorseno(String endorseno) {
        this.endorseno = endorseno == null ? null : endorseno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_AIRORDER.POLICYNO
     *
     * @return the value of GE_AIRORDER.POLICYNO
     *
     * @mbggenerated
     */
    public String getPolicyno() {
        return policyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_AIRORDER.POLICYNO
     *
     * @param policyno the value for GE_AIRORDER.POLICYNO
     *
     * @mbggenerated
     */
    public void setPolicyno(String policyno) {
        this.policyno = policyno == null ? null : policyno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_AIRORDER.ENDORSEFROM
     *
     * @return the value of GE_AIRORDER.ENDORSEFROM
     *
     * @mbggenerated
     */
    public String getEndorsefrom() {
        return endorsefrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_AIRORDER.ENDORSEFROM
     *
     * @param endorsefrom the value for GE_AIRORDER.ENDORSEFROM
     *
     * @mbggenerated
     */
    public void setEndorsefrom(String endorsefrom) {
        this.endorsefrom = endorsefrom == null ? null : endorsefrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_AIRORDER.FEE
     *
     * @return the value of GE_AIRORDER.FEE
     *
     * @mbggenerated
     */
    public BigDecimal getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_AIRORDER.FEE
     *
     * @param fee the value for GE_AIRORDER.FEE
     *
     * @mbggenerated
     */
    public void setFee(BigDecimal fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_AIRORDER.ENDORSEFINISHTIME
     *
     * @return the value of GE_AIRORDER.ENDORSEFINISHTIME
     *
     * @mbggenerated
     */
    public Date getEndorsefinishtime() {
        return endorsefinishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_AIRORDER.ENDORSEFINISHTIME
     *
     * @param endorsefinishtime the value for GE_AIRORDER.ENDORSEFINISHTIME
     *
     * @mbggenerated
     */
    public void setEndorsefinishtime(Date endorsefinishtime) {
        this.endorsefinishtime = endorsefinishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_AIRORDER.OUTPOLICYNO
     *
     * @return the value of GE_AIRORDER.OUTPOLICYNO
     *
     * @mbggenerated
     */
    public String getOutpolicyno() {
        return outpolicyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_AIRORDER.OUTPOLICYNO
     *
     * @param outpolicyno the value for GE_AIRORDER.OUTPOLICYNO
     *
     * @mbggenerated
     */
    public void setOutpolicyno(String outpolicyno) {
        this.outpolicyno = outpolicyno == null ? null : outpolicyno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_AIRORDER.OUTBIZNO
     *
     * @return the value of GE_AIRORDER.OUTBIZNO
     *
     * @mbggenerated
     */
    public String getOutbizno() {
        return outbizno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_AIRORDER.OUTBIZNO
     *
     * @param outbizno the value for GE_AIRORDER.OUTBIZNO
     *
     * @mbggenerated
     */
    public void setOutbizno(String outbizno) {
        this.outbizno = outbizno == null ? null : outbizno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_AIRORDER.STATUS
     *
     * @return the value of GE_AIRORDER.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_AIRORDER.STATUS
     *
     * @param status the value for GE_AIRORDER.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_AIRORDER.INSUREDCOPIES
     *
     * @return the value of GE_AIRORDER.INSUREDCOPIES
     *
     * @mbggenerated
     */
    public String getInsuredcopies() {
        return insuredcopies;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_AIRORDER.INSUREDCOPIES
     *
     * @param insuredcopies the value for GE_AIRORDER.INSUREDCOPIES
     *
     * @mbggenerated
     */
    public void setInsuredcopies(String insuredcopies) {
        this.insuredcopies = insuredcopies == null ? null : insuredcopies.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_AIRORDER.BIZORDERID
     *
     * @return the value of GE_AIRORDER.BIZORDERID
     *
     * @mbggenerated
     */
    public String getBizorderid() {
        return bizorderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_AIRORDER.BIZORDERID
     *
     * @param bizorderid the value for GE_AIRORDER.BIZORDERID
     *
     * @mbggenerated
     */
    public void setBizorderid(String bizorderid) {
        this.bizorderid = bizorderid == null ? null : bizorderid.trim();
    }
}