package com.future.dao.po;

import java.util.Date;

public class GeFlycuaAir {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_FLYCUA_AIR.FLYCUAID
     *
     * @mbggenerated
     */
    private String flycuaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_FLYCUA_AIR.POLICYNO
     *
     * @mbggenerated
     */
    private String policyno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_FLYCUA_AIR.PROPOSALNO
     *
     * @mbggenerated
     */
    private String proposalno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_FLYCUA_AIR.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_FLYCUA_AIR.REASON
     *
     * @mbggenerated
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_FLYCUA_AIR.MAKEDATE
     *
     * @mbggenerated
     */
    private Date makedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_FLYCUA_AIR.MODIFYDATE
     *
     * @mbggenerated
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_FLYCUA_AIR.NUM
     *
     * @mbggenerated
     */
    private Short num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_FLYCUA_AIR.RETURNCODE
     *
     * @mbggenerated
     */
    private String returncode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_FLYCUA_AIR.ITEMID
     *
     * @mbggenerated
     */
    private String itemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_FLYCUA_AIR.TICKETNO
     *
     * @mbggenerated
     */
    private String ticketno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_FLYCUA_AIR.FLIGHTNO
     *
     * @mbggenerated
     */
    private String flightno;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GE_FLYCUA_AIR
     *
     * @mbggenerated
     */
    public GeFlycuaAir(String flycuaid, String policyno, String proposalno, String status, String reason, Date makedate, Date modifydate, Short num, String returncode, String itemid, String ticketno, String flightno) {
        this.flycuaid = flycuaid;
        this.policyno = policyno;
        this.proposalno = proposalno;
        this.status = status;
        this.reason = reason;
        this.makedate = makedate;
        this.modifydate = modifydate;
        this.num = num;
        this.returncode = returncode;
        this.itemid = itemid;
        this.ticketno = ticketno;
        this.flightno = flightno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GE_FLYCUA_AIR
     *
     * @mbggenerated
     */
    public GeFlycuaAir() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_FLYCUA_AIR.FLYCUAID
     *
     * @return the value of GE_FLYCUA_AIR.FLYCUAID
     *
     * @mbggenerated
     */
    public String getFlycuaid() {
        return flycuaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_FLYCUA_AIR.FLYCUAID
     *
     * @param flycuaid the value for GE_FLYCUA_AIR.FLYCUAID
     *
     * @mbggenerated
     */
    public void setFlycuaid(String flycuaid) {
        this.flycuaid = flycuaid == null ? null : flycuaid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_FLYCUA_AIR.POLICYNO
     *
     * @return the value of GE_FLYCUA_AIR.POLICYNO
     *
     * @mbggenerated
     */
    public String getPolicyno() {
        return policyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_FLYCUA_AIR.POLICYNO
     *
     * @param policyno the value for GE_FLYCUA_AIR.POLICYNO
     *
     * @mbggenerated
     */
    public void setPolicyno(String policyno) {
        this.policyno = policyno == null ? null : policyno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_FLYCUA_AIR.PROPOSALNO
     *
     * @return the value of GE_FLYCUA_AIR.PROPOSALNO
     *
     * @mbggenerated
     */
    public String getProposalno() {
        return proposalno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_FLYCUA_AIR.PROPOSALNO
     *
     * @param proposalno the value for GE_FLYCUA_AIR.PROPOSALNO
     *
     * @mbggenerated
     */
    public void setProposalno(String proposalno) {
        this.proposalno = proposalno == null ? null : proposalno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_FLYCUA_AIR.STATUS
     *
     * @return the value of GE_FLYCUA_AIR.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_FLYCUA_AIR.STATUS
     *
     * @param status the value for GE_FLYCUA_AIR.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_FLYCUA_AIR.REASON
     *
     * @return the value of GE_FLYCUA_AIR.REASON
     *
     * @mbggenerated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_FLYCUA_AIR.REASON
     *
     * @param reason the value for GE_FLYCUA_AIR.REASON
     *
     * @mbggenerated
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_FLYCUA_AIR.MAKEDATE
     *
     * @return the value of GE_FLYCUA_AIR.MAKEDATE
     *
     * @mbggenerated
     */
    public Date getMakedate() {
        return makedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_FLYCUA_AIR.MAKEDATE
     *
     * @param makedate the value for GE_FLYCUA_AIR.MAKEDATE
     *
     * @mbggenerated
     */
    public void setMakedate(Date makedate) {
        this.makedate = makedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_FLYCUA_AIR.MODIFYDATE
     *
     * @return the value of GE_FLYCUA_AIR.MODIFYDATE
     *
     * @mbggenerated
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_FLYCUA_AIR.MODIFYDATE
     *
     * @param modifydate the value for GE_FLYCUA_AIR.MODIFYDATE
     *
     * @mbggenerated
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_FLYCUA_AIR.NUM
     *
     * @return the value of GE_FLYCUA_AIR.NUM
     *
     * @mbggenerated
     */
    public Short getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_FLYCUA_AIR.NUM
     *
     * @param num the value for GE_FLYCUA_AIR.NUM
     *
     * @mbggenerated
     */
    public void setNum(Short num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_FLYCUA_AIR.RETURNCODE
     *
     * @return the value of GE_FLYCUA_AIR.RETURNCODE
     *
     * @mbggenerated
     */
    public String getReturncode() {
        return returncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_FLYCUA_AIR.RETURNCODE
     *
     * @param returncode the value for GE_FLYCUA_AIR.RETURNCODE
     *
     * @mbggenerated
     */
    public void setReturncode(String returncode) {
        this.returncode = returncode == null ? null : returncode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_FLYCUA_AIR.ITEMID
     *
     * @return the value of GE_FLYCUA_AIR.ITEMID
     *
     * @mbggenerated
     */
    public String getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_FLYCUA_AIR.ITEMID
     *
     * @param itemid the value for GE_FLYCUA_AIR.ITEMID
     *
     * @mbggenerated
     */
    public void setItemid(String itemid) {
        this.itemid = itemid == null ? null : itemid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_FLYCUA_AIR.TICKETNO
     *
     * @return the value of GE_FLYCUA_AIR.TICKETNO
     *
     * @mbggenerated
     */
    public String getTicketno() {
        return ticketno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_FLYCUA_AIR.TICKETNO
     *
     * @param ticketno the value for GE_FLYCUA_AIR.TICKETNO
     *
     * @mbggenerated
     */
    public void setTicketno(String ticketno) {
        this.ticketno = ticketno == null ? null : ticketno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_FLYCUA_AIR.FLIGHTNO
     *
     * @return the value of GE_FLYCUA_AIR.FLIGHTNO
     *
     * @mbggenerated
     */
    public String getFlightno() {
        return flightno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_FLYCUA_AIR.FLIGHTNO
     *
     * @param flightno the value for GE_FLYCUA_AIR.FLIGHTNO
     *
     * @mbggenerated
     */
    public void setFlightno(String flightno) {
        this.flightno = flightno == null ? null : flightno.trim();
    }
}