package com.future.dao.po;

import java.util.Date;

public class GeQuoteParty extends GeQuotePartyKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_QUOTE_PARTY.PARTYFLAG
     *
     * @mbggenerated
     */
    private String partyflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_QUOTE_PARTY.PARTYNAME
     *
     * @mbggenerated
     */
    private String partyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_QUOTE_PARTY.GENDER
     *
     * @mbggenerated
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_QUOTE_PARTY.BIRTHDAY
     *
     * @mbggenerated
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_QUOTE_PARTY.IDENTIFYTYPE
     *
     * @mbggenerated
     */
    private String identifytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_QUOTE_PARTY.IDENTIFYNUMBER
     *
     * @mbggenerated
     */
    private String identifynumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_QUOTE_PARTY.ZIPCODE
     *
     * @mbggenerated
     */
    private String zipcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_QUOTE_PARTY.COMPANYPHONE
     *
     * @mbggenerated
     */
    private String companyphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_QUOTE_PARTY.HOMEPHONE
     *
     * @mbggenerated
     */
    private String homephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_QUOTE_PARTY.MOBILE
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_QUOTE_PARTY.EMAIL
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_QUOTE_PARTY.ADDRESS
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_QUOTE_PARTY.OCCUPATION
     *
     * @mbggenerated
     */
    private String occupation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_QUOTE_PARTY.OCCUPATIONTYPE
     *
     * @mbggenerated
     */
    private String occupationtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_QUOTE_PARTY.INSRELATIONAPP
     *
     * @mbggenerated
     */
    private String insrelationapp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_QUOTE_PARTY.INSFLAG
     *
     * @mbggenerated
     */
    private String insflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_QUOTE_PARTY.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_QUOTE_PARTY.FLAG
     *
     * @mbggenerated
     */
    private String flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_QUOTE_PARTY.OCCUPATIONM
     *
     * @mbggenerated
     */
    private String occupationm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_QUOTE_PARTY.OCCUPATIONTYPEM
     *
     * @mbggenerated
     */
    private String occupationtypem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_QUOTE_PARTY.OCCUPATIONS
     *
     * @mbggenerated
     */
    private String occupations;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_QUOTE_PARTY.OCCUPATIONTYPES
     *
     * @mbggenerated
     */
    private String occupationtypes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_QUOTE_PARTY.UNDERWRITEAMOUNT
     *
     * @mbggenerated
     */
    private String underwriteamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_QUOTE_PARTY.DRIVINGLICENCENO
     *
     * @mbggenerated
     */
    private String drivinglicenceno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_QUOTE_PARTY.HOUSEADDRESS
     *
     * @mbggenerated
     */
    private String houseaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_QUOTE_PARTY.HOUSESTRUCTURE
     *
     * @mbggenerated
     */
    private String housestructure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_QUOTE_PARTY.IDEXPDATE
     *
     * @mbggenerated
     */
    private Date idexpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_QUOTE_PARTY.IDSTDATE
     *
     * @mbggenerated
     */
    private Date idstdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GE_QUOTE_PARTY.ENTERPRISENAME
     *
     * @mbggenerated
     */
    private String enterprisename;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GE_QUOTE_PARTY
     *
     * @mbggenerated
     */
    public GeQuoteParty(String quoteno, String serialno, String partyflag, String partyname, String gender, Date birthday, String identifytype, String identifynumber, String zipcode, String companyphone, String homephone, String mobile, String email, String address, String occupation, String occupationtype, String insrelationapp, String insflag, String remark, String flag, String occupationm, String occupationtypem, String occupations, String occupationtypes, String underwriteamount, String drivinglicenceno, String houseaddress, String housestructure, Date idexpdate, Date idstdate, String enterprisename) {
        super(quoteno, serialno);
        this.partyflag = partyflag;
        this.partyname = partyname;
        this.gender = gender;
        this.birthday = birthday;
        this.identifytype = identifytype;
        this.identifynumber = identifynumber;
        this.zipcode = zipcode;
        this.companyphone = companyphone;
        this.homephone = homephone;
        this.mobile = mobile;
        this.email = email;
        this.address = address;
        this.occupation = occupation;
        this.occupationtype = occupationtype;
        this.insrelationapp = insrelationapp;
        this.insflag = insflag;
        this.remark = remark;
        this.flag = flag;
        this.occupationm = occupationm;
        this.occupationtypem = occupationtypem;
        this.occupations = occupations;
        this.occupationtypes = occupationtypes;
        this.underwriteamount = underwriteamount;
        this.drivinglicenceno = drivinglicenceno;
        this.houseaddress = houseaddress;
        this.housestructure = housestructure;
        this.idexpdate = idexpdate;
        this.idstdate = idstdate;
        this.enterprisename = enterprisename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GE_QUOTE_PARTY
     *
     * @mbggenerated
     */
    public GeQuoteParty() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_QUOTE_PARTY.PARTYFLAG
     *
     * @return the value of GE_QUOTE_PARTY.PARTYFLAG
     *
     * @mbggenerated
     */
    public String getPartyflag() {
        return partyflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_QUOTE_PARTY.PARTYFLAG
     *
     * @param partyflag the value for GE_QUOTE_PARTY.PARTYFLAG
     *
     * @mbggenerated
     */
    public void setPartyflag(String partyflag) {
        this.partyflag = partyflag == null ? null : partyflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_QUOTE_PARTY.PARTYNAME
     *
     * @return the value of GE_QUOTE_PARTY.PARTYNAME
     *
     * @mbggenerated
     */
    public String getPartyname() {
        return partyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_QUOTE_PARTY.PARTYNAME
     *
     * @param partyname the value for GE_QUOTE_PARTY.PARTYNAME
     *
     * @mbggenerated
     */
    public void setPartyname(String partyname) {
        this.partyname = partyname == null ? null : partyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_QUOTE_PARTY.GENDER
     *
     * @return the value of GE_QUOTE_PARTY.GENDER
     *
     * @mbggenerated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_QUOTE_PARTY.GENDER
     *
     * @param gender the value for GE_QUOTE_PARTY.GENDER
     *
     * @mbggenerated
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_QUOTE_PARTY.BIRTHDAY
     *
     * @return the value of GE_QUOTE_PARTY.BIRTHDAY
     *
     * @mbggenerated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_QUOTE_PARTY.BIRTHDAY
     *
     * @param birthday the value for GE_QUOTE_PARTY.BIRTHDAY
     *
     * @mbggenerated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_QUOTE_PARTY.IDENTIFYTYPE
     *
     * @return the value of GE_QUOTE_PARTY.IDENTIFYTYPE
     *
     * @mbggenerated
     */
    public String getIdentifytype() {
        return identifytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_QUOTE_PARTY.IDENTIFYTYPE
     *
     * @param identifytype the value for GE_QUOTE_PARTY.IDENTIFYTYPE
     *
     * @mbggenerated
     */
    public void setIdentifytype(String identifytype) {
        this.identifytype = identifytype == null ? null : identifytype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_QUOTE_PARTY.IDENTIFYNUMBER
     *
     * @return the value of GE_QUOTE_PARTY.IDENTIFYNUMBER
     *
     * @mbggenerated
     */
    public String getIdentifynumber() {
        return identifynumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_QUOTE_PARTY.IDENTIFYNUMBER
     *
     * @param identifynumber the value for GE_QUOTE_PARTY.IDENTIFYNUMBER
     *
     * @mbggenerated
     */
    public void setIdentifynumber(String identifynumber) {
        this.identifynumber = identifynumber == null ? null : identifynumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_QUOTE_PARTY.ZIPCODE
     *
     * @return the value of GE_QUOTE_PARTY.ZIPCODE
     *
     * @mbggenerated
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_QUOTE_PARTY.ZIPCODE
     *
     * @param zipcode the value for GE_QUOTE_PARTY.ZIPCODE
     *
     * @mbggenerated
     */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode == null ? null : zipcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_QUOTE_PARTY.COMPANYPHONE
     *
     * @return the value of GE_QUOTE_PARTY.COMPANYPHONE
     *
     * @mbggenerated
     */
    public String getCompanyphone() {
        return companyphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_QUOTE_PARTY.COMPANYPHONE
     *
     * @param companyphone the value for GE_QUOTE_PARTY.COMPANYPHONE
     *
     * @mbggenerated
     */
    public void setCompanyphone(String companyphone) {
        this.companyphone = companyphone == null ? null : companyphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_QUOTE_PARTY.HOMEPHONE
     *
     * @return the value of GE_QUOTE_PARTY.HOMEPHONE
     *
     * @mbggenerated
     */
    public String getHomephone() {
        return homephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_QUOTE_PARTY.HOMEPHONE
     *
     * @param homephone the value for GE_QUOTE_PARTY.HOMEPHONE
     *
     * @mbggenerated
     */
    public void setHomephone(String homephone) {
        this.homephone = homephone == null ? null : homephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_QUOTE_PARTY.MOBILE
     *
     * @return the value of GE_QUOTE_PARTY.MOBILE
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_QUOTE_PARTY.MOBILE
     *
     * @param mobile the value for GE_QUOTE_PARTY.MOBILE
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_QUOTE_PARTY.EMAIL
     *
     * @return the value of GE_QUOTE_PARTY.EMAIL
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_QUOTE_PARTY.EMAIL
     *
     * @param email the value for GE_QUOTE_PARTY.EMAIL
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_QUOTE_PARTY.ADDRESS
     *
     * @return the value of GE_QUOTE_PARTY.ADDRESS
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_QUOTE_PARTY.ADDRESS
     *
     * @param address the value for GE_QUOTE_PARTY.ADDRESS
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_QUOTE_PARTY.OCCUPATION
     *
     * @return the value of GE_QUOTE_PARTY.OCCUPATION
     *
     * @mbggenerated
     */
    public String getOccupation() {
        return occupation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_QUOTE_PARTY.OCCUPATION
     *
     * @param occupation the value for GE_QUOTE_PARTY.OCCUPATION
     *
     * @mbggenerated
     */
    public void setOccupation(String occupation) {
        this.occupation = occupation == null ? null : occupation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_QUOTE_PARTY.OCCUPATIONTYPE
     *
     * @return the value of GE_QUOTE_PARTY.OCCUPATIONTYPE
     *
     * @mbggenerated
     */
    public String getOccupationtype() {
        return occupationtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_QUOTE_PARTY.OCCUPATIONTYPE
     *
     * @param occupationtype the value for GE_QUOTE_PARTY.OCCUPATIONTYPE
     *
     * @mbggenerated
     */
    public void setOccupationtype(String occupationtype) {
        this.occupationtype = occupationtype == null ? null : occupationtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_QUOTE_PARTY.INSRELATIONAPP
     *
     * @return the value of GE_QUOTE_PARTY.INSRELATIONAPP
     *
     * @mbggenerated
     */
    public String getInsrelationapp() {
        return insrelationapp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_QUOTE_PARTY.INSRELATIONAPP
     *
     * @param insrelationapp the value for GE_QUOTE_PARTY.INSRELATIONAPP
     *
     * @mbggenerated
     */
    public void setInsrelationapp(String insrelationapp) {
        this.insrelationapp = insrelationapp == null ? null : insrelationapp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_QUOTE_PARTY.INSFLAG
     *
     * @return the value of GE_QUOTE_PARTY.INSFLAG
     *
     * @mbggenerated
     */
    public String getInsflag() {
        return insflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_QUOTE_PARTY.INSFLAG
     *
     * @param insflag the value for GE_QUOTE_PARTY.INSFLAG
     *
     * @mbggenerated
     */
    public void setInsflag(String insflag) {
        this.insflag = insflag == null ? null : insflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_QUOTE_PARTY.REMARK
     *
     * @return the value of GE_QUOTE_PARTY.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_QUOTE_PARTY.REMARK
     *
     * @param remark the value for GE_QUOTE_PARTY.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_QUOTE_PARTY.FLAG
     *
     * @return the value of GE_QUOTE_PARTY.FLAG
     *
     * @mbggenerated
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_QUOTE_PARTY.FLAG
     *
     * @param flag the value for GE_QUOTE_PARTY.FLAG
     *
     * @mbggenerated
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_QUOTE_PARTY.OCCUPATIONM
     *
     * @return the value of GE_QUOTE_PARTY.OCCUPATIONM
     *
     * @mbggenerated
     */
    public String getOccupationm() {
        return occupationm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_QUOTE_PARTY.OCCUPATIONM
     *
     * @param occupationm the value for GE_QUOTE_PARTY.OCCUPATIONM
     *
     * @mbggenerated
     */
    public void setOccupationm(String occupationm) {
        this.occupationm = occupationm == null ? null : occupationm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_QUOTE_PARTY.OCCUPATIONTYPEM
     *
     * @return the value of GE_QUOTE_PARTY.OCCUPATIONTYPEM
     *
     * @mbggenerated
     */
    public String getOccupationtypem() {
        return occupationtypem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_QUOTE_PARTY.OCCUPATIONTYPEM
     *
     * @param occupationtypem the value for GE_QUOTE_PARTY.OCCUPATIONTYPEM
     *
     * @mbggenerated
     */
    public void setOccupationtypem(String occupationtypem) {
        this.occupationtypem = occupationtypem == null ? null : occupationtypem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_QUOTE_PARTY.OCCUPATIONS
     *
     * @return the value of GE_QUOTE_PARTY.OCCUPATIONS
     *
     * @mbggenerated
     */
    public String getOccupations() {
        return occupations;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_QUOTE_PARTY.OCCUPATIONS
     *
     * @param occupations the value for GE_QUOTE_PARTY.OCCUPATIONS
     *
     * @mbggenerated
     */
    public void setOccupations(String occupations) {
        this.occupations = occupations == null ? null : occupations.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_QUOTE_PARTY.OCCUPATIONTYPES
     *
     * @return the value of GE_QUOTE_PARTY.OCCUPATIONTYPES
     *
     * @mbggenerated
     */
    public String getOccupationtypes() {
        return occupationtypes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_QUOTE_PARTY.OCCUPATIONTYPES
     *
     * @param occupationtypes the value for GE_QUOTE_PARTY.OCCUPATIONTYPES
     *
     * @mbggenerated
     */
    public void setOccupationtypes(String occupationtypes) {
        this.occupationtypes = occupationtypes == null ? null : occupationtypes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_QUOTE_PARTY.UNDERWRITEAMOUNT
     *
     * @return the value of GE_QUOTE_PARTY.UNDERWRITEAMOUNT
     *
     * @mbggenerated
     */
    public String getUnderwriteamount() {
        return underwriteamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_QUOTE_PARTY.UNDERWRITEAMOUNT
     *
     * @param underwriteamount the value for GE_QUOTE_PARTY.UNDERWRITEAMOUNT
     *
     * @mbggenerated
     */
    public void setUnderwriteamount(String underwriteamount) {
        this.underwriteamount = underwriteamount == null ? null : underwriteamount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_QUOTE_PARTY.DRIVINGLICENCENO
     *
     * @return the value of GE_QUOTE_PARTY.DRIVINGLICENCENO
     *
     * @mbggenerated
     */
    public String getDrivinglicenceno() {
        return drivinglicenceno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_QUOTE_PARTY.DRIVINGLICENCENO
     *
     * @param drivinglicenceno the value for GE_QUOTE_PARTY.DRIVINGLICENCENO
     *
     * @mbggenerated
     */
    public void setDrivinglicenceno(String drivinglicenceno) {
        this.drivinglicenceno = drivinglicenceno == null ? null : drivinglicenceno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_QUOTE_PARTY.HOUSEADDRESS
     *
     * @return the value of GE_QUOTE_PARTY.HOUSEADDRESS
     *
     * @mbggenerated
     */
    public String getHouseaddress() {
        return houseaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_QUOTE_PARTY.HOUSEADDRESS
     *
     * @param houseaddress the value for GE_QUOTE_PARTY.HOUSEADDRESS
     *
     * @mbggenerated
     */
    public void setHouseaddress(String houseaddress) {
        this.houseaddress = houseaddress == null ? null : houseaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_QUOTE_PARTY.HOUSESTRUCTURE
     *
     * @return the value of GE_QUOTE_PARTY.HOUSESTRUCTURE
     *
     * @mbggenerated
     */
    public String getHousestructure() {
        return housestructure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_QUOTE_PARTY.HOUSESTRUCTURE
     *
     * @param housestructure the value for GE_QUOTE_PARTY.HOUSESTRUCTURE
     *
     * @mbggenerated
     */
    public void setHousestructure(String housestructure) {
        this.housestructure = housestructure == null ? null : housestructure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_QUOTE_PARTY.IDEXPDATE
     *
     * @return the value of GE_QUOTE_PARTY.IDEXPDATE
     *
     * @mbggenerated
     */
    public Date getIdexpdate() {
        return idexpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_QUOTE_PARTY.IDEXPDATE
     *
     * @param idexpdate the value for GE_QUOTE_PARTY.IDEXPDATE
     *
     * @mbggenerated
     */
    public void setIdexpdate(Date idexpdate) {
        this.idexpdate = idexpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_QUOTE_PARTY.IDSTDATE
     *
     * @return the value of GE_QUOTE_PARTY.IDSTDATE
     *
     * @mbggenerated
     */
    public Date getIdstdate() {
        return idstdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_QUOTE_PARTY.IDSTDATE
     *
     * @param idstdate the value for GE_QUOTE_PARTY.IDSTDATE
     *
     * @mbggenerated
     */
    public void setIdstdate(Date idstdate) {
        this.idstdate = idstdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GE_QUOTE_PARTY.ENTERPRISENAME
     *
     * @return the value of GE_QUOTE_PARTY.ENTERPRISENAME
     *
     * @mbggenerated
     */
    public String getEnterprisename() {
        return enterprisename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GE_QUOTE_PARTY.ENTERPRISENAME
     *
     * @param enterprisename the value for GE_QUOTE_PARTY.ENTERPRISENAME
     *
     * @mbggenerated
     */
    public void setEnterprisename(String enterprisename) {
        this.enterprisename = enterprisename == null ? null : enterprisename.trim();
    }
}