package com.future.dao.po;

public class ParentProjectInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parent_project_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parent_project_info.parent_project_name
     *
     * @mbggenerated
     */
    private String parentProjectName;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parent_project_info
     *
     * @mbggenerated
     */
    public ParentProjectInfo(Integer id, String parentProjectName) {
        this.id = id;
        this.parentProjectName = parentProjectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parent_project_info
     *
     * @mbggenerated
     */
    public ParentProjectInfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parent_project_info.id
     *
     * @return the value of parent_project_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parent_project_info.id
     *
     * @param id the value for parent_project_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parent_project_info.parent_project_name
     *
     * @return the value of parent_project_info.parent_project_name
     *
     * @mbggenerated
     */
    public String getParentProjectName() {
        return parentProjectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parent_project_info.parent_project_name
     *
     * @param parentProjectName the value for parent_project_info.parent_project_name
     *
     * @mbggenerated
     */
    public void setParentProjectName(String parentProjectName) {
        this.parentProjectName = parentProjectName == null ? null : parentProjectName.trim();
    }
}