package com.future.dao.po;

import java.util.Date;

public class ProjectInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.project_name
     *
     * @mbggenerated
     */
    private String projectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.parent_project_id
     *
     * @mbggenerated
     */
    private Integer parentProjectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.project_type
     *
     * @mbggenerated
     */
    private Byte projectType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.develop_field
     *
     * @mbggenerated
     */
    private String developField;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.workload
     *
     * @mbggenerated
     */
    private Float workload;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.handle_state
     *
     * @mbggenerated
     */
    private Byte handleState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.internal_task_state
     *
     * @mbggenerated
     */
    private Byte internalTaskState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.external_task_state
     *
     * @mbggenerated
     */
    private Byte externalTaskState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.joint_debug_date
     *
     * @mbggenerated
     */
    private Date jointDebugDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.requirements_received_date
     *
     * @mbggenerated
     */
    private Date requirementsReceivedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_info.owner_id
     *
     * @mbggenerated
     */
    private Integer ownerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_info
     *
     * @mbggenerated
     */
    public ProjectInfo(Integer id, String projectName, Integer parentProjectId, Byte projectType, String developField, Float workload, Byte handleState, Byte internalTaskState, Byte externalTaskState, Date jointDebugDate, Date requirementsReceivedDate, Integer ownerId) {
        this.id = id;
        this.projectName = projectName;
        this.parentProjectId = parentProjectId;
        this.projectType = projectType;
        this.developField = developField;
        this.workload = workload;
        this.handleState = handleState;
        this.internalTaskState = internalTaskState;
        this.externalTaskState = externalTaskState;
        this.jointDebugDate = jointDebugDate;
        this.requirementsReceivedDate = requirementsReceivedDate;
        this.ownerId = ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_info
     *
     * @mbggenerated
     */
    public ProjectInfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.id
     *
     * @return the value of project_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.id
     *
     * @param id the value for project_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.project_name
     *
     * @return the value of project_info.project_name
     *
     * @mbggenerated
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.project_name
     *
     * @param projectName the value for project_info.project_name
     *
     * @mbggenerated
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.parent_project_id
     *
     * @return the value of project_info.parent_project_id
     *
     * @mbggenerated
     */
    public Integer getParentProjectId() {
        return parentProjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.parent_project_id
     *
     * @param parentProjectId the value for project_info.parent_project_id
     *
     * @mbggenerated
     */
    public void setParentProjectId(Integer parentProjectId) {
        this.parentProjectId = parentProjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.project_type
     *
     * @return the value of project_info.project_type
     *
     * @mbggenerated
     */
    public Byte getProjectType() {
        return projectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.project_type
     *
     * @param projectType the value for project_info.project_type
     *
     * @mbggenerated
     */
    public void setProjectType(Byte projectType) {
        this.projectType = projectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.develop_field
     *
     * @return the value of project_info.develop_field
     *
     * @mbggenerated
     */
    public String getDevelopField() {
        return developField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.develop_field
     *
     * @param developField the value for project_info.develop_field
     *
     * @mbggenerated
     */
    public void setDevelopField(String developField) {
        this.developField = developField == null ? null : developField.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.workload
     *
     * @return the value of project_info.workload
     *
     * @mbggenerated
     */
    public Float getWorkload() {
        return workload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.workload
     *
     * @param workload the value for project_info.workload
     *
     * @mbggenerated
     */
    public void setWorkload(Float workload) {
        this.workload = workload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.handle_state
     *
     * @return the value of project_info.handle_state
     *
     * @mbggenerated
     */
    public Byte getHandleState() {
        return handleState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.handle_state
     *
     * @param handleState the value for project_info.handle_state
     *
     * @mbggenerated
     */
    public void setHandleState(Byte handleState) {
        this.handleState = handleState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.internal_task_state
     *
     * @return the value of project_info.internal_task_state
     *
     * @mbggenerated
     */
    public Byte getInternalTaskState() {
        return internalTaskState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.internal_task_state
     *
     * @param internalTaskState the value for project_info.internal_task_state
     *
     * @mbggenerated
     */
    public void setInternalTaskState(Byte internalTaskState) {
        this.internalTaskState = internalTaskState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.external_task_state
     *
     * @return the value of project_info.external_task_state
     *
     * @mbggenerated
     */
    public Byte getExternalTaskState() {
        return externalTaskState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.external_task_state
     *
     * @param externalTaskState the value for project_info.external_task_state
     *
     * @mbggenerated
     */
    public void setExternalTaskState(Byte externalTaskState) {
        this.externalTaskState = externalTaskState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.joint_debug_date
     *
     * @return the value of project_info.joint_debug_date
     *
     * @mbggenerated
     */
    public Date getJointDebugDate() {
        return jointDebugDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.joint_debug_date
     *
     * @param jointDebugDate the value for project_info.joint_debug_date
     *
     * @mbggenerated
     */
    public void setJointDebugDate(Date jointDebugDate) {
        this.jointDebugDate = jointDebugDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.requirements_received_date
     *
     * @return the value of project_info.requirements_received_date
     *
     * @mbggenerated
     */
    public Date getRequirementsReceivedDate() {
        return requirementsReceivedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.requirements_received_date
     *
     * @param requirementsReceivedDate the value for project_info.requirements_received_date
     *
     * @mbggenerated
     */
    public void setRequirementsReceivedDate(Date requirementsReceivedDate) {
        this.requirementsReceivedDate = requirementsReceivedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_info.owner_id
     *
     * @return the value of project_info.owner_id
     *
     * @mbggenerated
     */
    public Integer getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_info.owner_id
     *
     * @param ownerId the value for project_info.owner_id
     *
     * @mbggenerated
     */
    public void setOwnerId(Integer ownerId) {
        this.ownerId = ownerId;
    }
}