package com.future.dao.po;

public class SC {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SC.Sid
     *
     * @mbggenerated
     */
    private Integer sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SC.Cid
     *
     * @mbggenerated
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SC.score
     *
     * @mbggenerated
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SC
     *
     * @mbggenerated
     */
    public SC(Integer sid, Integer cid, Integer score) {
        this.sid = sid;
        this.cid = cid;
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SC
     *
     * @mbggenerated
     */
    public SC() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SC.Sid
     *
     * @return the value of SC.Sid
     *
     * @mbggenerated
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SC.Sid
     *
     * @param sid the value for SC.Sid
     *
     * @mbggenerated
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SC.Cid
     *
     * @return the value of SC.Cid
     *
     * @mbggenerated
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SC.Cid
     *
     * @param cid the value for SC.Cid
     *
     * @mbggenerated
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SC.score
     *
     * @return the value of SC.score
     *
     * @mbggenerated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SC.score
     *
     * @param score the value for SC.score
     *
     * @mbggenerated
     */
    public void setScore(Integer score) {
        this.score = score;
    }
}