package com.future.dao.po;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Student.Sid
     *
     * @mbggenerated
     */
    private Integer sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Student.Sname
     *
     * @mbggenerated
     */
    private String sname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Student.Sage
     *
     * @mbggenerated
     */
    private Integer sage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Student.Ssex
     *
     * @mbggenerated
     */
    private String ssex;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Student
     *
     * @mbggenerated
     */
    public Student(Integer sid, String sname, Integer sage, String ssex) {
        this.sid = sid;
        this.sname = sname;
        this.sage = sage;
        this.ssex = ssex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Student
     *
     * @mbggenerated
     */
    public Student() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Student.Sid
     *
     * @return the value of Student.Sid
     *
     * @mbggenerated
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Student.Sid
     *
     * @param sid the value for Student.Sid
     *
     * @mbggenerated
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Student.Sname
     *
     * @return the value of Student.Sname
     *
     * @mbggenerated
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Student.Sname
     *
     * @param sname the value for Student.Sname
     *
     * @mbggenerated
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Student.Sage
     *
     * @return the value of Student.Sage
     *
     * @mbggenerated
     */
    public Integer getSage() {
        return sage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Student.Sage
     *
     * @param sage the value for Student.Sage
     *
     * @mbggenerated
     */
    public void setSage(Integer sage) {
        this.sage = sage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Student.Ssex
     *
     * @return the value of Student.Ssex
     *
     * @mbggenerated
     */
    public String getSsex() {
        return ssex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Student.Ssex
     *
     * @param ssex the value for Student.Ssex
     *
     * @mbggenerated
     */
    public void setSsex(String ssex) {
        this.ssex = ssex == null ? null : ssex.trim();
    }
}