package com.future.dao.po;

public class TeamInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_info.id
     *
     * @mbggenerated
     */
    private Byte id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_info.team_name
     *
     * @mbggenerated
     */
    private String teamName;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_info
     *
     * @mbggenerated
     */
    public TeamInfo(Byte id, String teamName) {
        this.id = id;
        this.teamName = teamName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_info
     *
     * @mbggenerated
     */
    public TeamInfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_info.id
     *
     * @return the value of team_info.id
     *
     * @mbggenerated
     */
    public Byte getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_info.id
     *
     * @param id the value for team_info.id
     *
     * @mbggenerated
     */
    public void setId(Byte id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_info.team_name
     *
     * @return the value of team_info.team_name
     *
     * @mbggenerated
     */
    public String getTeamName() {
        return teamName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_info.team_name
     *
     * @param teamName the value for team_info.team_name
     *
     * @mbggenerated
     */
    public void setTeamName(String teamName) {
        this.teamName = teamName == null ? null : teamName.trim();
    }
}