package com.future.dao4ora.idao;

import com.future.dao4ora.po.EndorsementEndorseitems;
import com.future.dao4ora.po.EndorsementEndorseitemsWithBLOBs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface EndorsementEndorseitemsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENDORSEMENT_ENDORSEITEMS
     *
     * @mbggenerated
     */
    @Delete({
        "delete from ENDORSEMENT_ENDORSEITEMS",
        "where PROPOSALSID = #{proposalsid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String proposalsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENDORSEMENT_ENDORSEITEMS
     *
     * @mbggenerated
     */
    @Insert({
        "insert into ENDORSEMENT_ENDORSEITEMS (PROPOSALSID, BATCHID, ",
        "ITEMID, ITEMTYPE, ",
        "CREATESTAMP, LASTUPDATESTAMP, ",
        "OLDVALUE, NEWVALUE)",
        "values (#{proposalsid,jdbcType=VARCHAR}, #{batchid,jdbcType=VARCHAR}, ",
        "#{itemid,jdbcType=VARCHAR}, #{itemtype,jdbcType=VARCHAR}, ",
        "#{createstamp,jdbcType=TIMESTAMP}, #{lastupdatestamp,jdbcType=TIMESTAMP}, ",
        "#{oldvalue,jdbcType=CLOB}, #{newvalue,jdbcType=CLOB})"
    })
    int insert(EndorsementEndorseitemsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENDORSEMENT_ENDORSEITEMS
     *
     * @mbggenerated
     */
    int insertSelective(EndorsementEndorseitemsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENDORSEMENT_ENDORSEITEMS
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "PROPOSALSID, BATCHID, ITEMID, ITEMTYPE, CREATESTAMP, LASTUPDATESTAMP, OLDVALUE, ",
        "NEWVALUE",
        "from ENDORSEMENT_ENDORSEITEMS",
        "where PROPOSALSID = #{proposalsid,jdbcType=VARCHAR}"
    })
    @ResultMap("ResultMapWithBLOBs")
    EndorsementEndorseitemsWithBLOBs selectByPrimaryKey(String proposalsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENDORSEMENT_ENDORSEITEMS
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EndorsementEndorseitemsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENDORSEMENT_ENDORSEITEMS
     *
     * @mbggenerated
     */
    @Update({
        "update ENDORSEMENT_ENDORSEITEMS",
        "set BATCHID = #{batchid,jdbcType=VARCHAR},",
          "ITEMID = #{itemid,jdbcType=VARCHAR},",
          "ITEMTYPE = #{itemtype,jdbcType=VARCHAR},",
          "CREATESTAMP = #{createstamp,jdbcType=TIMESTAMP},",
          "LASTUPDATESTAMP = #{lastupdatestamp,jdbcType=TIMESTAMP},",
          "OLDVALUE = #{oldvalue,jdbcType=CLOB},",
          "NEWVALUE = #{newvalue,jdbcType=CLOB}",
        "where PROPOSALSID = #{proposalsid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKeyWithBLOBs(EndorsementEndorseitemsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENDORSEMENT_ENDORSEITEMS
     *
     * @mbggenerated
     */
    @Update({
        "update ENDORSEMENT_ENDORSEITEMS",
        "set BATCHID = #{batchid,jdbcType=VARCHAR},",
          "ITEMID = #{itemid,jdbcType=VARCHAR},",
          "ITEMTYPE = #{itemtype,jdbcType=VARCHAR},",
          "CREATESTAMP = #{createstamp,jdbcType=TIMESTAMP},",
          "LASTUPDATESTAMP = #{lastupdatestamp,jdbcType=TIMESTAMP}",
        "where PROPOSALSID = #{proposalsid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(EndorsementEndorseitems record);
}