package com.future.dao4ora.idao;

import com.future.dao4ora.po.GeFlycuaAir;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface GeFlycuaAirMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GE_FLYCUA_AIR
     *
     * @mbggenerated
     */
    @Delete({
        "delete from GE_FLYCUA_AIR",
        "where FLYCUAID = #{flycuaid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String flycuaid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GE_FLYCUA_AIR
     *
     * @mbggenerated
     */
    @Insert({
        "insert into GE_FLYCUA_AIR (FLYCUAID, POLICYNO, ",
        "PROPOSALNO, STATUS, ",
        "REASON, MAKEDATE, ",
        "MODIFYDATE, NUM, ",
        "RETURNCODE, ITEMID, ",
        "TICKETNO, FLIGHTNO)",
        "values (#{flycuaid,jdbcType=VARCHAR}, #{policyno,jdbcType=VARCHAR}, ",
        "#{proposalno,jdbcType=VARCHAR}, #{status,jdbcType=VARCHAR}, ",
        "#{reason,jdbcType=VARCHAR}, #{makedate,jdbcType=TIMESTAMP}, ",
        "#{modifydate,jdbcType=TIMESTAMP}, #{num,jdbcType=NUMERIC}, ",
        "#{returncode,jdbcType=VARCHAR}, #{itemid,jdbcType=VARCHAR}, ",
        "#{ticketno,jdbcType=VARCHAR}, #{flightno,jdbcType=VARCHAR})"
    })
    int insert(GeFlycuaAir record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GE_FLYCUA_AIR
     *
     * @mbggenerated
     */
    int insertSelective(GeFlycuaAir record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GE_FLYCUA_AIR
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "FLYCUAID, POLICYNO, PROPOSALNO, STATUS, REASON, MAKEDATE, MODIFYDATE, NUM, RETURNCODE, ",
        "ITEMID, TICKETNO, FLIGHTNO",
        "from GE_FLYCUA_AIR",
        "where FLYCUAID = #{flycuaid,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    GeFlycuaAir selectByPrimaryKey(String flycuaid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GE_FLYCUA_AIR
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GeFlycuaAir record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GE_FLYCUA_AIR
     *
     * @mbggenerated
     */
    @Update({
        "update GE_FLYCUA_AIR",
        "set POLICYNO = #{policyno,jdbcType=VARCHAR},",
          "PROPOSALNO = #{proposalno,jdbcType=VARCHAR},",
          "STATUS = #{status,jdbcType=VARCHAR},",
          "REASON = #{reason,jdbcType=VARCHAR},",
          "MAKEDATE = #{makedate,jdbcType=TIMESTAMP},",
          "MODIFYDATE = #{modifydate,jdbcType=TIMESTAMP},",
          "NUM = #{num,jdbcType=NUMERIC},",
          "RETURNCODE = #{returncode,jdbcType=VARCHAR},",
          "ITEMID = #{itemid,jdbcType=VARCHAR},",
          "TICKETNO = #{ticketno,jdbcType=VARCHAR},",
          "FLIGHTNO = #{flightno,jdbcType=VARCHAR}",
        "where FLYCUAID = #{flycuaid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(GeFlycuaAir record);
}