package com.future.dao4ora.idao;

import com.future.dao4ora.po.GeAlipayAirinfo;
import com.future.dao4ora.po.GeProposalMain;
import org.apache.ibatis.annotations.*;

import java.util.List;

public interface GeProposalMainMapper {
    @Select({
            "SELECT",
            "a.tbOrderId,b.partyname ",
            "FROM chinalifeec.GE_PROPOSAL_MAIN a ",
            "LEFT JOIN chinalifeec.GE_QUOTE_PARTY b ON a.quoteno = b.quoteno ",
            "WHERE ",
            "b.partyflag = '2' " ,
            "and a.OPERATEDATE>=to_date(to_char(trunc(sysdate-1),'yyyy-mm-dd') ||' 00:00:00','yyyy-mm-dd hh24:mi:ss') " ,
            "and a.OPERATEDATE<=to_date(to_char(trunc(sysdate-0),'yyyy-mm-dd') ||' 23:59:59','yyyy-mm-dd hh24:mi:ss') " ,
            "and a.PRODUCTNO='313' " ,
            "ORDER BY " ,
            "a.OPERATEDATE DESC"
    })
//    @ResultMap("com.future.dao4ora.idao.GeProposalMainMapper.joinResultMap")
//@ResultType(Map.class)
    @ResultMap("joinResultMap")
    List<GeProposalMain> selectForStat();

    @Select({
            "SELECT ",
            "a.tbOrderId,a.PROPOSALNO,a.SUMPREMIUM,a.SUMAMOUNT,a.OPERATEDATE,a.STARTDATE,a.ENDDATE,a.UNITCOUNT, ",
            "c.airOrderId,c.flightNo,c.airTakeOff, ",
            "d.payWay,d.alipayBuyerId,d.payTime,d.orderAmount,d.payOrderId, ",
            "c.bizOrderId, ",
            "a.appliName,a.appliaddress, ",
            "b.partyname,b.IDENTIFYTYPE,b.IDENTIFYNUMBER,b.birthday, ",
            "a.REQUESTEDTIME,a.loanStartTime,a.status,a.reason ",
            "FROM chinalifeec.GE_PROPOSAL_MAIN a ",
            "LEFT JOIN chinalifeec.GE_QUOTE_PARTY b ON a.quoteno = b.quoteno ",
            "LEFT JOIN chinalifeec.GE_AIRORDER c ON a.tbOrderId = c.policyno ",
            "LEFT JOIN chinalifeec.GE_ORDER d on a.tbOrderId = d.tbOrderId ",
            "WHERE ",
            "b.partyflag = '2' ",
            "AND ",
            "c.proposalno = a.proposalno ",
            "and c.status='1' ",
            "and a.PRODUCTNO='313' ",
            "and  a.PROPOSALNO= #{proposalno,jdbcType=VARCHAR} ",

            "ORDER BY a.OPERATEDATE DESC "
    })
    @ResultMap("joinResultMap")
    GeProposalMain selectForAliAir(GeProposalMain geProposalMain);

    @Select({
            "select ",
            " '蚂蚁航意险' as PRODUCTNAME,",
            " m.SUMPREMIUM,  ",
            " p.identifynumber, ",
            " p.identifytype, ",
            " p.partyname, ",
            " m.policyno  ",
            " from chinalifeec.ge_proposal_main m  ",
            " left join chinalifeec.ge_quote_party p on m.quoteno=p.quoteno ",
            " where ",
            " m.productno='313'",
            " and m.tbOrderId='${tborderid}'  ",
            " and ( p.partyflag is null or p.partyflag = '2') "
    })
    @ResultMap("joinResultMap")
    List<GeProposalMain> selectOmittedByOrderId(@Param("tborderid")String tborderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GE_PROPOSAL_MAIN
     *
     * @mbggenerated
     */
    @Delete({
        "delete from GE_PROPOSAL_MAIN",
        "where PROPOSALSID = #{proposalsid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String proposalsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GE_PROPOSAL_MAIN
     *
     * @mbggenerated
     */
    @Insert({
        "insert into GE_PROPOSAL_MAIN (PROPOSALSID, PROPOSALNO, ",
        "QUOTENO, POLICYNO, ",
        "PRODUCTNO, RISKCODE, ",
        "CLASSCODE, BUSINESSNATURE, ",
        "AREACODE, SALECOM, ",
        "OPERATEDATE, APPLINAME, ",
        "APPLIADDRESS, INSUREDNAME, ",
        "INSUREDADDRESS, USERID, ",
        "USERTYPE, CHANNELCODE, ",
        "RENEWALFLAG, OLDLPOLICYNO, ",
        "STARTDATE, ENDDATE, ",
        "UNITCOUNT, PERIODUNIT, ",
        "PERIOD, CURRENCY, ",
        "MAXINSURANCEAMOUNT, SUMAMOUNT, ",
        "SUMBASEPREMIUM, DISCOUNT, ",
        "SUMDISCOUNT, SUMPREMIUM, ",
        "SUMSUBPREMIUM, ISPAPER, ",
        "ELEADDRESS, BUSINESSAREA, ",
        "PLATFORMINVALIDDATE, INPUTDATE, ",
        "INPUTHOUR, ISLEGALFLAG, ",
        "ISCLEAR, STATUS, ",
        "UPDATETIME, UPDATEDATE, ",
        "AGENTCODE, AGREEMENTNO, ",
        "AGENTNAME, DEPARTMENTNO, ",
        "DEPARTMENTNAME, REASON, ",
        "FLAG, EID, AREACODEPRO, ",
        "PRECHECKDATE, MOREBUYNO, ",
        "DISCOUNTID, PAYMENTSTATUS, ",
        "BUSINESSSOURCE, GROUPCHANNEL, ",
        "HXSUMPREMIUM, HXSTATUS, ",
        "HXPOLICYSTATUS, SESSIONID, ",
        "TBITEMID, TBSUBORDERID, ",
        "ITEMID, TBORDERID, ",
        "COMMUNICATIONMODE, APPTIME, ",
        "ZHREFERENCECODE, SALETYPE, ",
        "SOCIATYPAYMENTNO, REFERRALCODE, ",
        "ORDERNO, OPENID, ",
        "SALESMANID, SALESMANCHANNEL, ",
        "SALESMANTYPE, MOBILEIMEI, ",
        "MAINTENANCE, MOBILEBRAND, ",
        "MOBILEMODEL, ISCLAIMS, ",
        "CLAIMSTIME, RECEIVEAGE, ",
        "PAYTIME, LOANPREMIUM, ",
        "LOANSTARTTIME, LOANENDTIME, ",
        "SURRENDERSTATUS, SURRENDERTIME, ",
        "SURRENDERUPDATEDATE, SURRENDERUPDATETIME, ",
        "SURRENDERMSG, REQUESTEDTIME)",
        "values (#{proposalsid,jdbcType=VARCHAR}, #{proposalno,jdbcType=VARCHAR}, ",
        "#{quoteno,jdbcType=VARCHAR}, #{policyno,jdbcType=VARCHAR}, ",
        "#{productno,jdbcType=VARCHAR}, #{riskcode,jdbcType=VARCHAR}, ",
        "#{classcode,jdbcType=VARCHAR}, #{businessnature,jdbcType=VARCHAR}, ",
        "#{areacode,jdbcType=VARCHAR}, #{salecom,jdbcType=VARCHAR}, ",
        "#{operatedate,jdbcType=TIMESTAMP}, #{appliname,jdbcType=VARCHAR}, ",
        "#{appliaddress,jdbcType=VARCHAR}, #{insuredname,jdbcType=VARCHAR}, ",
        "#{insuredaddress,jdbcType=VARCHAR}, #{userid,jdbcType=VARCHAR}, ",
        "#{usertype,jdbcType=VARCHAR}, #{channelcode,jdbcType=VARCHAR}, ",
        "#{renewalflag,jdbcType=VARCHAR}, #{oldlpolicyno,jdbcType=VARCHAR}, ",
        "#{startdate,jdbcType=TIMESTAMP}, #{enddate,jdbcType=TIMESTAMP}, ",
        "#{unitcount,jdbcType=VARCHAR}, #{periodunit,jdbcType=VARCHAR}, ",
        "#{period,jdbcType=VARCHAR}, #{currency,jdbcType=VARCHAR}, ",
        "#{maxinsuranceamount,jdbcType=VARCHAR}, #{sumamount,jdbcType=NUMERIC}, ",
        "#{sumbasepremium,jdbcType=NUMERIC}, #{discount,jdbcType=NUMERIC}, ",
        "#{sumdiscount,jdbcType=NUMERIC}, #{sumpremium,jdbcType=NUMERIC}, ",
        "#{sumsubpremium,jdbcType=NUMERIC}, #{ispaper,jdbcType=VARCHAR}, ",
        "#{eleaddress,jdbcType=VARCHAR}, #{businessarea,jdbcType=VARCHAR}, ",
        "#{platforminvaliddate,jdbcType=TIMESTAMP}, #{inputdate,jdbcType=TIMESTAMP}, ",
        "#{inputhour,jdbcType=VARCHAR}, #{islegalflag,jdbcType=VARCHAR}, ",
        "#{isclear,jdbcType=VARCHAR}, #{status,jdbcType=VARCHAR}, ",
        "#{updatetime,jdbcType=TIMESTAMP}, #{updatedate,jdbcType=TIMESTAMP}, ",
        "#{agentcode,jdbcType=VARCHAR}, #{agreementno,jdbcType=VARCHAR}, ",
        "#{agentname,jdbcType=VARCHAR}, #{departmentno,jdbcType=VARCHAR}, ",
        "#{departmentname,jdbcType=VARCHAR}, #{reason,jdbcType=VARCHAR}, ",
        "#{flag,jdbcType=VARCHAR}, #{eid,jdbcType=VARCHAR}, #{areacodepro,jdbcType=VARCHAR}, ",
        "#{precheckdate,jdbcType=VARCHAR}, #{morebuyno,jdbcType=VARCHAR}, ",
        "#{discountid,jdbcType=VARCHAR}, #{paymentstatus,jdbcType=VARCHAR}, ",
        "#{businesssource,jdbcType=VARCHAR}, #{groupchannel,jdbcType=VARCHAR}, ",
        "#{hxsumpremium,jdbcType=NUMERIC}, #{hxstatus,jdbcType=VARCHAR}, ",
        "#{hxpolicystatus,jdbcType=VARCHAR}, #{sessionid,jdbcType=VARCHAR}, ",
        "#{tbitemid,jdbcType=VARCHAR}, #{tbsuborderid,jdbcType=VARCHAR}, ",
        "#{itemid,jdbcType=VARCHAR}, #{tborderid,jdbcType=VARCHAR}, ",
        "#{communicationmode,jdbcType=VARCHAR}, #{apptime,jdbcType=VARCHAR}, ",
        "#{zhreferencecode,jdbcType=VARCHAR}, #{saletype,jdbcType=VARCHAR}, ",
        "#{sociatypaymentno,jdbcType=VARCHAR}, #{referralcode,jdbcType=VARCHAR}, ",
        "#{orderno,jdbcType=VARCHAR}, #{openid,jdbcType=VARCHAR}, ",
        "#{salesmanid,jdbcType=VARCHAR}, #{salesmanchannel,jdbcType=VARCHAR}, ",
        "#{salesmantype,jdbcType=VARCHAR}, #{mobileimei,jdbcType=VARCHAR}, ",
        "#{maintenance,jdbcType=NUMERIC}, #{mobilebrand,jdbcType=VARCHAR}, ",
        "#{mobilemodel,jdbcType=VARCHAR}, #{isclaims,jdbcType=VARCHAR}, ",
        "#{claimstime,jdbcType=TIMESTAMP}, #{receiveage,jdbcType=VARCHAR}, ",
        "#{paytime,jdbcType=VARCHAR}, #{loanpremium,jdbcType=NUMERIC}, ",
        "#{loanstarttime,jdbcType=TIMESTAMP}, #{loanendtime,jdbcType=TIMESTAMP}, ",
        "#{surrenderstatus,jdbcType=VARCHAR}, #{surrendertime,jdbcType=TIMESTAMP}, ",
        "#{surrenderupdatedate,jdbcType=TIMESTAMP}, #{surrenderupdatetime,jdbcType=TIMESTAMP}, ",
        "#{surrendermsg,jdbcType=VARCHAR}, #{requestedtime,jdbcType=TIMESTAMP})"
    })
    int insert(GeProposalMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GE_PROPOSAL_MAIN
     *
     * @mbggenerated
     */
    int insertSelective(GeProposalMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GE_PROPOSAL_MAIN
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "PROPOSALSID, PROPOSALNO, QUOTENO, POLICYNO, PRODUCTNO, RISKCODE, CLASSCODE, ",
        "BUSINESSNATURE, AREACODE, SALECOM, OPERATEDATE, APPLINAME, APPLIADDRESS, INSUREDNAME, ",
        "INSUREDADDRESS, USERID, USERTYPE, CHANNELCODE, RENEWALFLAG, OLDLPOLICYNO, STARTDATE, ",
        "ENDDATE, UNITCOUNT, PERIODUNIT, PERIOD, CURRENCY, MAXINSURANCEAMOUNT, SUMAMOUNT, ",
        "SUMBASEPREMIUM, DISCOUNT, SUMDISCOUNT, SUMPREMIUM, SUMSUBPREMIUM, ISPAPER, ELEADDRESS, ",
        "BUSINESSAREA, PLATFORMINVALIDDATE, INPUTDATE, INPUTHOUR, ISLEGALFLAG, ISCLEAR, ",
        "STATUS, UPDATETIME, UPDATEDATE, AGENTCODE, AGREEMENTNO, AGENTNAME, DEPARTMENTNO, ",
        "DEPARTMENTNAME, REASON, FLAG, EID, AREACODEPRO, PRECHECKDATE, MOREBUYNO, DISCOUNTID, ",
        "PAYMENTSTATUS, BUSINESSSOURCE, GROUPCHANNEL, HXSUMPREMIUM, HXSTATUS, HXPOLICYSTATUS, ",
        "SESSIONID, TBITEMID, TBSUBORDERID, ITEMID, TBORDERID, COMMUNICATIONMODE, APPTIME, ",
        "ZHREFERENCECODE, SALETYPE, SOCIATYPAYMENTNO, REFERRALCODE, ORDERNO, OPENID, ",
        "SALESMANID, SALESMANCHANNEL, SALESMANTYPE, MOBILEIMEI, MAINTENANCE, MOBILEBRAND, ",
        "MOBILEMODEL, ISCLAIMS, CLAIMSTIME, RECEIVEAGE, PAYTIME, LOANPREMIUM, LOANSTARTTIME, ",
        "LOANENDTIME, SURRENDERSTATUS, SURRENDERTIME, SURRENDERUPDATEDATE, SURRENDERUPDATETIME, ",
        "SURRENDERMSG, REQUESTEDTIME",
        "from GE_PROPOSAL_MAIN",
        "where PROPOSALSID = #{proposalsid,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    GeProposalMain selectByPrimaryKey(String proposalsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GE_PROPOSAL_MAIN
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GeProposalMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GE_PROPOSAL_MAIN
     *
     * @mbggenerated
     */
    @Update({
        "update GE_PROPOSAL_MAIN",
        "set PROPOSALNO = #{proposalno,jdbcType=VARCHAR},",
          "QUOTENO = #{quoteno,jdbcType=VARCHAR},",
          "POLICYNO = #{policyno,jdbcType=VARCHAR},",
          "PRODUCTNO = #{productno,jdbcType=VARCHAR},",
          "RISKCODE = #{riskcode,jdbcType=VARCHAR},",
          "CLASSCODE = #{classcode,jdbcType=VARCHAR},",
          "BUSINESSNATURE = #{businessnature,jdbcType=VARCHAR},",
          "AREACODE = #{areacode,jdbcType=VARCHAR},",
          "SALECOM = #{salecom,jdbcType=VARCHAR},",
          "OPERATEDATE = #{operatedate,jdbcType=TIMESTAMP},",
          "APPLINAME = #{appliname,jdbcType=VARCHAR},",
          "APPLIADDRESS = #{appliaddress,jdbcType=VARCHAR},",
          "INSUREDNAME = #{insuredname,jdbcType=VARCHAR},",
          "INSUREDADDRESS = #{insuredaddress,jdbcType=VARCHAR},",
          "USERID = #{userid,jdbcType=VARCHAR},",
          "USERTYPE = #{usertype,jdbcType=VARCHAR},",
          "CHANNELCODE = #{channelcode,jdbcType=VARCHAR},",
          "RENEWALFLAG = #{renewalflag,jdbcType=VARCHAR},",
          "OLDLPOLICYNO = #{oldlpolicyno,jdbcType=VARCHAR},",
          "STARTDATE = #{startdate,jdbcType=TIMESTAMP},",
          "ENDDATE = #{enddate,jdbcType=TIMESTAMP},",
          "UNITCOUNT = #{unitcount,jdbcType=VARCHAR},",
          "PERIODUNIT = #{periodunit,jdbcType=VARCHAR},",
          "PERIOD = #{period,jdbcType=VARCHAR},",
          "CURRENCY = #{currency,jdbcType=VARCHAR},",
          "MAXINSURANCEAMOUNT = #{maxinsuranceamount,jdbcType=VARCHAR},",
          "SUMAMOUNT = #{sumamount,jdbcType=NUMERIC},",
          "SUMBASEPREMIUM = #{sumbasepremium,jdbcType=NUMERIC},",
          "DISCOUNT = #{discount,jdbcType=NUMERIC},",
          "SUMDISCOUNT = #{sumdiscount,jdbcType=NUMERIC},",
          "SUMPREMIUM = #{sumpremium,jdbcType=NUMERIC},",
          "SUMSUBPREMIUM = #{sumsubpremium,jdbcType=NUMERIC},",
          "ISPAPER = #{ispaper,jdbcType=VARCHAR},",
          "ELEADDRESS = #{eleaddress,jdbcType=VARCHAR},",
          "BUSINESSAREA = #{businessarea,jdbcType=VARCHAR},",
          "PLATFORMINVALIDDATE = #{platforminvaliddate,jdbcType=TIMESTAMP},",
          "INPUTDATE = #{inputdate,jdbcType=TIMESTAMP},",
          "INPUTHOUR = #{inputhour,jdbcType=VARCHAR},",
          "ISLEGALFLAG = #{islegalflag,jdbcType=VARCHAR},",
          "ISCLEAR = #{isclear,jdbcType=VARCHAR},",
          "STATUS = #{status,jdbcType=VARCHAR},",
          "UPDATETIME = #{updatetime,jdbcType=TIMESTAMP},",
          "UPDATEDATE = #{updatedate,jdbcType=TIMESTAMP},",
          "AGENTCODE = #{agentcode,jdbcType=VARCHAR},",
          "AGREEMENTNO = #{agreementno,jdbcType=VARCHAR},",
          "AGENTNAME = #{agentname,jdbcType=VARCHAR},",
          "DEPARTMENTNO = #{departmentno,jdbcType=VARCHAR},",
          "DEPARTMENTNAME = #{departmentname,jdbcType=VARCHAR},",
          "REASON = #{reason,jdbcType=VARCHAR},",
          "FLAG = #{flag,jdbcType=VARCHAR},",
          "EID = #{eid,jdbcType=VARCHAR},",
          "AREACODEPRO = #{areacodepro,jdbcType=VARCHAR},",
          "PRECHECKDATE = #{precheckdate,jdbcType=VARCHAR},",
          "MOREBUYNO = #{morebuyno,jdbcType=VARCHAR},",
          "DISCOUNTID = #{discountid,jdbcType=VARCHAR},",
          "PAYMENTSTATUS = #{paymentstatus,jdbcType=VARCHAR},",
          "BUSINESSSOURCE = #{businesssource,jdbcType=VARCHAR},",
          "GROUPCHANNEL = #{groupchannel,jdbcType=VARCHAR},",
          "HXSUMPREMIUM = #{hxsumpremium,jdbcType=NUMERIC},",
          "HXSTATUS = #{hxstatus,jdbcType=VARCHAR},",
          "HXPOLICYSTATUS = #{hxpolicystatus,jdbcType=VARCHAR},",
          "SESSIONID = #{sessionid,jdbcType=VARCHAR},",
          "TBITEMID = #{tbitemid,jdbcType=VARCHAR},",
          "TBSUBORDERID = #{tbsuborderid,jdbcType=VARCHAR},",
          "ITEMID = #{itemid,jdbcType=VARCHAR},",
          "TBORDERID = #{tborderid,jdbcType=VARCHAR},",
          "COMMUNICATIONMODE = #{communicationmode,jdbcType=VARCHAR},",
          "APPTIME = #{apptime,jdbcType=VARCHAR},",
          "ZHREFERENCECODE = #{zhreferencecode,jdbcType=VARCHAR},",
          "SALETYPE = #{saletype,jdbcType=VARCHAR},",
          "SOCIATYPAYMENTNO = #{sociatypaymentno,jdbcType=VARCHAR},",
          "REFERRALCODE = #{referralcode,jdbcType=VARCHAR},",
          "ORDERNO = #{orderno,jdbcType=VARCHAR},",
          "OPENID = #{openid,jdbcType=VARCHAR},",
          "SALESMANID = #{salesmanid,jdbcType=VARCHAR},",
          "SALESMANCHANNEL = #{salesmanchannel,jdbcType=VARCHAR},",
          "SALESMANTYPE = #{salesmantype,jdbcType=VARCHAR},",
          "MOBILEIMEI = #{mobileimei,jdbcType=VARCHAR},",
          "MAINTENANCE = #{maintenance,jdbcType=NUMERIC},",
          "MOBILEBRAND = #{mobilebrand,jdbcType=VARCHAR},",
          "MOBILEMODEL = #{mobilemodel,jdbcType=VARCHAR},",
          "ISCLAIMS = #{isclaims,jdbcType=VARCHAR},",
          "CLAIMSTIME = #{claimstime,jdbcType=TIMESTAMP},",
          "RECEIVEAGE = #{receiveage,jdbcType=VARCHAR},",
          "PAYTIME = #{paytime,jdbcType=VARCHAR},",
          "LOANPREMIUM = #{loanpremium,jdbcType=NUMERIC},",
          "LOANSTARTTIME = #{loanstarttime,jdbcType=TIMESTAMP},",
          "LOANENDTIME = #{loanendtime,jdbcType=TIMESTAMP},",
          "SURRENDERSTATUS = #{surrenderstatus,jdbcType=VARCHAR},",
          "SURRENDERTIME = #{surrendertime,jdbcType=TIMESTAMP},",
          "SURRENDERUPDATEDATE = #{surrenderupdatedate,jdbcType=TIMESTAMP},",
          "SURRENDERUPDATETIME = #{surrenderupdatetime,jdbcType=TIMESTAMP},",
          "SURRENDERMSG = #{surrendermsg,jdbcType=VARCHAR},",
          "REQUESTEDTIME = #{requestedtime,jdbcType=TIMESTAMP}",
        "where PROPOSALSID = #{proposalsid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(GeProposalMain record);
}