package com.future.dao.idao;

import com.future.dao.po.ParentProjectInfo;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ParentProjectInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parent_project_info
     *
     * @mbggenerated
     */
    @Delete({
        "delete from parent_project_info",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parent_project_info
     *
     * @mbggenerated
     */
    @Insert({
        "insert into parent_project_info (id, parent_project_name)",
        "values (#{id,jdbcType=INTEGER}, #{parentProjectName,jdbcType=VARCHAR})"
    })
    int insert(ParentProjectInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parent_project_info
     *
     * @mbggenerated
     */
    int insertSelective(ParentProjectInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parent_project_info
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, parent_project_name",
        "from parent_project_info",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    ParentProjectInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parent_project_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ParentProjectInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parent_project_info
     *
     * @mbggenerated
     */
    @Update({
        "update parent_project_info",
        "set parent_project_name = #{parentProjectName,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ParentProjectInfo record);
}