package com.future.dao.idao;

import com.future.dao.po.ProjectInfo;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import java.util.List;

public interface ProjectInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_info
     *
     * @mbggenerated
     */
    @Delete({
        "delete from project_info",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_info
     *
     * @mbggenerated
     */
    @Insert({
        "insert into project_info (id, project_name, ",
        "parent_project_id, project_type, ",
        "develop_field, workload, ",
        "handle_state, internal_task_state, ",
        "external_task_state, joint_debug_date, ",
        "requirements_received_date, owner_id)",
        "values (#{id,jdbcType=INTEGER}, #{projectName,jdbcType=VARCHAR}, ",
        "#{parentProjectId,jdbcType=INTEGER}, #{projectType,jdbcType=TINYINT}, ",
        "#{developField,jdbcType=VARCHAR}, #{workload,jdbcType=REAL}, ",
        "#{handleState,jdbcType=TINYINT}, #{internalTaskState,jdbcType=TINYINT}, ",
        "#{externalTaskState,jdbcType=TINYINT}, #{jointDebugDate,jdbcType=DATE}, ",
        "#{requirementsReceivedDate,jdbcType=DATE}, #{ownerId,jdbcType=INTEGER})"
    })
    int insert(ProjectInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_info
     *
     * @mbggenerated
     */
    int insertSelective(ProjectInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_info
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, project_name, parent_project_id, project_type, develop_field, workload, ",
        "handle_state, internal_task_state, external_task_state, joint_debug_date, requirements_received_date, ",
        "owner_id",
        "from project_info",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    ProjectInfo selectByPrimaryKey(Integer id);

    @Select({
            "select",
            "id, project_name, parent_project_id, project_type, develop_field, workload, ",
            "handle_state, internal_task_state, external_task_state, joint_debug_date, requirements_received_date, ",
            "owner_id",
            "from project_info",
            "where owner_id = #{ownerId,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    List<ProjectInfo> selectByOwnerId(Integer ownerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProjectInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_info
     *
     * @mbggenerated
     */
    @Update({
        "update project_info",
        "set project_name = #{projectName,jdbcType=VARCHAR},",
          "parent_project_id = #{parentProjectId,jdbcType=INTEGER},",
          "project_type = #{projectType,jdbcType=TINYINT},",
          "develop_field = #{developField,jdbcType=VARCHAR},",
          "workload = #{workload,jdbcType=REAL},",
          "handle_state = #{handleState,jdbcType=TINYINT},",
          "internal_task_state = #{internalTaskState,jdbcType=TINYINT},",
          "external_task_state = #{externalTaskState,jdbcType=TINYINT},",
          "joint_debug_date = #{jointDebugDate,jdbcType=DATE},",
          "requirements_received_date = #{requirementsReceivedDate,jdbcType=DATE},",
          "owner_id = #{ownerId,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ProjectInfo record);
}