package com.future.dao.idao;

import com.future.dao.po.SC;
import org.apache.ibatis.annotations.Insert;

public interface SCMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SC
     *
     * @mbggenerated
     */
    @Insert({
        "insert into SC (Sid, Cid, ",
        "score)",
        "values (#{sid,jdbcType=INTEGER}, #{cid,jdbcType=INTEGER}, ",
        "#{score,jdbcType=INTEGER})"
    })
    int insert(SC record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SC
     *
     * @mbggenerated
     */
    int insertSelective(SC record);
}