package com.future.dao.idao;

import com.future.dao.po.Student;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Student
     *
     * @mbggenerated
     */
    @Delete({
        "delete from Student",
        "where Sid = #{sid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Student
     *
     * @mbggenerated
     */
    @Insert({
        "insert into Student (Sid, Sname, ",
        "Sage, Ssex)",
        "values (#{sid,jdbcType=INTEGER}, #{sname,jdbcType=VARCHAR}, ",
        "#{sage,jdbcType=INTEGER}, #{ssex,jdbcType=VARCHAR})"
    })
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Student
     *
     * @mbggenerated
     */
    int insertSelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Student
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "Sid, Sname, Sage, Ssex",
        "from Student",
        "where Sid = #{sid,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Student selectByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Student
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Student
     *
     * @mbggenerated
     */
    @Update({
        "update Student",
        "set Sname = #{sname,jdbcType=VARCHAR},",
          "Sage = #{sage,jdbcType=INTEGER},",
          "Ssex = #{ssex,jdbcType=VARCHAR}",
        "where Sid = #{sid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Student record);
}