package com.future.dao.idao;

import com.future.dao.po.TeamInfo;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface TeamInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_info
     *
     * @mbggenerated
     */
    @Delete({
        "delete from team_info",
        "where id = #{id,jdbcType=TINYINT}"
    })
    int deleteByPrimaryKey(Byte id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_info
     *
     * @mbggenerated
     */
    @Insert({
        "insert into team_info (id, team_name)",
        "values (#{id,jdbcType=TINYINT}, #{teamName,jdbcType=VARCHAR})"
    })
    int insert(TeamInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_info
     *
     * @mbggenerated
     */
    int insertSelective(TeamInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_info
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, team_name",
        "from team_info",
        "where id = #{id,jdbcType=TINYINT}"
    })
    @ResultMap("BaseResultMap")
    TeamInfo selectByPrimaryKey(Byte id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TeamInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_info
     *
     * @mbggenerated
     */
    @Update({
        "update team_info",
        "set team_name = #{teamName,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=TINYINT}"
    })
    int updateByPrimaryKey(TeamInfo record);
}